### ISSUE TITLE
Scaling with TusD 

### ISSUE THREAD

**Issue by avil-jc01** [tus/tusd#1001]
**Question**
Hello, I wanted to ask about the concept of scaling horizontally with TusD. Right now, we are deploying to Azure as an App Service, but because of some of the scaling abstractions, we're losing access to `/metrics` and a few other complications associated with HA and load balancing. Before reinventing completely the wheel, I wanted to ask about "the right way" to scale tusD from the developers and sanity-check if we're on the right path. 

The scaled out Azure App Service seems to work okay vis-a-vis serving requests; losing access to `/metrics` though is undesirable.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Azure App Service - custom application (Linux backend)
- Used tusd version: 1.10.1
- Used tusd data storage: Azure mount paths
- Used tusd configuration: --mount-path, --behind-proxy and --expose-metrics 
- Used tus client library: tus-js-client reference example

**Comment by Acconut** [comment]
Information about scaling tus (which also applies to tusd) is available in the FAQ at https://tus.io/faq#how-do-i-scale-tus. I recommend you to read this first. Regarding `/metrics`, you can fetch the endpoint for every tusd instance and then accumulate the results. Most metrics can be simply summed up, e.g. number of open connections or errors. I hope this provides a first direction.

**Comment by avil-jc01** [comment]
Thank you, we did visit the FAQ before setting up our scaling implementation. We are using global locks (as opposed to sticky sessions).

> Regarding /metrics, you can fetch the endpoint for every tusd instance and then accumulate the results. Most metrics can be simply summed up, e.g. number of open connections or errors. I hope this provides a first direction.

In our case, we're running into a problem very similar to https://stackoverflow.com/questions/49034293/prometheus-with-several-servers, where the OP is having his `GET /metrics` request load balanced to both/all tusd processes, and getting back essentially sinusoidal data. 

Is there a way to include somehow, a unique identifier, in the `/metrics`response payload? From the other side of the load balancer, is there any way to know if a response came from any one specific TusD instance?

**Comment by avil-jc01** [comment]
It seems like as far as TusD is concerned, we are doing things correctly. TusD doesn't appear to have any native "clustering" or high availability built in at the application-level; it expects HA to be implemented at a higher infra/architecture level it seems. 

I'd be interested to hear if anybody else is using tusd in a similar way (behind a load balancer), and is collecting their Prometheus metrics for all instances.

**Comment by Acconut** [comment]
> I'd be interested to hear if anybody else is using tusd in a similar way (behind a load balancer), and is collecting their Prometheus metrics for all instances.

Yes, we are doing as well. All tusd instances are behind a load balancer, but for the metrics we just iterate through all servers and query their `/metrics` endpoint directly without going through the load balancer at all. If you infrastructure does not allow you to contact individual servers directly, then this might not work for you. But then this might a more general issue with the infrastructure and not a problem specific to tusd.

> Is there a way to include somehow, a unique identifier, in the `/metrics`response payload? From the other side of the load balancer, is there any way to know if a response came from any one specific TusD instance?

It would be possible to include the hostname in the metrics, but that would require the hostname to be unique. And you still have to send many requests in the hope that your load balancer routes your requests to all tusd instances.

> TusD doesn't appear to have any native "clustering" or high availability built in at the application-level; it expects HA to be implemented at a higher infra/architecture level it seems.

I am interested in this. What kind of features would you expect from tusd directly to support clustering better?

**Comment by avil-jc01** [comment]
Thanks again Acconut - appreciate the replies. 

> But then this might a more general issue with the infrastructure and not a problem specific to tusd.

My actual issue is probably this in reality; I don't have any evidence tusd is behaving against expectation; I wanted to start here though to shine visibility into this use case and see if there's any out-of-band advice.

> query their /metrics endpoint directly without going through the load balancer at all

I think that our Azure implementation is going to prevent doing this; based on my research my paths forward are either a) proxy the requests to each instance (ie, to `<instanceid>.<app-name>.azurewebsites.net`) somehow or b) move the Prometheus process to behind the load balancer network boundary. My question I guess becomes an Azure implementation question/issue.

> It would be possible to include the hostname in the metrics

Is this available via config or a runtime argument? My firm is trying to avoid making code changes to tusd for our use case if we can avoid it. But getting Prometheus metrics in the format `metric{hostname=foobarbaz, label2=otherdata}=123.456` would be helpful enough I think. I could take on the querying and aggregation from there, as long as I can be sure every `GET /metrics` response was tagged correctly. If we can continue our general discussion, I'd like to pursue this topic further specifically. 

> I am interested in this. What kind of features would you expect from tusd directly to support clustering better?

As far as we could tell, tusD scales just fine to the limits of the process/VM running it. We tested (single instance) on a 1 core and 2 core VM in early development and the performance scaled fairly linearly with our expectation. Since we didn't see any tusD documentation on horizontal scaling, we just followed what Azure gives us and implemented the global file lock method (instead of sticky sessions). 

But at least in the `/metrics` page, being able to identify by host, or even have a uuid generated, would be great. In `/files` I don't have any specific asks or advice to offer (yet).

**Comment by javila-mechanicode** [comment]
Update:

I was able to do the following hack:

`var (
	requestsTotalDesc = prometheus.NewDesc(
		tusd_requests_total,
		Total number of requests served by tusd per method.,
		[]string{method, computername}, nil)
`

and similar to each label for each metric in `pkg/prometheuscollector/prometheuscollector.go`. Correspondingly, I also added

`
		metrics <- prometheus.MustNewConstMetric(
			errorsTotalDesc,
			prometheus.CounterValue,
			float64(atomic.LoadUint64(valuePtr)),
			strconv.Itoa(httpError.StatusCode),
			httpError.ErrorCode,
			computerName,
		)
` 

to fill in the label, where `computerName` is given by

`
	computerName := os.Getenv("COMPUTERNAME")
`

This seems to produce the desired effect: 
![Screenshot 2023-09-14 at 1 53 29 PM](https://github.com/tus/tusd/assets/117209231/65b1c839-2199-476e-8d4f-a6be9e87e248)


It would be nice if we could have a command-line argument flag, say `--metrics id ENVVAR` where `ENVVAR` is the prometheus metric label (computername in my instance above). I've been hacking in flags.go but don't have it working yet; I've never used flag pkg before. But this functionality above would be nice to have!

**Comment by Acconut** [comment]
> Is this available via config or a runtime argument? My firm is trying to avoid making code changes to tusd for our use case if we can avoid it. But getting Prometheus metrics in the format `metric{hostname=foobarbaz, label2=otherdata}=123.456` would be helpful enough I think.

As you probably discovered, there is no such option so far. It would have to be implemented. That being said, even with the hostname attached to every metric, monitoring any cluster through a load balancer is not guaranteed to reach all instances. This could lead to some instances, whose metrics are never aggregated. Therefore, I am very hesitant to add an option to tusd, which would not really help here. There is also more information (and some alternative solutions) in https://groups.google.com/g/prometheus-users/c/7z4QCdqt5gc.

Since this is not a tusd-specific issue, I recommend you to reach out to the Prometheus community and Azure to see if there is an idiomatic approach to solving this issue. You are not the first person to run into this limitation :) If tusd needs an improvement to work better with an alternative solution, we can talk about adding that.

**Comment by Acconut** [comment]
Maybe that is interesting for you: https://github.com/prometheus-community/PushProx

**Comment by Acconut** [comment]
No, a network disk is not necessary and S3 is sufficient for shared storage. Please also consider https://tus.github.io/tusd/advanced-topics/locks/ carefully.

**Comment by Acconut** [comment]
I haven't used httprouter before, so I cannot comment on that package, but the linked example should be a good starting point, yes. If you haven't  already, I also recommend to read these two resources, which touch on the scaling of tusd:
- https://tus.github.io/tusd/advanced-topics/locks/
- https://tus.io/faq#how-do-i-scale-tus

**Comment by avil-jc01** [comment]
Closing due to staleness
