### ISSUE TITLE
Why is config.validate() called inside UnroutedHandler? Should we let user decide for themselves?

### ISSUE THREAD

**Issue by jimydavis** [tus/tusd#1004]
1. config.validate() should not be called in UnroutedHandler as it is hydrating the config with defaults, it is not just validating it. It is expected that NewHandler comes with all the bells and whistles via the validate call but UnroutedHandler should be slightly more primitive. User can always copy paste the code.
  1. Alternatively, we can make Validate public and let user call it themselves.
1. config.isAbs should not be private if we wish for user to construct their own validate() function.

**Comment by Acconut** [comment]
I don't understand your point, sorry. Yes, `validate` might be ill-named as it also sets the defaults, but why would you want to disable this behavior? The handler depends on all config fields to be set, so it is important that default values are set when no value is provided by the caller. In the end, this also benefits the user as it reduces the possibility of errors.

> 1. UnroutedHandler should be slightly more primitive. User can always copy paste the code.

I disagree with both. UnroutedHandler should be the same as the routed Handler, except for the routing. Everything else should be the same. Also, requiring the user to duplicate internal code is not the preferred approach.
