### ISSUE TITLE
Will There Be a NewUnroutedHandlerWithHooks?

### ISSUE THREAD

**Issue by jimydavis** [tus/tusd#1005]
There is a `NewHandlerWithHooks` in v2. Will there be a `NewUnroutedHandlerWithHooks` ? From looking at the code, it seems like if I start copy pasting the language inside `NewHandlerWithHooks`, I will end up forking the whole repo.

Thank you!

**Comment by Acconut** [comment]
You can access the unrouted handler from a routed handler through the embedded struct. So maybe you can do the following:

```go
routedHandler := hooks.NewHandlerWithHooks(...)
unroutedHandler := routedHandler.UnroutedHandler
```

I haven't tried it yet, but if this works, we can add this as an implementation for `NewUnroutedHandlerWithHooks`
