### ISSUE TITLE
Why Does HookEvent.HTTPRequest Not Have Body?

### ISSUE THREAD

**Issue by jimydavis** [tus/tusd#1006]
- Why Does HookEvent.HTTPRequest Not Have Body? Is this intentional?
- As an alternative, can I put whatever I want into the Metadata header? For example a base64 encoded json as I cannot place it into the body as I understand it. Does TusD functionally ignore the Metadata and pass it along?

Thank you.

**Comment by Acconut** [comment]
The request body is used by the tus protocol to transfer the upload data in PATCH and sometimes also the POST requests. Any value is usually consumed by tusd on its own. That is why (our) tus clients do not allow modifying the body and why (our) tus servers do not provide access to them. 

Additional data can either be added as meta data or additional headers to the request. Meta data will be parsed by tusd. The parsed meta data and request headers are provided to the hooks.
