### ISSUE TITLE
Rate limit for webhook requests

### ISSUE THREAD

**Issue by mjkoffice** [tus/tusd#1011]
**Rate limit:**
Is there an option to control the rate of webhook requests produced by the tusd server application?
To set e.g. an interval for emitting the progress related webhook requests.
In particular parallel uploads of larger files create a considerable amount of requests and therefore load on a given API.
What options are there to scale the webhook integration?

My thoughts:
Of course one option would be to apply rate limiting/request queuing on the API side.
Or using the go package in a custom web application and adding a different logic on related events?

Details:
- Used tusd version: 1.6
- Used tusd data storage: disk store, AWS S3
- Used tusd configuration: tusd -host 127.0.0.1 -port 8080 -behind-proxy -hooks-http https://api.example.org/webhooks/uploads -hooks-http-retry 5 -hooks-http-backoff 2 -upload-dir /dir/uploads (behind Nginx proxy)
- Used tus client library: tus-js-client, various

Thanks in advance!

**Comment by Acconut** [comment]
> To set e.g. an interval for emitting the progress related webhook requests.

Yes, tusd v2 supports the `-progress-hooks-interval` flag. It specifies that interval at which `post-receive` hooks are emitted. For example, to only trigger them every 5s, use `-progress-hooks-interval 5s`.

I hope that already helps with your issues!

**Comment by Acconut** [comment]
Great to hear that it works for you :)
