### ISSUE TITLE
How to specify a path based on the information in MetaData

### ISSUE THREAD

**Issue by dogger123** [tus/tusd#1024]
**Question**
I want to specify a upload path based on the information in MetaData. The current programme is that I need to specify a fixed path first, but my requirement is to upload to a different path based on the requested content each time. How can I achieve this?

**Setup details**
- Operating System: linux
- Used tusd version: 1.12.1
- Used tusd data storage: disk Store,
- Used tus client library:  tus-js-client,
Here is my code：
```golang
func UploadsHandler() *tusd.UnroutedHandler {
	tmpPath, _ := GetTemporaryFileSpacePath()
	store := filestore.FileStore{
		Path: tmpPath,
	}
	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	handler, err := tusd.NewUnroutedHandler(tusd.Config{
		BasePath:                "/upload/",
		StoreComposer:           composer,
		NotifyCompleteUploads:   true,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %w", err))
	}

	go func() {
		for {
			select {
			case event := <-handler.CompleteUploads:
				metaData, err := finishCallback(event)
				targetPath = metaData["path"]
                                moveFile(tmpPath, targetPath )
	return handler
}

**Comment by dogger123** [comment]
Since I'm using ceph storage, it's sometimes very time-consuming to **move** across pvc, and I wanted to skip this step of the operation

**Comment by Acconut** [comment]
This is not fully possible right now. You can use the pre-create hook and set ChangeFileInfo.ID to a custom file name (https://github.com/tus/tusd/blob/main/docs/hooks.md#hook-requests-and-responses). This ID will then be the file name where tusd saves the data and will also be part of the upload URL. However, the ID must not contain a slash for now, so you cannot use subfolders: https://github.com/tus/tusd/issues/1030

We hope to improve support for this in the future.
