### ISSUE TITLE
v2.1.0 cpu 100%

### ISSUE THREAD

**Issue by dcboy** [tus/tusd#1028]
**Question**
i upgrade new version server side as some logic with v1.13.0, but the new version run cpu 100%

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: [ Linux, macOS]
- Used tusd version: v2.1.0
- Used tusd data storage: [e.g. disk store]
- Used tusd configuration: Using the tusd package programmaticallya
- Used tus client library: golang tus client

this is pprof cpu profile
[profile.zip](https://github.com/tus/tusd/files/13259837/profile.zip)

**Comment by Acconut** [comment]
Was this capture while performing a single upload or while load testing it? What storage did you use? How was the CPU usage in tusd v1 for you?

**Comment by dcboy** [comment]
> Was this capture while performing a single upload or while load testing it? What storage did you use? How was the CPU usage in tusd v1 for you?

just single file upload and use local filestore, tusd v1 only cpu 2%

**Comment by Acconut** [comment]
Looking at the profile, I didn't spot any obvious issue. 66% of the samples are spent inside syscall, as is expected for a program that reads from network and writes to disk.

I wasn't able to reproduce high CPU usage locally when uploading large files using tusd. Can you provide me with a method to reproduce this issue?

**Comment by dcboy** [comment]
i will try furnish demo,thx

**Comment by dcboy** [comment]
i have reconstruct hold logic, now is ok

**Comment by Acconut** [comment]
Glad that you found a solution! Could you share a few more details to help other users if they also run into similar issues? Was the root cause part of your own Go code?
