### ISSUE TITLE
Dynamicly setting S3 Bucket

### ISSUE THREAD

**Issue by ADDNW** [tus/tusd#1029]
**Question**
In my use case I need tusd to be able to save to one of few buckets, chosen based on f.e. metadata (s3 bucket name), probably at pre-finish hook. Is there a way to do it? (any version, but at best v2.0+, as I'd like to use this parallel upload to s3)

**Comment by Acconut** [comment]
No, this is currently not possible. Your only choice right now is to transfer the object to another bucket after the upload is complete.

**Comment by Acconut** [comment]
This will be implemented in v3 (release date unknown yet) with https://github.com/tus/tusd/pull/1167.
