### ISSUE TITLE
"s3store: unable to create multipart upload" in 2.0.0 with S3-compatible storage

### ISSUE THREAD

**Issue by maltsev** [tus/tusd#1058]
After upgrading to version 2.0.0 file uploading via Uppy.js fails with the following error:

```
ERR_INTERNAL_SERVER_ERROR: s3store: unable to create multipart upload:
operation error S3: CreateMultipartUpload, failed to resolve service endpoint, endpoint rule error, Custom endpoint `s3.sto1.safedc.net` was not a valid URI
```

**Setup details**

- Operating System: Linux (Kubernetes), run as Docker image `tusproject/tusd:v2.0.0`
- Used tusd version: 2.0.0
- Used tusd data storage: a S3-compatible storage ([SafeSpring](https://docs.safespring.com/storage/generalinfo/))
- Used tusd configuration: `tusd -s3-bucket=my-bucket-name -behind-proxy -s3-endpoint=s3.sto1.safedc.net` 
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
Does it work if you explicitly mention the protocol, so the value becomes a valid URI?

> -s3-endpoint=https://s3.sto1.safedc.net

**Comment by maltsev** [comment]
Yes, now it works (both with v2 and v1). Thanks a lot for your help!
