### ISSUE TITLE
Breacking change on Hook-Name header

### ISSUE THREAD

**Issue by mosi-kha** [tus/tusd#1061]
**Describe the bug**
in tusd v1, we had `Hook-Name` header to determine hook but in tusd v2 this header removed and set to payload with `Type` so in states we have problem to parse body.

**To Reproduce**
Run tusd v2

**Expected behavior**
In addition to being in body, it should be in the header as well

**Setup details**
- Operating System: Linux
- Used tusd version: v2
- Used tusd data storage: S3 
- Used tus client library: tus-py-client

**Comment by Acconut** [comment]
tusd v2 included breaking changes as explained in the release notes and the accompanying blog post: https://github.com/tus/tusd/releases/tag/v2.0.0. The new version includes a reworked hook interface, so you need to adapt to the new interface if you upgrade tusd.

**Comment by mosi-kha** [comment]
@Acconut Thanks for the response, It would be better if it remained in the header
