### ISSUE TITLE
domain truncated

### ISSUE THREAD

**Issue by foolishwang** [tus/tusd#107]
hi, 
 I run tusd  behind nginx per documents, 
 my domain is  upload.xxxx.com
 but the upload truncate my domain to https://upload/

[tusd] event="UploadCreated" id="6e896fbfb6ac8426bf363aa104b49151" size="47320" url="https://upload/files/6e896fbfb6ac8426bf363aa104b49151"

**Comment by Acconut** [comment]
This looks like a misconfigured nginx proxy to me. Please provide the relevant section of the nginx configuration where you tell it to proxy requests to the tusd server and also the command which you use to invoke the tusd binary. This would help us a lot with resolving this problem.

**Comment by Acconut** [comment]
Closing due to lack of information. Feel free to add a comment if you want to continue the discussion.
