### ISSUE TITLE
about temp file

### ISSUE THREAD

**Issue by aixj1984** [tus/tusd#108]
when upload one file, in the dirct of data genenrate two tempfile。 one file is lock file ， end of upload deleted，but other pid file not delete

**Comment by Acconut** [comment]
I'm sorry but I have no idea what you actually mean. You are correct that a `.lock` file is there as long as an client is uploading but there should be no "pid file". Please be more descriptive.

**Comment by aixj1984** [comment]
[
![qq 20170213091108](https://cloud.githubusercontent.com/assets/2499352/22868082/ae84f0ee-f1cc-11e6-90ca-77cea9769e63.png)
](url)   please check the picture，I give the  tag on the picture.

**Comment by Acconut** [comment]
Ok, thanks for clarifying things. This file is indeed a temporary one used for creating the `.lock` file. What concerns you about it?

**Comment by aixj1984** [comment]
why don't delete it after upload file?

I findthe temp file in the folder , i think the file must be deleted .

**Comment by Acconut** [comment]
You are correct, usually it will be removed however, it may have issues on Windows. I can look into this once I have some time left, as this has looks like a low priority.

**Comment by Acconut** [comment]
This should have been solved with #117. Feel free to comment if this issue is still arising for you.
