### ISSUE TITLE
Am I doing the gcp bucket set up right? keeps failing with EOF error

### ISSUE THREAD

**Issue by emilaleksanteri** [tus/tusd#1124]
**Question**
Am I doing the gcp bucket set up right? keeps failing with EOF error, if I change the storage to be local file storage, then everything works perfect. My client is pretty much identical from the Uppy.js example for react
**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: macOS
- Used tusd version: 2.4.0
- Used tusd data storage: Google Cloud Storage
- Used tusd configuration: Using the go library to have it on my server
- Used tus client library:  tus-js-client, Uppy.js

Here is my current handler creation:
```go
func FileUploadHandler() *tusd.UnroutedHandler {
	bucket := "sample-bucket"
	absPath, _ := filepath.Abs("./")
	gcpCredentials := filepath.Join(absPath, "config", "credentials.json")

	gcsService, err := gcsstore.NewGCSService(gcpCredentials)
	if err != nil {
		log.Fatalf("Unable to create gcsService: %s\n", err.Error())
	}

	locker := memorylocker.New()

	store := gcsstore.New(bucket, gcsService)
	store.ObjectPrefix = "store-products-csv"

	composer := tusd.NewStoreComposer()
	store.UseIn(composer)
	locker.UseIn(composer)

	handler, err := tusd.NewUnroutedHandler(tusd.Config{
		BasePath:              "/store-products-csv/",
		StoreComposer:         composer,
		NotifyCompleteUploads: true,
		NotifyCreatedUploads:  true,
		Cors: &tusd.CorsConfig{
			Disable: true,
		},
	})

	if err != nil {
		log.Fatalf("could not create tusd handler: %s\n", err.Error())
	}

	go func() {
		for {
			event := <-handler.CompleteUploads
			fmt.Printf("\nSuccessfully uploaded a file with an id: %v", event.Upload.ID)
			createdUpload := <-handler.CreatedUploads
			fmt.Printf("\nCreated an upload with an id: %v", createdUpload.Upload.ID)
		}
	}()

	return handler

}
```

routes set up with chi:
```go
        r.Post("/store-products-csv/", fileRoutes.PostFile)
	r.Head("/store-products-csv/{id}", fileRoutes.HeadFile)
	r.Patch("/store-products-csv/{id}", fileRoutes.PatchFile)
	r.Get("/store-products-csv/{id}", fileRoutes.GetFile)
```

**Comment by Acconut** [comment]
That's odd. EOF usually means that the request got interrupted and thus tusd received the end of file (EOF) earlier than expected. Can you send us the tusd logs?

**Comment by emilaleksanteri** [comment]
> That's odd. EOF usually means that the request got interrupted and thus tusd received the end of file (EOF) earlier than expected. Can you send us the tusd logs?

Is there way to get them out when using the library in a go server? I tried using the logger on the config struct but saw nothing on the logs🤔

**Comment by Acconut** [comment]
Oh, you are getting EOF for POST requests? That's odd since usually no body is transferred for POST requests. What does your client code look like? Are you setting [`uploadDataDuringCreation`](https://github.com/tus/tus-js-client/blob/main/docs/api.md#uploaddataduringcreation)?

**Comment by emilaleksanteri** [comment]
@Acconut 
so the client set up looks like this:
```ts
import { IslandContainer } from '@/components/Island';
import {
  Button,
  Grid,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Typography,
} from '@mui/material';
import { Folder } from '@mui/icons-material';
import React, { useState } from 'react';
import Uppy from '@uppy/core';
import Tus from '@uppy/tus';
import { Dashboard } from '@uppy/react';
import UppyDashboard from '@uppy/dashboard';

const STUBFILES = [
  {
    name: 'groceries-1.csv',
    date: new Date('04/26/2024').toJSON(),
  },
  {
    name: 'groceries-2.csv',
    date: new Date('04/26/2024').toJSON(),
  },
];

import '@uppy/core/dist/style.css';
import '@uppy/dashboard/dist/style.css';
import '@uppy/drag-drop/dist/style.css';
import '@uppy/file-input/dist/style.css';
import '@uppy/progress-bar/dist/style.css';

export default function Data() {
  const [showInlineDashboard, setShowInlineDashboard] = useState(false);
  const [uppy] = useState(() =>
    new Uppy({ debug: true, autoProceed: true }).use(UppyDashboard, { inline: true }).use(Tus, {
      endpoint: 'http://127.0.0.1:8081/store-products-csv/',
      retryDelays: [0, 3000],
      addRequestId: true,
      uploadDataDuringCreation: true,
    }),
  );

  return (
    <IslandContainer>
      <Grid>
        <Typography variant="h6">Uploaded product files</Typography>
        <List>
          {STUBFILES.map((file, idx) => (
            <ListItem key={idx}>
              <ListItemIcon>
                <Folder />
              </ListItemIcon>
              <ListItemText primary={file.name} secondary={file.date} />
            </ListItem>
          ))}
        </List>
        <label>
          <Button
            onClick={() => {
              setShowInlineDashboard(!showInlineDashboard);
            }}
          >
            Show Dashboard
          </Button>
        </label>
        {showInlineDashboard && (
          <Dashboard
            uppy={uppy}
            fileManagerSelectionType="files"
            metaFields={[{ id: 'name', name: 'Name', placeholder: 'File name' }]}
          />
        )}
      </Grid>
    </IslandContainer>
  );
}
```
Added the `uploadDataDuringCreation` as true now and the upload shows progress and then fails with EOF, logs show these errors now:
```bash
2024/05/02 10:55:45 "POST http://127.0.0.1:8081/store-products-csv/ HTTP/1.1" from 127.0.0.1:62786 - 500 31B in 4.202125ms
time=2024-05-02T10:55:48.504+01:00 level=ERROR msg=InternalServerError method=POST path=/store-products-csv/ requestId=9e8f9cb6-b57f-4471-ae11-b41c635cd419 message=EOF
time=2024-05-02T10:55:48.504+01:00 level=INFO msg=ResponseOutgoing method=POST path=/store-products-csv/ requestId=9e8f9cb6-b57f-4471-ae11-b41c635cd419 status=500 body="ERR_INTERNAL_SERVER_ERROR: EOF\n"
2024/05/02 10:55:48 "POST http://127.0.0.1:8081/store-products-csv/ HTTP/1.1" from 127.0.0.1:62786 - 500 31B in 14.373083ms
```

**Comment by emilaleksanteri** [comment]
@Acconut Did not have it before, so if I disable it, the upload fails immediately with the same errors as before

**Comment by emilaleksanteri** [comment]
Here is also my browser network tab with the error when using `uploadDataDuringCreation`

![Screenshot 2024-05-02 at 11 19 50](https://github.com/tus/tusd/assets/86009801/86e068e5-05d5-4901-aad4-d26ca9caef93)

**Comment by emilaleksanteri** [comment]
@Acconut after furhter investigation I noticed that the EOF error comes from this line in the gcsstore https://github.com/tus/tusd/blob/d24016a63c5d079eef8b1c44336d627ad074a97c/pkg/gcsstore/gcsstore.go#L157

No you know what might cause the file info not being written/read correctly? on gcsstore I do see that write info returns that it has written 408 bytes for the info json so perhaps something going on with reading it from the bucket

**Comment by Acconut** [comment]
> buf read to return an error although all of the .info data gets read into the buffer.

Thanks for looking into this, that's interesting! The EOF value in this case does not represent a real error, but rather that the file file was read from GCS. See the [documentation for the `Read` method](https://pkg.go.dev/io#Reader).

We can try fixing this by replacing

https://github.com/tus/tusd/blob/d24016a63c5d079eef8b1c44336d627ad074a97c/pkg/gcsstore/gcsstore.go#L156-L160

with

```go
buf, err := io.ReadAll(r)
if err != nil {
	return info, err
}
```

ReadAll does not return EOF, so this error should not appear there. Could you give this a try and see if it helps?

**Comment by emilaleksanteri** [comment]
@Acconut that did the trick, want me to open a PR for this?

**Comment by Acconut** [comment]
That's great! Yes, please open a PR!
