### ISSUE TITLE
validating video files using blocking hooks

### ISSUE THREAD

**Issue by mohamadrezza** [tus/tusd#1133]
**Describe the bug**
I want to validate my uploading video files using ffprobe and send appropriate response to user (for validation).
The documentation suggests using blocking hooks for this purpose(pre-create,pre-finish). However, when working with the pre-finish hook, I don't have access to the video file to perform validation.
and i get this error : "ERR_LOCK_TIMEOUT: failed to acquire lock before timeout"
but when i work with post-finish hook, everything works fine, but i can't send response to client in this step.
i implemented my hook as a webhook

**Expected behavior**
i want to access video files for validating with ffprobe in pre-finish hook

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: macOS
- Used tusd version: v2.3.0
- Used tusd data storage: S3
- Used tusd configuration: -s3-bucket mybucket -s3-endpoint http://minio:9000
      --hooks-http http://host.docker.internal:8000/v1/upload/handle-tusd-hooks
      --hooks-enabled-events post-finish,post-terminate,post-create,pre-create,pre-finish
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
Are you trying to send a GET request to the upload resource in the pre-finish hook? That won't work because the upload is still locking until pre-finish (and other request handling) finishes. You would have to fetch the resource from S3 directly.

**Comment by mohamadrezza** [comment]
> Are you trying to send a GET request to the upload resource in the pre-finish hook? That won't work because the upload is still locking until pre-finish (and other request handling) finishes. You would have to fetch the resource from S3 directly.

but i can access file when the data storage is local disk.
it's weird for me that we don't have access to the file in pre-finish on s3, unlike the default back-and-storage?

**Comment by Acconut** [comment]
What do you mean exactly when you say that you are "accessing the files"? Can you describe in more details what you are doing exactly? Or could you even provide an example to produce this issue? I am still not entirely sure what you are attempting here.

**Comment by mohamadrezza** [comment]
> What do you mean exactly when you say that you are "accessing the files"? Can you describe in more details what you are doing exactly? Or could you even provide an example to produce this issue? I am still not entirely sure what you are attempting here.

as i mentioned before,i mean i can't read file with ffprobe (i get ERR_LOCK_TIMEOUT error)...
when the data storage is local disk the i can read the file with ffprobe on pre-finish hook, and everything works fine
but when the storage is s3, it returns ERR_LOCK_TIMEOUT error
