### ISSUE TITLE
AzureService is using a deprecated SDK (github.com/Azure/azure-storage-blob-go/azblob)

### ISSUE THREAD

**Issue by vikas-rajvanshy** [tus/tusd#1135]
**Is your feature request related to a problem? Please describe.**
github.com/Azure/azure-storage-blob-go/azblob is deprecated, will officially EOL later this year. The recommended replacement is github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blockblob

**Describe the solution you'd like**
Port AzService to use the supported SDK

**Describe alternatives you've considered**
Tried replacing it myself, the changes across SDK's are substantial - needs someone with more context to make the change. Ex. seems like there is now a client per blob rather than singleton across lifetime.

**Can you provide help with implementing this feature?**
Don't have much context here, but willing to help

**Additional context**

**Comment by Acconut** [comment]
Thank you for bringing this to our attention. I will try to have a look at this soon. A migration guide is at https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/migrationguide.md, which seems rather simple, but your experience points in the other direction. Let's hope that the necessary changes on our side are not significant.
