### ISSUE TITLE
How to delete files uploaded to server?

### ISSUE THREAD

**Issue by gugelshit9** [tus/tusd#1145]
**Question**
I want to delete files uploaded to server example /files/1213-123-12312-2312 (uuid)

**Setup details**
Please provide following details, if applicable to your situation:
- Linux
- Used tusd version: 2.4.0
- Used tusd data storage: disk store
- Used tusd configuration: what req should i send?
- Used tus client library:  tus-js-client

**Comment by Acconut** [comment]
Send a DELETE request to the upload URL: https://tus.io/protocols/resumable-upload#termination
