### ISSUE TITLE
Extract ID from Path is broken if base path is provided

### ISSUE THREAD

**Issue by linusr** [tus/tusd#1153]
**Question**
After upgrading tusd package noticed 404 errors for PATCH request.

> 2024/07/04 16:51:17 INFO ResponseOutgoing method=PATCH path=/media/upload/63f0f86e643ed46472fb4fafa654b274+zzgpwSfRXuzhE1QskfccW6dRWG50j5dn48_kupnC.plOTtLd9_TtedwtBwOwvZmI3YD8ItxjOunTAcLhGJ04Dz2C5UsnDE7o9_I1zmcia90xHQQ_yZxV70Ox8Hxqr97.osT_E45G1zvB1qUOc5uppmMWXGG4Gcc7XTj0N_qjsxg- requestId="" id=media/upload/63f0f86e643ed46472fb4fafa654b274+zzgpwSfRXuzhE1QskfccW6dRWG50j5dn48_kupnC.plOTtLd9_TtedwtBwOwvZmI3YD8ItxjOunTAcLhGJ04Dz2C5UsnDE7o9_I1zmcia90xHQQ_yZxV70Ox8Hxqr97.osT_E45G1zvB1qUOc5uppmMWXGG4Gcc7XTj0N_qjsxg- status=404 body="ERR_UPLOAD_NOT_FOUND: upload not found\n"

While comparing the difference noticed the generated Upload ID seems odd.

Not clear why such lengthy ID is being generated and how to debug this further.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: [ Linux, macOS]
- Used tusd version: v2.4.0 , also tested with v2.5.0-rc1
- Used tusd data storage: [AWS S3]
- Used tus client library: [Uppy.js]

**Comment by Acconut** [comment]
This length is normal for the S3 store as it needs to encode the object ID and the multipart ID for S3 multipart uploads in the upload ID. That is not a bug. In future version I hope to change this and remove the multipart ID (the second part after the `+` sign) from the upload ID. But that is not the case yet.

The problem might be that it considers `media/upload/` to be part of the upload ID, but I suppose it should be a path prefix instead. You might have to add `-base-path /media/upload/` to the CLI.

If that doesn't work, please share you entire tusd configuration, as was also requested in the issue template.

**Comment by linusr** [comment]
>You might have to add -base-path /media/upload/ to the CLI

Not using the CLI but embedded as Go package.

tusd.Config.BasePath is configured to `domain_name/media/upload/` which is reflected here in logs,

>path=/media/upload/63f0f86e643ed46472fb4fafa654b274+zzgpwSfRXuzhE1QskfccW6dRWG50j5dn48_kupnC.plOTtLd9_TtedwtBwOwvZmI3YD8ItxjOunTAcLhGJ04Dz2C5UsnDE7o9_I1zmcia90xHQQ_yZxV70Ox8Hxqr97.osT_E45G1zvB1qUOc5uppmMWXGG4Gcc7XTj0N_qjsxg-

**Comment by linusr** [comment]
Issue started after v2.2.2

In v2.2.2 extractIDFromPath method uses regex which removes the base path and only returns the id,

> result := reExtractFileID.FindStringSubmatch(url)

In v2.4.0, 
> return strings.Trim(path, "/")

Also noticed the comment,
>extractIDFromPath extracts the upload ID from a path, which has already been stripped of the base path (done by the user)

Unfortunately this is not clearly documented.

Is it expected to rewrite path before forwarding all request to tus unrouted handlers?

**Comment by Acconut** [comment]
Do you use http.StripPrefix?

https://github.com/tus/tusd/blob/585d7a57110a544809fab98c683cdf7331b8e52a/pkg/handler/doc.go#L67
https://github.com/tus/tusd/blob/585d7a57110a544809fab98c683cdf7331b8e52a/examples/server/main.go#L60

**Comment by linusr** [comment]
Nope. Let me test this out. Thanks.

**Comment by linusr** [comment]
All works after removing the custom path `http.Handle("/files/", http.StripPrefix("/files/", handler))`
