### ISSUE TITLE
s3store: unable to create multipart upload

### ISSUE THREAD

**Issue by mohamadrezza** [tus/tusd#1154]
**Describe the bug**
While I'm trying to upload to my s3 tusd returns this error:
2024/07/09 13:09:55.756983 level=ERROR event=InternalServerError method=POST path="" requestId="" message="s3store: unable to create multipart upload:\noperation error S3: CreateMultipartUpload, https response error StatusCode: 404, RequestID: , HostID: , api error NotFound: Not Found"
(I can upload to my s3 successfully without tusd but when I integrate it with tusd I face with this error)
**Expected behavior**
when I try it with my local s3 (using minio) everything works fine

**Setup details**
- Operating System: macOS
- Used tusd version:  tusproject/tusd:sha-775b805 (docker image)
- Used tusd data storage: AWS S3
- Used tusd configuration:    command: -s3-bucket avt -s3-endpoint  http://my-s3-address.com:9000
- Used tus client library:tus-js-client

**Comment by Acconut** [comment]
My first instinct would be to look at the s3 endpoint you provided to tusd and check if that URL is correct. Maybe you need to append a specific path. But I assume you found the problem on your own. Let me know if you need more help.
