### ISSUE TITLE
Local storage - folder hierarchy

### ISSUE THREAD

**Issue by edwh** [tus/tusd#1157]
Is there any standard way of making tusd put files in split folders, e.g. by date?  This would make archiving easier.

**Comment by Acconut** [comment]
tusd v2.5.0-rc1 supports path customization using the `pre-create` hook. Please see https://tus.github.io/tusd/advanced-topics/hooks/ and the `Storage` property for more details.

**Comment by edwh** [comment]
Thanks.  I saw that, but I wasn't sure how it would work for also serving up the file via `GET`.  Is there a corresponding hook for that side?

**Comment by Acconut** [comment]
GET requests, just like HEAD, PATCH, or DELETE, are sent to the upload URL, which is based in the upload ID. The pre-create hook can also customize the upload ID. See https://tus.github.io/tusd/storage-backends/local-disk/ for details

**Comment by edwh** [comment]
I think I follow.  Thanks.
