### ISSUE TITLE
Checking current usage vs limit using /quota endpoint.

### ISSUE THREAD

**Issue by edwh** [tus/tusd#1158]
There's an endpoint at `quota`.  When I query that, I always get this back:

`{"X-RateLimit-Limit":2500, "X-RateLimit-Remaining":2500, "X-RateLimit-Reset":0}`

I was expecting that `X-RateLimit-Remaining` would decrease over time as I made requests, and then get reset back up at the start of the next hour.  Am I misunderstanding what it means?

I'd like to be able to check where I currently am vs the usage limit so that I can spot well in advance if I'm likely to hit it.

**Comment by Acconut** [comment]
Tusd does not provide such an endpoint. You are likely hitting some other service's API.

**Comment by edwh** [comment]
Sheesh, I'm an idiot.  You're absolutely right, sorry.
