### ISSUE TITLE
Upload-Metadata handling not working

### ISSUE THREAD

**Issue by trickkiste** [tus/tusd#116]
Upload-Metadata handling is not working.

Anything I am sending with this HEADER in a POST request for upload endpoint creation is discarded! The Metadata does neither make it to the hooks, nor is it in the response of a HEAD request to an already created upload endpoint.

It appears like this was introduced by switching things from handler to unroutedHandler. This is only an educated guess for now - pull request #36 .

Here a quick verification of what I am talking about:

curl -i -X OPTIONS http://master.tus.io/files/
```
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Tue, 28 Feb 2017 05:19:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Tus-Extension: creation,creation-with-upload,termination
Tus-Max-Size: 1000000000
Tus-Resumable: 1.0.0
Tus-Version: 1.0.0
X-Content-Type-Options: nosniff
King: marius
```
"metadata" is missing in Tus-Extension header

When you then create an upload endpoint with POST with additional metadata in the header and then check it with HEAD, the Upload-Metadata is not there. While according to protocol spec, it should.

curl -i -X POST -H "Upload-Length: 17274436" -H "Tus-Resumable: 1.0.0" -H "Upload-Metadata: filename xxx" http://master.tus.io/files/
```
HTTP/1.1 201 Created
Server: nginx/1.10.2
Date: Tue, 28 Feb 2017 05:19:59 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: http://master.tus.io/files/ee8ed2e66c94634e0bb92f3c50197e16
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
King: marius
```
curl -i -X HEAD --head -H "Tus-Resumable:1.0.0" http://master.tus.io/files/ee8ed2e66c94634e0bb92f3c50197e16
```
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Tue, 28 Feb 2017 05:20:41 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Cache-Control: no-store
Tus-Resumable: 1.0.0
Upload-Length: 17274436
Upload-Offset: 0
X-Content-Type-Options: nosniff
King: marius
```

**Comment by trickkiste** [comment]
The node.js tus server implementation does not have that problem.

**Comment by Acconut** [comment]
> "metadata" is missing in Tus-Extension header

There is no metadata extension, instead it is a feature of the Creation extension. That's why there is no "metadata" entry in this list.

> curl -i -X POST -H "Upload-Length: 17274436" -H "Tus-Resumable: 1.0.0" -H "Upload-Metadata: filename xxx" http://master.tus.io/files/

I tested it against the master.tus.io server, as you seemed to do, and could not reproduce your issue:
```bash
$ curl -X POST https://master.tus.io/files/ -H "Tus-Resumable: 1.0.0" -H "Upload-Length: 100" -H "Upload-Metadata: filename aGVsbG8=" -i
HTTP/1.1 201 Created
Server: nginx/1.10.2
Date: Tue, 28 Feb 2017 16:35:32 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: https://master.tus.io/files/c5623034b6fd3dd5273021738ed0d6f3
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
King: marius

$ curl -X HEAD https://master.tus.io/files/c5623034b6fd3dd5273021738ed0d6f3 -i -H "Tus-Resumable: 1.0.0"
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Tue, 28 Feb 2017 16:35:52 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Cache-Control: no-store
Tus-Resumable: 1.0.0
Upload-Length: 100
Upload-Metadata: filename aGVsbG8= <-- Metadata is here
Upload-Offset: 0
X-Content-Type-Options: nosniff
King: marius

```

Please be aware of that the values for a metadata **must be base64-encoded** (see `filename aGVsbG8=`). I cannot see if you missed this as you used xxx as your value.

**Comment by trickkiste** [comment]
Thank you so much for this quick response. I was aware of the base64 encoding requirement, just did not think, it would stop working altogether as long as there are no special characters in there.

The main purpose for me is to pass on a JSON Web Token for authentication, so basically three base64 encoded strings separated by dots. Per TUS protocol specification I have to base64 the whole string again or cut it apart into three key value pairs, because it won't accept the value as is.

**Comment by Acconut** [comment]
> I was aware of the base64 encoding requirement, just did not think, it would stop working altogether as long as there are no special characters in there.

It does not matter whether your metadata value contains any special character, it must always be encoded.

> Per TUS protocol specification I have to base64 the whole string again

Yes, this is the approach you should take.
