### ISSUE TITLE
FileInfoChanges set in PreFinishHook not available in PostFinishHook

### ISSUE THREAD

**Issue by TaridaGeorge** [tus/tusd#1160]
**Question**
In my PreFinishHook I put some metadata about the file that has been successfully received on the server. The problem is that when the PostFinishHook is called these metadatas are not there. Is this a bug or it is as intended?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: latest
- Used tusd data storage: disk store
- Used tusd configuration: --hooks-grpc 192.168.1.150:7333 --hooks-grpc-retry 5 --hooks-enabled-events "pre-create,post-create,post-receive,post-terminate,post-finish,pre-finish"
- Used tus client library: tus-java-client

**Comment by Acconut** [comment]
Using FileInfoChanges is currently only possible from the pre-create hook, not the pre-finish hook. If this value is set from pre-finish, it will be ignored. So, yes, this is working as intended for now.

**Comment by TaridaGeorge** [comment]
Thank you!
