### ISSUE TITLE
Compile from source on MacOS

### ISSUE THREAD

**Issue by pguth** [tus/tusd#118]
Following the [compile from source](https://github.com/tus/tusd/blob/master/README.md#compile-from-source) instructions on MacOS Sierra (Golang 1.8 was installed via Homebrew - no manual `GOPATH` or `GOROOT` configuration set) I ran into the following error:

```sh
$ go run cmd/tusd/main.go
cmd/tusd/main.go:4:2: cannot find package "github.com/tus/tusd/cmd/tusd/cli" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/github.com/tus/tusd/cmd/tusd/cli (from $GOROOT)
	/Users/per/go/src/github.com/tus/tusd/cmd/tusd/cli (from $GOPATH)
```

**Comment by pguth** [comment]
Fixed by running `go get github.com/tus/tusd/cmd/tusd/cli`

**Comment by Acconut** [comment]
It's not uncommon for people to get the installation wrong, mostly because Golang has a more unconventional setup structure. However, I am glad to see that you got it working but I will revisit our instructions anyhow.
