### ISSUE TITLE
Notify upload error to backend

### ISSUE THREAD

**Issue by tdewolff** [tus/tusd#1182]
While using the `tusd` library for Go, I'd like to receive a notification whenever an upload fails. For example, user starts uploading a file and closes the browser tab. The logs will show `ERR_UNEXPECTED_EOF: server expected to receive more bytes`, but how can I know that an error occurred? I was expecting it to push to the `NotifyTerminatedUploads` channel, but this probably isn't termination but an error.

**Comment by Acconut** [comment]
There is no hook to notify you when an upload is interrupted. You could use the lack of post-receive events as an indication that an upload has either been interrupted or finished. post-terminate is emitted when the upload is deleted using the [termination extension](https://tus.io/protocols/resumable-upload#termination).

In short, there is no easy way to achieve what you are asking for. Do you mind explaining more what your intention with such a hook would be?

**Comment by tdewolff** [comment]
Hi Marius, my use case is that whenever an upload is initiated, an entry in the database is created, which is updated whenever the upload succeeds. When it fails, there is no way to know except for a timeout.

Perhaps I could only add the database entry whenever the upload has succeeded.

**Comment by Acconut** [comment]
> When it fails, there is no way to know except for a timeout.

In general, there is no reliable way to determine at the moment of the upload interruption whether the upload has failed permanently and the client will not attempt to resume it or whether the upload interruption is just temporary and the client will resume the upload. So we cannot provide a hook for definite upload failures. I recommend you to design your application without needing this information. But a timeout is a good heuristic to decide whether an upload can be cleaned up or not.

**Comment by tdewolff** [comment]
Thanks for the response, you're right there's no way to know.
