### ISSUE TITLE
PreUploadCreateCallback should include upload ID

### ISSUE THREAD

**Issue by tdewolff** [tus/tusd#1184]
Before starting an upload, I'd like to verify if the upload ID (a random UUID) creates a collision with a previously uploaded file. Unfortunately, the `HookEvent.Upload.ID` field is empty and I can only verify when uploading is completed. Could this perhaps be included before calling the `PreUploadCreateCallback` method?

**Comment by Acconut** [comment]
The upload ID is not known when pre-create is emitted. The upload ID is created by the data store, hence we only know the final upload ID once the upload is created, which happens after pre-create. If you want to have control over the upload ID, pre-create can return a custom upload ID.

**Comment by tdewolff** [comment]
Excellent, thank you very much for the information. Specifying my own ID is exactly what I need.
