### ISSUE TITLE
tusd log WARN NetworkTimeoutError method=PATCH  error="feature not supported"

### ISSUE THREAD

**Issue by kj471043129** [tus/tusd#1191]
**Question**

When I use go client to upload files to Tusd service, Tusd service will print a large number of the following wanring logs. Do these warnings have any impact on the service? If we don't eliminate these warm logs, how can we.

And, if I use tusd-v1.13, there will be no problem at all.

WARN log print:
2024/09/19 17:27:23 WARN NetworkTimeoutError method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a error="feature not supported"
2024/09/19 17:27:23 WARN NetworkTimeoutError method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a error="feature not supported"
2024/09/19 17:27:23 WARN NetworkTimeoutError method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a error="feature not supported"
2024/09/19 17:27:23 INFO ChunkWriteComplete method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a bytesWritten=2012344
2024/09/19 17:27:23 INFO UploadFinished method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a size=12498104
2024/09/19 17:27:23 INFO ResponseOutgoing method=PATCH path=9d45767e50ad476f4bf2d827033dd52a requestId="" id=9d45767e50ad476f4bf2d827033dd52a status=204 body=""

**Setup details**
- GOVERSION='go1.23.1'
- Operating System: linux 3.10.0-514.el7.x86_64
- Used tusd version: tusd v2.2.2
- Used tusd data storage: disk store
- Used tusd configuration: default config
- Used tus client library: github.com/eventials/go-tus

**Comment by Acconut** [comment]
Please consult https://tus.github.io/tusd/advanced-topics/usage-package/#i-am-getting-warnings-regarding-networkcontrolerrornetworktimeouterror-and-feature-not-supported-why for information on this topic.

**Comment by kj471043129** [comment]
> Please consult https://tus.github.io/tusd/advanced-topics/usage-package/#i-am-getting-warnings-regarding-networkcontrolerrornetworktimeouterror-and-feature-not-supported-why for information on this topic.

thank u
