### ISSUE TITLE
Upgrade log/slog

### ISSUE THREAD

**Issue by pcfreak30** [tus/tusd#1201]
I had to upgrade `golang.org/x/exp/slog` to `log/slog` earlier this year, though I forgot the technical reason.

I would like to request this be done since the package seems to have graduated.

**Comment by Acconut** [comment]
This is planned for the [next major release](https://github.com/tus/tusd/milestone/1). Closing as a duplicate of https://github.com/tus/tusd/pull/1159.

**Comment by srerickson** [comment]
I noticed that `handler.Config` is still using golang.org/x/exp/slog
