### ISSUE TITLE
Where are all the chunks saved ?

### ISSUE THREAD

**Issue by MurtadhaS** [tus/tusd#121]
Hi,
I just want to ask about where are all the chunks saved before they got combined ?

**Comment by Acconut** [comment]
If you are talking about the on-disk storage, than the answer is a bit different: The chunks are not saved in individual files but are appended into one single file while the chunks are uploaded, meaning that there is only one file used for storing the upload's content.

**Comment by MurtadhaS** [comment]
thanks
