### ISSUE TITLE
About parallel uploads

### ISSUE THREAD

**Issue by MurtadhaS** [tus/tusd#125]
Hi, I want to ask about the parallel upload extension, will it be considered ?
and if not how easy is it doable ?

**Comment by Acconut** [comment]
There is no such "parallel upload extension". If you are talking about the Concatenation Extension which provides this functionality, it is already supported by tusd.

**Comment by MurtadhaS** [comment]
Thank you very much.

**Comment by MurtadhaS** [comment]
The checksum extension won't be supported in the future ?
Should I myself implement it in tusd ?

**Comment by Acconut** [comment]
We would be happy to support the Checksum extension in the future but currently do not have any plans to implement it as the value it provides is limited compared to the efforts required to build it (see https://github.com/tus/tusd/issues/81 for more details). However, we are always pleased to see contributions :)
