### ISSUE TITLE
post-create hook

### ISSUE THREAD

**Issue by flaneurtv** [tus/tusd#126]
I would desperately need an asynchronous post-create hook.

I would use this hook in order to create a DB entry for the Upload even before the upload has finished, using the UUID as the primary key. I want this record to be created in the backend for security reasons. The record then is populated with descriptive data by the user, while their video upload is still in progress. However, the user would only be able to update such a record, so the UUID can not be changed.

I would also use this record to keep track of uploads, which have been started but never finished.

The post-create hook is not a show stopper and therefore should be asynchronous. In my case, what it would be doing, is posting all data and metadata concerning the upload onto an MQTT bus, where other micro-services pick up on that information and create the DB entry.

**Comment by Acconut** [comment]
> I would use this hook in order to create a DB entry for the Upload even before the upload has finished, using the UUID as the primary key. 

Oh boy, this sounds like you are definitely going to have to deal with race conditions. What happens if the upload is finished before the entry in created? Personally, I would not go this route.

All-in-all, I haven't fully understood your situation. Tusd already offers the pre-create hook; does this not suffice you? You mentioned security reasons but I wonder what exactly concerns you.

**Comment by trickkiste** [comment]
@Acconut I would still need this feature. Can I encourage anyone of your team to write it with a bounty?

**Comment by kvz** [comment]
As far as I know the Vimeo guys where planning on adding HTTP versions of the hooks that would "fire & forget", perhaps that suffices for your purposes also?

**Comment by Acconut** [comment]
@kvz Unfortunately, the HTTP hooks to not help here since they are not "fire & forget".

@trickkiste Would you mind explaining your use case first?

**Comment by trickkiste** [comment]
1) I have a Single Page ReactJS App. The user is authenticated and then identifies with a jwt id_token.
2) The pre-create hook does verify this id_token as a conditional to create a new upload.
3) When the upload is created successfully, I use the post-create hook to publish the success message including the info json onto an MQTT bus.
4) A particular microservice will pickup this message and create a record for "metadata" (yet to be provided via ReactJS APP) in a DB for that upload.
5) The ReactJS App will update this record with description, name and tags.

UPDATE is the keyword here. I do NOT allow the App to create a new record as it is per definition untrusted. I can not reliably ensure, the ID it will provide me with for record creation is the actual uploads ID. Therefore I do not allow it to create a record to begin with but much rather do that in the backend.

**Comment by Acconut** [comment]
Thank you very much. In fact, I could not think of another way to implement this (properly without workarounds) right now.

Therefore, closing this in favour of #141.
