### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by flaneurtv** [tus/tusd#127]
I would like to encourage you to create a Dockerfile for TUSD and possibly to get involved with the Docker people in order to provide an official image.

I have created my own version already and will try to make a pull request in the near future.

**Comment by Acconut** [comment]
I am not a Docker-user for myself but I don't see any reason why we shouldn't have an image. If you could provide one, it would be appreciated greatly.

**Comment by tersmitten** [comment]
Also see #119

**Comment by kvz** [comment]
I think it will be great to have an Alpine based Dockerfile in the repo. Even if it's not perfect rightaway, it would give us something to iterate on, and already test the waters reaching out to Docker for becoming the default `_/tusd` image.

What is the best practice for versioning these images? It would be nice I guess if the tusd version is included, but we also get to push out container iterations independently of that.

**Comment by tersmitten** [comment]
I think we already setup something similar for the https://github.com/freyproject/frey repository

* `latest` is always build on changes in `master`
* for instance `release-v1.0.0` is build we you tag `v1.0.0`

https://docs.docker.com/docker-hub/builds/#create-an-automated-build

**Comment by flaneurtv** [comment]
Hi there,

I would setup an automatic build, which will build a new image on every git
commit and on every git tag created. The docker images generated from the
git tags, would have these exact tag names.

We could also have an extra set of docker images generated from a
development branch. And of course, everybody can always use the Dockerfile
to easily generate their own image from their current local sources.

I have everything setup and working already, as I am using tusd in my
docker based infrastructure and am happy to compile commit for a pull
request.

However, I am currently running from source. If you guys could provide or
point me to the best build routine, I would integrate that.

Regards,
Markus

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-05-22 16:16 GMT+02:00 Mischa ter Smitten <notifications@github.com>:

**Comment by Acconut** [comment]
> I think it will be great to have an Alpine based Dockerfile in the repo.

Agreed, Alpine seems a good way to go.

> I would setup an automatic build, which will build a new image on every git commit and on every git tag created. The docker images generated from the git tags, would have these exact tag names.

Sounds good, thank you :+1:

> However, I am currently running from source. If you guys could provide or point me to the best build routine, I would integrate that.

Not sure if you are looking for this, but that is the current routine for cross-compiling: https://github.com/tus/tusd/blob/master/.scripts/build_all.sh

**Comment by kvz** [comment]
Noob question, would we not be able to use the existing produced 64 bits Linux binary and copy that into the image, vs duplicating our build steps inside the container and having to clean up the dependencies for that afterwards (and risking not having binary compatibility with our main releases)

**Comment by tersmitten** [comment]
You can use the "64 bits Linux binary", but I remember it needing `glibc`, so you need to install that too if you want to use alpine.

**Comment by kvz** [comment]
I just remembered about this and wondered what the status here was?

**Comment by tersmitten** [comment]
Do you mean [this snippet](https://github.com/tus/tusd/issues/119#issuecomment-292010152)?

**Comment by kvz** [comment]
Nope, I thought there were plans in this ticket for creating an official container image like `_/tusd`, but it appears that was here https://github.com/tus/tusd/pull/129 - sorry for the noise!
