### ISSUE TITLE
Question of download completion hook

### ISSUE THREAD

**Issue by eokeeffe** [tus/tusd#128]
Heya
Love the library, works unbelievably well.

I'm currently using the official Go server, I'm trying to find a way for users to upload to the server multiple files. I need each set of files to go to a folder for that session. I'm trying to set it up as a job system, that will wait for all files to be submitted before processing them altogether. 

Any tips or methods you recommend to go about this?

**Comment by Acconut** [comment]
> Love the library, works unbelievably well.

Thank you :)

> I'm trying to set it up as a job system, that will wait for all files to be submitted before processing them altogether.

You could do that but I believe it's easier to process each file right after it has been uploaded: First, the client will add meta data to each file identifying in which folder it needs to go. Secondly, the server has a post-finish hook (see https://github.com/tus/tusd/blob/master/docs/hooks.md) which copies to finished uploads into the specific folder depending on the provided meta data.

What do you think?

**Comment by eokeeffe** [comment]
Hmm I could send a packet that notifies the server how many files will be uploaded first, the system does require the files altogether before starting.
I'm trying to make sure the user has to simply choose what files to upload, make it as simple as possible to use.

I think once the number of hooks has been activated, then I process the files. 

TY for the help :D

**Comment by Acconut** [comment]
There are many ways to achieve your goal. Good luck :)
