### ISSUE TITLE
S3store throwing EntityTooSmall  for the last packet.

### ISSUE THREAD

**Issue by apremalal** [tus/tusd#132]
This happens only for the last upload chunk.

Sample Error:
```
EntityTooSmall: Your proposed upload is smaller than the minimum allowed size
	status code: 400, request id: D16ED664919AC107, host id: NEuWghRsD8nr0PCGQVbJUiqhYCIbu9COt/251o+6y/Pzbqu+sGKmrcfsSacHw/nHbFw9LBETKDs=

```

**Comment by Acconut** [comment]
Are you using AWS S3 or a different S3-compatible storage service?

**Comment by Acconut** [comment]
@apremalal Any updates on this issue?

**Comment by apremalal** [comment]
@Acconut I was using AWS S3. I couldn't narrow down the issue and ended up writing my own api set with the tus protocol. Hence closing the issue.

**Comment by Acconut** [comment]
There was a patch a few months ago (https://github.com/tus/tusd/commit/d48e4ac5775e323e77f778e8f72f69126da881cd) which fixed a similar issue, if I recall correctly. Could it be that you were not running the latest version of tusd at that time?
