### ISSUE TITLE
How to configure the Expiration of an upload?

### ISSUE THREAD

**Issue by apremalal** [tus/tusd#133]
Does s3store support expiration of an upload?. Appreciate if someone can point to a documentation or relevant methods.

**Comment by Acconut** [comment]
> Does s3store support expiration of an upload?

No, it doesn't. In fact, tusd does not currently implement the Expiration extension. However, I would be delighted to help you add this feature :)

**Comment by apremalal** [comment]
I searched a bit and found out that s3 support expiration. http://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lc-expire-mpu

**Comment by kvz** [comment]
> I searched a bit and found out that s3 support expiration. http://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lc-expire-mpu

This is also in line with our approach here: https://github.com/transloadit/uppy/issues/122#issuecomment-243703608 - letting a layer close to the actual storage handle it has its drawbacks, but also the clear advantage of not having to do bookkeeping at a higher layer which has an increased chance of being out of sync and/or more resource hungry.

**Comment by kaharman** [comment]
Hello, if there any plan to implement expiration extension? Can I add expiration date into FileInfo struct?

**Comment by Acconut** [comment]
We currently have no plan to implement the Expiration extension on our own but we are always happy to assist you if you would like to contribute this feature.

**Comment by Acconut** [comment]
I opened https://github.com/tus/tusd/issues/435 to start the discussion for a possible implementation of the Expiration extension.
