### ISSUE TITLE
How to listen to complete upload event in Go code?

### ISSUE THREAD

**Issue by apremalal** [tus/tusd#134]
I'm trying tusd manually with go code. Is it possible to listen to a upload completed channel?. (without using hooks externally.)
I'm trying to create an external DB record after a successful upload. Additionally wants to send a custom pay load with the last PATCH request 

{
"id: "filde-id",
"url" : "s3-url"
"type": "mp4",
"size" :325542545
}

**Comment by Acconut** [comment]
You can look at how the tusd binary implements this. The relevant lines are here: https://github.com/tus/tusd/blob/master/cmd/tusd/cli/hooks.go#L47-L56. In addition, I would recommend reading the documentation for these channels (https://godoc.org/github.com/tus/tusd#UnroutedHandler).

**Comment by Acconut** [comment]
Closing this issue since I assume it's solved. Feel free to leave a comment if you want to continue the discussion :)
