### ISSUE TITLE
Wrong URL when new upload is created

### ISSUE THREAD

**Issue by alexandrevicenzi** [tus/tusd#136]
The [absFileURL](https://github.com/tus/tusd/blob/master/unrouted_handler.go#L652) method returns a wrong URL if my server list in a random port. It only works if my server is running on ports 80 for HTTP and 443 for HTTPS.

![screenshot from 2017-06-28 14-46-00](https://user-images.githubusercontent.com/2637672/27652137-07e29afc-5c11-11e7-950f-0640eca4277d.png)

**Comment by Acconut** [comment]
Are you using a proxy in front of tusd? If so, did you set the `-behind-proxy` flag? Also what exactly do you mean with "random port"? Are you referring to listen on port 0?

**Comment by alexandrevicenzi** [comment]
I'm using tusd as a lib, and I'm running on port 7781 behind nginx on the same port (dev only). `RespectForwardedHeaders` is set to false.

What I fould is that `absFileURL` doens't get the port in any case.

**Comment by Acconut** [comment]
`RespectForwardedHeaders` should be enabled to ensure that the correct URL is generated. Did you try to enable it yet? Also, did you solve the problem or did you close the issue by accident?

**Comment by alexandrevicenzi** [comment]
The problem was on nginx, I just enabled proxy_redirect to change the Location url.

**Comment by Acconut** [comment]
Glad to hear that.

**Comment by kvz** [comment]
Would it make sense to add this contribution to https://github.com/tus/tusd/blob/master/.infra/files/nginx.conf ?

**Comment by jheaff1** [comment]
This still seems to be an issue, with `-behind-proxy` the Location returned by the Creation request strips the port, assuming that it is on 80/443. Is there any way around this?

**Comment by jheaff1** [comment]
Sorry if I was unclear, I mean if the proxy is NOT running on 80/443, eg running on 8443. The returned Location header does not include “:8443” in this case if the “-behind-proxy” flag is set

**Comment by Acconut** [comment]
Ok, now I understand. Did you follow the instructions at https://github.com/tus/tusd/blob/main/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy for configuring your proxy?

**Comment by jheaff1** [comment]
Yep I followed those instructions. I also used the following config as a template:

https://github.com/tus/tusd/blob/main/examples/nginx.conf

**Comment by Acconut** [comment]
> Yep I followed those instructions

That's odd because that should work. tusd then just takes the hostname from the X-Forwarded-Host header. See https://github.com/tus/tusd/blob/0e1169bdf182253d73c58bd118d6679cfb64b496/pkg/handler/unrouted_handler.go#L1030

> Weirdly it works fine if it don't specify the `-behind-proxy` flag

That also seems weird. In that case, tusd includes its own port in the Location header and ignore the X-Forwarded-* headers. Could it be that you have some other component that is rewriting the Location header?
