### ISSUE TITLE
Make .info files on master.tus.io accessible too

### ISSUE THREAD

**Issue by trickkiste** [tus/tusd#139]
https://tus.io/demo.html and https://master.tus.io/files are great resources for testing TUS.

It would be great, if the .info files corresponding to an upload would be accessible too. 

Helps client devs to verify if they have done things right e.g.

**Comment by Acconut** [comment]
Good idea! However, there is already a way to retrieve the information contained in .info files: The specification defines the `HEAD` request for this (https://tus.io/protocols/resumable-upload.html#head) which contains the Upload-Offset, Upload-Length, Upload-Metadata, etc headers for this. Of course, this is supported by the https://master.tus.io/files instance.

**Comment by trickkiste** [comment]
Hi Marius,

I understand. This is of course the standard procedure, when one needs to
retrieve this info.

However, having these files available on a demo platform still comes in
very handy. See, I had setup tusd with an s3store in my production system,
when I realised, that the .info file did not contain the ID value. I wanted
to quickly check, if this in the case only with my personal installation or
if this concerns all installations. Would I have had available the .info
files on master.tus.io, that would have been trivial. And in this case,
whatever the HEAD request does respond is of little value, when I want to
know, what actually is in written to the .info file.

Turns out - reading the code - GetReader will present me with an ID, even
though there is non in the .info file (when using s3store).

That's why I want to suggest, to make that .info file available on the demo
system as well. Helps people to debug and learn about tusd. For a demo
system, I guess it is always a good idea to have as much information
available as possible. It's not for me, it's for the next guy wanting to
learn about tusd.

My best Regards,
Markus

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 21:48 GMT+02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment]
> Turns out - reading the code - GetReader will present me with an ID, even though there is non in the .info file (when using s3store).

The endpoint you are talking about would not have helped in this situation. Bascially, tusd cannot "make .info files accessible" because it does not know about any .info file. The .info file is just a common pattern used in the FileStore and S3Store. Those are two different pairs of shoes, since data storage is separated form request handling in tusd. The only details tusd has about an upload are the ones which are available using GetInfo. And since this function "patched" the ID info the FileInfo structure, the bug would not have been seen.

**Comment by trickkiste** [comment]
Well, not tusd shall make the file available, but the reverse proxy before
it maybe. Which store are you using on master.tus.io? Are you saying the
file does not even exist, as you are not using filestore and therefore the
info is stored some place else (e.g. in memory)?

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 23:16 GMT+02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment]
> Which store are you using on master.tus.io?

We are using the (default) file storage for it.

> Well, not tusd shall make the file available, but the reverse proxy before it maybe.

I do not feel comfortable with this. Generally, we like to keep master.tus.io as close as possible to how you would run it in production this make it easier to find issues in tusd before we release them. And such a change would go in the other direction, I feel.

**Comment by trickkiste** [comment]
True, but only if you try to do that in tusd.
I suppose you have a reverse proxy in front of it. How about making the
files available through that? Your tusd would stay untouched.

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 23:34 GMT+02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment]
We are running nginx in front of it (for SSL termination etc) but the same applies to it. We like to keep our nginx configuration production-like :)

**Comment by trickkiste** [comment]
Alright.

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 23:39 GMT+02:00 Marius <notifications@github.com>:
