### ISSUE TITLE
Docker Automated Build not working

### ISSUE THREAD

**Issue by trickkiste** [tus/tusd#144]
For some reason, Docker does not trigger an automated build, when a new commit is pushed to tus/tusd. This is the case for both tusproject/tusd and my shadow build tusio/tusd. From what I am seeing in the settings on Docker Hub, everything should work just fine. These settings also resemble exactly, what I have on flaneurtv/tusd and everything is working fine there.

Can someone check the settings in `https://github.com/tus/tusd/settings/installations`, see if there is a Docker entry and it is activated? I could also take care of troubleshooting myself, but currently I only have read repository access, so I can not view or change the settings on github.

My best regards,
Markus

**Comment by kvz** [comment]
It wasn't there at all, sorry. I just added it tho:

<img width="1150" alt="screen shot 2017-07-20 at 13 01 59" src="https://user-images.githubusercontent.com/26752/28414381-aa7d5068-6d4b-11e7-90c6-102db810bec9.png">

**Comment by trickkiste** [comment]
Great, thanks!

We see if it works, with the next commit or the next tag added. BTW, I would recommend issuing a new minor version, as we have no tagged version yet, which already includes the Dockerfile. I also proposed this to Acconut today.

**Comment by Acconut** [comment]
The new release is on my list but I want to update the README first to reflect some changes.

**Comment by kvz** [comment]
Cool, just added an empty commit via `git commit --allow-empty -m 'Add empty commit for the purpose of testing Docker Automated Build' && git push` I'll leave release decisions to Acconut

**Comment by trickkiste** [comment]
@Acconut, great!
@kvz, worked. It is successfully and automatically built the new "latest" version.

For the Docker official-builds this will work a little differently, commits are referenced by fingerprint directly and then "named/aliased" with multiple Docker tags. Still working on it.
