### ISSUE TITLE
s3store MaxPartSize limits possible upload size way below S3 specs of 5 TB max

### ISSUE THREAD

**Issue by trickkiste** [tus/tusd#149]
AWS S3 specifies a maximum object size of 5TB. This object size can not be handled by tusd, as MaxPartSize is not calculated according to the file size of the upload, but has a hard limit way below the limit AWS specifies in their documentation.

Tusd's s3store sets this:
> MaxPartSize: 6 * 1024 * 1024,
> MinPartSize: 5 * 1024 * 1024,

AWS Specs states:
http://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html
> Maximum object size | 5 TB
> Maximum number of parts per upload | 10,000
> Part size | 5 MB to 5 GB, last part can be < 5 MB

The maximum file size with 10,000 possible parts would be 60 GB with the current settings and the restriction to 10.000 parts max. As a side note it should be mentioned, that at the time of writing, anything greater than 1000 parts will currently not work due to bug #147, effectively restricting max upload size to 6 GB.

From my understanding, `MaxPartSize` needs to be `5 * 1024 * 1024 * 1024` and the `EffectivePartSize` needs to be calculated from the actual upload size taking into account the restraints set by the S3 specs.

`EffectivePartSize` should then be calculated as follows:
```
if (uploadSize <= MinPartSize)
  upload in one piece
elseif (uploadSize/10.000 <= MinPartSize)
  upload with EffectivePartSize = MinPartSize
elseif (uploadSize <= 5TB)
  EffectivePartSize = uploadSize/10.000
else
refuse to comply
```

As a prerequisite bug #147 needs to be fixed of course.

**Comment by trickkiste** [comment]
The solution I am proposing would still assure that the EffectivePartSize will be set as small as possible, while at the same time enable uploads to the upper end of the S3 specs size limit.

Therefore the user would get the best of both:
* Minimal re-upload size if an upload needs to resume
* And max upload size of 5 TB total

**Comment by Acconut** [comment]
This is indeed a limiting factor. Another possible solution (which is used by the data store for Google Cloud Storage) is to merge the upload recursively. This would work like following:

1. Upload parts 1 to 10,000 to S3
2. Merge the chunks 1 to 10,000 into a temporary object
3. Create a new multipart upload on S3
4. Copy the temporary object in a new part using UploadPartCopy (http://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.UploadPartCopy)
5. Upload parts 10,001 to 19,999 to S3.
6. Repeat steps 2 - 5 until the upload is finished.

The downside is, however, that this solution is more complex and also more error-prone to bugs. What do you think?

**Comment by Acconut** [comment]
> The solution I am proposing would still assure that the EffectivePartSize will be set as small as possible, while at the same time enable uploads to the upper end of the S3 specs size limit.

I like this idea very much :+1:

**Comment by trickkiste** [comment]
It sounds complex.

My first thought was, how would you store that state of this complex upload process. Currently, as I understand it, state is deterministic and can always be derived from the upload-URL.

When we calculate an `EffectivePartSize` from the file size we want to upload, things would still be deterministic and therefore it will always be possible to resume an upload.

**Comment by Acconut** [comment]
You are right, let's not choose the recursive merge, it's too complex and actually not necessary.

**Comment by Acconut** [comment]
Closing in favour of #150.
