### ISSUE TITLE
Any plan to switch from AWS SDK to Minio?

### ISSUE THREAD

**Issue by sachinwalia2k8** [tus/tusd#151]
I am wondering if there is any plan to move away from AWS Go SDK to Minio SDK for file upload to S3 or S3 compatible stores. I've always found minio Go SDK to be much cleaner and better documented.

https://github.com/minio/minio-go

**Comment by Acconut** [comment]
I agree that the AWS Go SDK does not expose a great API but it serves our purposes well and therefore we do not have any plans to migrate to the Minio SDK. Or does Minio offer more benefits than its good API and documentation?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
