### ISSUE TITLE
Multi User Download Error

### ISSUE THREAD

**Issue by aixj1984** [tus/tusd#153]
I plan to use tus as file serivce. There is one error where multi users download one file at the same time. I want to know how to process this problem.

**Comment by Acconut** [comment]
Sorry to hear that you are having issues but we cannot help you unless you provide us with more information. What exactly did you do? What error did you see? Can it be reproduced? What tusd data store are you using (s3, gcs, file)?

**Comment by aixj1984** [comment]
Thank you! Next time I give more information to you.

**Comment by aixj1984** [comment]
The message is "file current lock", 
![b66a74b719dfe33b0b34d11b20946157](https://user-images.githubusercontent.com/2499352/31752310-bc42c8c4-b4bc-11e7-8255-fc34e8de6cc4.png)

**Comment by Acconut** [comment]
Thank you for clarifying your issue. The reason that you are seeing this behaviour is that tusd only allows one concurrent access to an upload, both for reading and writing. This is a safety check meant to prevent data corruptions when multiple clients upload to the same upload resource at the same time. This rule also disallows downloading an upload while it is being uploaded and (what you are seeing) prevents multiple users from downloading simultaneously. That being said, you see, tusd is not meant to be used as a server for downloading or serving uploaded content. Instead its job is to just receive uploads.

Therefore, I am not entirely sure whether it makes sense to loosen these safety rules for your situation. Are you able to work around your issue by having a dedicated server for downloading the content for your used data storage?
