### ISSUE TITLE
s3store not quite compatible with Minio Gateway for Azure

### ISSUE THREAD

**Issue by pauln** [tus/tusd#156]
Per the "Known Limitations" section in the [Minio Gateway for Azure documentation](https://docs.minio.io/docs/minio-gateway-for-azure):
> List Multipart Uploads and List Object parts always returns empty list. i.e Client will need to remember all the parts that it has uploaded and use it for Complete Multipart Upload

This should be surmountable by having `s3store` track the parts itself rather than relying on the ListParts call.  If so, it could be a quick and (relatively) easy way to add support for Azure.

For the record, the symptom of this issue is that `tusd` appears to be processing the upload, with every chunk apparently being uploaded successfully - but the file itself never appears in Azure.  The `tusd` logs then show a response with status code `400`:
```
10/11/2017 14:29:43[tusd] event="ResponseOutgoing" status="400" method="PATCH" path="7fdf39333a73637d84d5aceef233d899+22d7ca0606e907ec" error="MalformedXML: The XML you provided was not well-formed or did not validate against our published schema.
10/11/2017 14:29:43	status code: 400, request id: 14F5954762ED0FC1, host id: "
```

**Comment by Acconut** [comment]
Thank you for bringing this up!

> Per the "Known Limitations" section in the Minio Gateway for Azure documentation

Unfortunately, this limitation makes the Minio Gateway not fully S3-compatible.

> This should be surmountable by having s3store track the parts itself rather than relying on the ListParts call.

I doubt that this would be an easy change. We cannot store this data in memory or on the local disk since this does not work with horizontal scaling using multiple tusd instances. Using an object on S3 for this information would be possible but it will likely decrease performance since reading an object may be slower than listing the parts. Furthermore, this would also duplicate the part list (actual part list vs the list we manually keep) making it hard job to ensure that this data is kept consistent. We always treat the storage as the single source of truth but the change you proposed would break this principle. I am sorry, but I don't think this is a good idea.

Frankly, instead of working around this limitation in tusd, it should be changed in Minio directly. Did you ask them what's the reason for this inconsistency?

**Comment by pauln** [comment]
> I doubt that this would be an easy change.
Fair enough - I dug into the code after posting this issue, and rapidly realised that it's not as simple a change as it seemed at first glance.

> Frankly, instead of working around this limitation in tusd, it should be changed in Minio directly. Did you ask them what's the reason for this inconsistency?

The limitation was listed under the heading "Gateway inherits the following Azure limitations", so it would seem that the limitation is at the Azure end.  As such, I'm guessing that Minio would have the same issues trying to work around it as tusd - but I'll raise an issue to see if they have any thoughts on potential workarounds which would allow Minio Gateway to implement the missing API calls.

**Comment by Acconut** [comment]
> I'll raise an issue to see if they have any thoughts on potential workarounds which would allow Minio Gateway to implement the missing API calls.

Thank you for creating the issue in their repository. Let's see how they decide on that topic

**Comment by pauln** [comment]
From discussion on the Minio issue, it seems that a full implementation may not be possible due to limitations in the Azure API, but even if that's the case, they'll hopefully be able to implement something which will suffice for `tusd`.

The Minio folks have also raised the point that [S3's ListParts apparently shouldn't be relied upon to build a CompleteMultipartUpload request](https://github.com/aws/aws-sdk-go/issues/1518).  I'm not sure how you'd like to tackle that (if at all), given the difficulties discussed earlier in this thread...

**Comment by Acconut** [comment]
From reading through https://github.com/minio/minio/issues/5169, it seems that the Minio team will add support for the ListParts call, which is amazing news. Thank you a lot for helping them :)

> The Minio folks have also raised the point that S3's ListParts apparently shouldn't be relied upon to build a CompleteMultipartUpload request. I'm not sure how you'd like to tackle that (if at all), given the difficulties discussed earlier in this thread...

I have never heard about this before and also never experienced any issues in that matter. However, I will look into the discussion, thanks for bringing this up.

**Comment by pauln** [comment]
There's now [a new Minio release](https://github.com/minio/minio/releases/tag/RELEASE.2017-11-22T19-55-46Z) which includes support for ListParts - but unfortunately still doesn't quite work with `tusd`, as it's missing a change which I submitted that triggers it to create an empty BlockBlob when initialising the multipart upload so that calling ListParts (amongst other operations) doesn't fail (404) before the first chunk is uploaded.  I've submitted a fresh [PR to Minio](https://github.com/minio/minio/pull/5226) with the change which disappeared from the ListParts PR; hopefully it will land soon, and we'll be able to close this issue.

**Comment by Acconut** [comment]
That's amazing to hear. :tada:

**Comment by pauln** [comment]
There have been two Minio releases over the holiday period, which both include a fix for the ListParts 404 issue.  I've just upgraded my development environment, and can confirm that it now seems to play nicely with `tusd`.

**Comment by kvz** [comment]
💯 🥇
