### ISSUE TITLE
Metadata validation

### ISSUE THREAD

**Issue by sysradium** [tus/tusd#160]
Is there a way to validate metadata before creating the upload?
Of course I can create a middleware which does that, however I should deal with the request payload myself. Moreover the `parseMetadata` function is not exported, so I can not parse metadata myself.

There is a `UplodCreated` channel, by it is async. What I do now is  once I receive a message on `UplodCreated` channel I analyse metadata and terminate the upload. But I want to able to return an error immediately, on the first request which creates an upload. Not once I get a message on `UplodCreated` and client could have already uploaded some data.

**Comment by Acconut** [comment]
Yes, this is absolutely possible without using custom middleware. Instead, tusd has an advanced hook system which allows custom routines to be executed when certain events occur. Please see the corresponding FAQ entry and the linked documentation for more details: https://github.com/tus/tusd#can-i-run-custom-verificationauthentication-checks-before-an-upload-begins

**Comment by sysradium** [comment]
@Acconut 

Yes, thanks. I figured it out. FAQ says you can use hooks, but I was embedding it into my app.
Only a few days laters I realised that I can take a look at how hooks actually work and mimic the same behaviour using my data store. And indeed, I found this:
https://github.com/tus/tusd/blob/master/cmd/tusd/cli/hooks.go#L33

For some reason the thought that you can override `NewUpload` did not cross my mind :)

**Comment by Acconut** [comment]
Great to hear that you figured out a solution :)
