### ISSUE TITLE
When I upload file, server return status code: 405

### ISSUE THREAD

**Issue by fanghuafan** [tus/tusd#164]
Why I always upload a file to make a mistake:
server: tusd] event="RequestIncoming" method="GET" path="" 
client: unexpected status code: 405
And i try upload file with https://github.com/eventials/go-tus,
the same as I use POSTMAN submission the upload request,

**Comment by Acconut** [comment]
I have never experienced this error before, but would like to debug it. Please provide your exact tusd configuration and also the relevant code sections where you are using go-tus, so I can attempt to reproduce it.

**Comment by fanghuafan** [comment]
Firstly,Thank you for your help!

my go-tus code:
`package main

import (
	"os"
	"github.com/eventials/go-tus"
	"log"
)

func main() {
	f, err := os.Open("G:/test/kupamovie.sql")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	// create the tus client.
	client, err1 := tus.NewClient("http://localhost:8080/files", nil)

	// create an upload from a file.
	upload, err2 := tus.NewUploadFromFile(f)

	// create the uploader.
	uploader, err := client.CreateUpload(upload)
	// start the uploading process.
	if err == nil {
		uploader.Upload()
	} else {
		log.Println("upload error:",err)
	}
}`

tusd version : 0.9.0
tusd code:
`package main

import (
	"fmt"
	"net/http"

	"github.com/tus/tusd"
	"github.com/tus/tusd/filestore"
	"log"
)

func main() {
	store := filestore.FileStore{
		Path: "G:/test/",
	}

	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:      "/files/",
		StoreComposer: composer,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}

	http.Handle("/files/", http.StripPrefix("/files/", handler))

	http.Handle("/test", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println("request method：", r.Method) // get
	}))

	http.HandleFunc("/test_1",func(w http.ResponseWriter, r *http.Request) {
		log.Println("request method：", r.Method) // post
	})

	err = http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}`

I think  it's possible  to initiate this problem for http.Handle,the same post request,but request method print result inequality,Why does this happen?

**Comment by fanghuafan** [comment]
Firstly,Thank you for your help!

my go-tus code:
package main

import (
	"os"
	"github.com/eventials/go-tus"
	"log"
)

func main() {
	f, err := os.Open("G:/test/kupamovie.sql")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	// create the tus client.
	client, err1 := tus.NewClient("http://localhost:8080/files", nil)

	// create an upload from a file.
	upload, err2 := tus.NewUploadFromFile(f)

	// create the uploader.
	uploader, err := client.CreateUpload(upload)
	// start the uploading process.
	if err == nil {
		uploader.Upload()
	} else {
		log.Println("upload error:",err)
	}
}

tusd version : 0.9.0
tusd code:
package main

import (
	"fmt"
	"net/http"

	"github.com/tus/tusd"
	"github.com/tus/tusd/filestore"
	"log"
)

func main() {
	store := filestore.FileStore{
		Path: "G:/test/",
	}

	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:      "/files/",
		StoreComposer: composer,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}

	http.Handle("/files/", http.StripPrefix("/files/", handler))

	http.Handle("/test", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Println("request method：", r.Method) // get
	}))

	http.HandleFunc("/test_1",func(w http.ResponseWriter, r *http.Request) {
		log.Println("request method：", r.Method) // post
	})

	err = http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}

I think  it's possible  to initiate this problem for http.Handle,the same post request,but request method print result inequality,Why does this happen?

**Comment by Acconut** [comment]
Thanks for posting your code, this helped a lot. This is not a problem in tusd, instead you did not set the correct URL when creating the tus client. It must be `tus.NewClient("http://localhost:8080/files/", nil)` (notice the trailing slash on the URL). The reason is that tusd redirects from http://localhost:8080/files to http://localhost:8080/files/ and does not accept any POST requests at http://localhost:8080/files, which causes the tus client to fail. Please update your code and it should work.

**Comment by fanghuafan** [comment]
Thank you very much!
