### ISSUE TITLE
Demo server isn't working

### ISSUE THREAD

**Issue by dongmai** [tus/tusd#165]
Hi,
I can't upload files on the demo site: https://tus.io/demo.html

<img width="530" alt="screen shot 2018-01-04 at 3 34 51 pm" src="https://user-images.githubusercontent.com/3855966/34555547-df7c915a-f164-11e7-8364-495ca38ac1c5.png">

Does this cause by I've uploaded too many files?

**Comment by wilkoklak** [comment]
I think that it's some bigger problem. I can't upload it on the demo page, and from uppy.io too. Uppy.io uses tus.io

**Comment by kvz** [comment]
We moved master.tus.io to kubernetes and are still having a few issues. I’ve asked @kiloreux to investigate. Sorry about the trouble people, we’ll get the demo server on its feet soon and will then also be able to share recipies for running tusd on kubernetes

**Comment by Acconut** [comment]
We were able to resolve the issues regarding the failing tus and uppy demos. Would you be so kind and try it again?

**Comment by dongmai** [comment]
It's working now, thanks!

**Comment by wiemann** [comment]
@kvz any news regarding running tusd on kubernetes? A working nginx ingress config would be great.

**Comment by kiloreux** [comment]
@wiemann We already running this repo on kubernetes You can check the config we are using here https://github.com/tus/tusd/blob/master/.infra/kube/tusd-kube.yaml . Please let us know if you have any further questions.
