### ISSUE TITLE
Restore the nginx and apache configs

### ISSUE THREAD

**Issue by mvrhov** [tus/tusd#166]
I know that you are running this in production, but not everybody falls for every hype which at this time is kubernetis.

**Comment by kvz** [comment]
We will first clean up some more, and then make example scripts available for all major integration possibilities again. But probably as part of documentation and right here as the actual implementation.

**Comment by Acconut** [comment]
I added the sample configurations back into the documentation folder before we forget about them: https://github.com/tus/tusd/tree/master/docs Thanks for reporting.

**Comment by mvrhov** [comment]
Thanks
