### ISSUE TITLE
parse file metadata

### ISSUE THREAD

**Issue by floodico** [tus/tusd#167]
How can i get metadata in post-finish hook? I need this to move file with original name to another store after uploading.
I watched this code - 
   `original_name="$(cat /dev/stdin | jq .MetaData.name)" `
    `mv ../public/uploads/daemon_store/${id}.bin ../public/uploads/cache/${original_name}`

But when i output original_name in terminal, that's empty

**Comment by kvz** [comment]
Hi, are you also setting the `name` metadata? This is not mandatory and you'd have to tag this yourself

**Comment by Acconut** [comment]
As @kvz said, you may not have set the `name` metadata. If you are using the tus-js-client, this attribute should be set by default, but this may not be the case for other clients. Would you mind mentioning what client you are using?

**Comment by floodico** [comment]
@kvz @Acconut I understood, thank you
