### ISSUE TITLE
How to get the absolute url of s3 when using s3 ad dataStore?

### ISSUE THREAD

**Issue by samyakjain** [tus/tusd#173]
Currently i am getting url as 

http://localhost:1333/files/da222199e55445353d1bd5341332cab0+VM8tESxKGHTy0wJJt_44OX1pzUHlQIdmB4jUS7PqA10B9ZuxRN6QaUsj.pyAT4BWfETjTFM.8ZFfxYcCCzAm7.h2m0HXkMpPq53Vf_xV8Yxnbpbu7z2x4d_4TCfaig.E

but i want is absolute url to s3. Something like 
https://s3-ap-southeast-1.amazonaws.com/<bucket_name>/some-id

**Comment by Acconut** [comment]
Currently, you would have to generate the absolute URL on your own. The tusd upload ID (the last segment in the upload URL) consists of the file ID and multipart ID separated by a `+`. The multipart ID is of no use after the upload is finished but you can use the file ID to generate the S3 URL.

In your case, the URL would be 
https://s3-ap-southeast-1.amazonaws.com/bucket_name/da222199e55445353d1bd5341332cab0

**Comment by samyakjain** [comment]
I eventually figured that out. 

Thanks for the reply.

**Comment by zvictor** [comment]
is there any place in the response object where we can get only the file ID? I can only find `uploadURL` and, I have to say, it feels quite hacky to have to break it down in order to extract the ID.

should we change it to include the id and maybe more?

```js
{
  ...
  tus: {
    uploadURL: '...',
    id: '...',
    bucket: '...',
    storage: '...'
  }
}
```

**Comment by Acconut** [comment]
@zvictor Unfortunately, is no such functionality yet. We do have plans to expose for storage details (such as the upload ID, bucket, etc) to hooks but it's not implemented. That being said, I am happy to assist you if you want to give this feature a try!

**Comment by kyleparisi** [comment]
For lazy reference:

```js
uploadURL.split("/").slice(-1)[0].split("+")[0]
```
