### ISSUE TITLE
Error "MissingRegion: could not find region configuration" despite AWS_REGION variable is set

### ISSUE THREAD

**Issue by vgiotsas** [tus/tusd#175]
I have a Bucket in the region EU (London) in which I'm trying to upload files.
I have set the required variables as follows:

```
export AWS_ACCESS_KEY_ID="MY_KEY_ID"
export AWS_SECRET_ACCESS_KEY="MY_SECRET_KEY"
export AWS_REGION="eu-west-2"
```

I start the server using `sudo tusd -s3-bucket my.bucket.name`
However, when I try to upload I get the following message:

```
[tusd] event="ResponseOutgoing" status="500" method="POST" path="" error="s3store: unable to create multipart upload:
MissingRegion: could not find region configuration"
```

My OS is Ubuntu 16.04 and I run it on an EC2 server

**Comment by Acconut** [comment]
That is unexpected, we have been using tusd with S3 in production for a long time and never came across this situation. But let's see...

What tusd version are you using? Did you download the prebuilt binaries or did you compile it from yourself? I am asking because this might cause a difference in the used AWS SDK.

**Comment by Acconut** [comment]
This might sound silly but are you really sure that you have set the AWS_REGION environment variable correctly?

**Comment by vgiotsas** [comment]
I just realized I was using the wrong bucket name format, I was using the virtual-hosted–style URL while I should have been using just the bucket name. Now it works fine, sorry for the false flag 😳

**Comment by Acconut** [comment]
I am glad to hear that you figured it out and it's not a bug in tusd :+1: However, I am still a bit surprised that entering a wrong bucket name would yield this error. So I may try to investigate better error message here.
