### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by mike-web** [tus/tusd#178]
Hello,
Yesterday it worked fine and today getting this error:
**Headers:**
Request URL: https://master.tus.io/files/
Request Method: POST
Status Code: 500 
Remote Address: 35.202.180.73:443
Referrer Policy: no-referrer-when-downgrade

**Response:**
close /srv/tusd-data/d83a271cb8b5b652ca8cca845878783d.info: no space left on device

This error also appears here: [https://uppy.io/examples/dashboard/](https://uppy.io/examples/dashboard/)

**Comment by Acconut** [comment]
We had issues with our clean up job which ensures that enough disk space is available for all uploads. This caused the error that you were reported but it should be working again now. Thanks for reporting
