### ISSUE TITLE
Unsupported Version: Running the "manual" example code

### ISSUE THREAD

**Issue by postables** [tus/tusd#194]
I'm running the example code from the README.md file , and get an "unsupported version" error message when trying to make POST requests. I have the version specified: `Tus-Version: 1.0.0`

**Comment by Acconut** [comment]
> I have the version specified: Tus-Version: 1.0.0

The header for specifying the client's version is called `Tus-Resumable`. The header Tus-Version also exists but is used by the server to indicate which versions it is supporting. So by setting the `Tus-Resumable: 1.0.0` header you should be fine.

**Comment by postables** [comment]
Thanks! I have tried that, and any files I pass through my post requests don't appear to be processed?

**Comment by Acconut** [comment]
> any files I pass through my post requests don't appear to be processed?

Yes, that is how the protocol works. The POST request creates an upload without transfering the file content. This last step is done using a PATCH request as described in the specification: https://tus.io/protocols/resumable-upload.html#patch

**Comment by postables** [comment]
Hmm okay, I'll try this and see how that goes.

**Comment by Acconut** [comment]
Ok, let me know if you experience other problems. BTW, we also offer a variety of client libraries which handle all the underlying HTTP requests, so you don't have to take care of that.

**Comment by postables** [comment]
Do you have golang binaries that do that? I wasn't able to find any that handle all that stuff.

**Comment by Acconut** [comment]
Yes, https://github.com/eventials/go-tus is a functional tus client written in Go.

**Comment by Acconut** [comment]
You can find it and others at https://tus.io/implementations.html

**Comment by postables** [comment]
:joy:  I can't believe I missed `go-tus` haha thought I was stuck to using tusd.
Thank you.

**Comment by Acconut** [comment]
No worries, you're welcome :)
