### ISSUE TITLE
tusd with minio, multipart file upload does not work.

### ISSUE THREAD

**Issue by DennisRutjes** [tus/tusd#197]
testing tusd on windows.
When I run minio with cmd and create with browser the uploads bucket:

`docker run -p 9000:9000 --name azure-s3 -e "MINIO_ACCESS_KEY=storage" -e "MINIO_SECRET_KEY=storagestorage" minio/minio:latest server /data
`
and I start tusd : 

```
set AWS_ACCESS_KEY_ID=storage
set AWS_SECRET_ACCESS_KEY=storagestorage
set AWS_REGION=us-east-1
tusd -s3-endpoint  http://localhost:9000 -s3-bucket uploads -max-size 2000000000
```

I cannot upload a 1.5 Gb file with the enclosed html page in demo.zip file.

[demo.zip](https://github.com/tus/tusd/files/2189023/demo.zip)

just click on index.html to run it from filesystem in the browser

Am I missing something ?

in console i get for tusd, it seems that offset is not getting increased?:

`[tusd] event="ChunkWriteStart" id="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8" maxSize="5000000" offset="0"
[tusd] event="ChunkWriteComplete" id="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8" bytesWritten="0"
[tusd] event="ResponseOutgoing" status="204" method="PATCH" path="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8"
[tusd] event="RequestIncoming" method="OPTIONS" path="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8"
[tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8"
[tusd] event="RequestIncoming" method="PATCH" path="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8"
[tusd] event="ChunkWriteStart" id="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8" maxSize="5000000" offset="0"
[tusd] event="ChunkWriteComplete" id="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8" bytesWritten="0"
[tusd] event="ResponseOutgoing" status="204" method="PATCH" path="46beda844186e22e9e6268ee1df692b0+d1e04144-e657-4acc-8dda-05e279931aa8"`

**Comment by Acconut** [comment]
There has been a few issues with Minio in the past as described in https://github.com/tus/tusd/issues/156 which were caused by the fact that Minio was not fully compatible with AWS S3. This problem has been fixed this release: https://github.com/minio/minio/releases/tag/RELEASE.2017-12-28T01-21-00Z

So, it's likely that this is again caused by Minio. What version of Minio are you using?

**Comment by DennisRutjes** [comment]
minio/minio:latest perhaps the issue snuck back into minio?

**Comment by DennisRutjes** [comment]
btw upload via minio browser of the 1.5 gb file succeeded locally

**Comment by DennisRutjes** [comment]
even with minio minio/minio:RELEASE.2017-12-28T01-21-00Z (old one) tusd cannot cope with multipart upload

**Comment by DennisRutjes** [comment]
ok It turns out I should not enter chunk size in the form, switched region to eu-west-1 and things worked out!

**Comment by DennisRutjes** [comment]
Ok removing chunks resulted in single upload, multipart still problem

**Comment by acj** [comment]
@DennisRutjes I think that your chunk size is too small for the S3 backend. The backend doesn't currently handle chunks that are smaller than 5 MiB (5 * 1024 * 1024 bytes) except for the final chunk. If you use a <5 MiB chunk size, the upload will fail in the way that you mentioned. Choosing a larger chunk size may fix it.

I've been testing a solution for this and should have something to share soon.

**Comment by Acconut** [comment]
As @DennisRutjes you should not set small chunk sizes. In fact, defining a chunk size for tusd is not only not necessary but will also decrease performance. Do you have a specific reason for setting this value?

> Ok removing chunks resulted in single upload, multipart is still a problem.

tusd will always upload files to S3 using multipart uploads, even if the upload is completed using one chunk.

**Comment by DennisRutjes** [comment]
no specific reason, I could configure it, so I did :-). I will omit this value, thanks for your help!

**Comment by Acconut** [comment]
You're welcome. I still haven't figured out how to properly communicate the effects and dangers of messing with the chunk size :)

**Comment by arck123** [comment]
i'm already implementation tusd v1.0.2 from v0.xx
old part my source not work 

this my source:
finishedFile := finisherDataStore.Store.Path + "/" + id + ".bin"
// Get video ID and filename from tusd.FileInfo
fileInfo, err := finisherDataStore.Store.GetInfo(id)

.GetInfo(id) => not working in v1.0.2,  message: filestore has no field or method GetInfo ..
do you have a solution to get metadata tusd.fileinfo ?

thanks
