### ISSUE TITLE
Add jq package in the docker container

### ISSUE THREAD

**Issue by konandrum** [tus/tusd#203]
To easily handle the .info data in a docker container with hooks, will be great to have jq installed

` apk add jq`

**Comment by kvz** [comment]
What’s the weight we’d add with jq?

**Comment by konandrum** [comment]
@Acconut I understand the reason to keep it as smaller as possible, but what about easily use the .info which is in json format to extract data. Furthermore hooks exemples use it: https://github.com/tus/tusd/blob/master/.hooks/post-finish#L4

FYI the hooks are not working in docker container without using `#!/bin/sh` because Alpine Linux image doesn't contain bash. So given exemples are not working.
So you could install bash or give exemples using sh which work on every linux distrib.

**Comment by Acconut** [comment]
> What’s the weight we’d add with jq?

According to https://pkgs.alpinelinux.org/package/edge/main/aarch64/jq it's about 500kb, which is acceptable.

> Furthermore hooks exemples use it

Good point, I didn't consider that. That changes my opinion on this subject, the examples should be easily usable. Are you able to provide a PR for this?

> give exemples using sh which work on every linux distrib

Oh, wasn't aware of that. Would you mind adding this to your PR?

**Comment by Acconut** [comment]
@ccarabine Your comment is a duplicate of #921. Please don't post duplicate content.
