### ISSUE TITLE
Should s3store use listParts?

### ISSUE THREAD

**Issue by janko-m** [tus/tusd#204]
In https://github.com/tus/tusd/issues/156 some interesting concerns came up which I would like to discuss and offer suggestions.

The s3store currently calls `listParts` in 

* `GetInfo` – calculates the current offset
* `WriteChunk` –  determines next part number
* `FinishUpload` – needs all parts to complete multipart upload

However, as per the [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html), `listParts` should *not* be used to complete multipart upload.

> You should not use the result of this listing when sending a complete multipart upload request. Instead, maintain your own list of the part numbers you specified when uploading parts and the corresponding ETag values that Amazon S3 returns.

To me this implies that `listParts` should not be considered a reliable source of the current state of the multipart upload. Also, currently for PATCH requests tusd fetches all multipart parts two times: (a) after fetching the `.info` object for calculating offset, and (b) for determining next part number. And the time to list of all multipart parts grows as the number of parts exceeds multiples of 1000, due to S3's per page limit of 1000 parts, it potentially adds up to a several additional HTTP requests which add overhead. https://github.com/tus/tusd/blob/6a474ce89e52b3fe63bedf6bddf865a49eac1dae/s3store/s3store.go#L325 https://github.com/tus/tusd/blob/6a474ce89e52b3fe63bedf6bddf865a49eac1dae/s3store/s3store.go#L246

So, my suggestion is: **why not store the list of parts in the `.info` S3 object?**

In [tus-ruby-server](https://github.com/janko-m/tus-ruby-server) I chose to store all information in the `.info` S3 object: length, offset, multipart id, multipart parts etc. Then since I have to retrieve the `.info` object anyway for each PATCH request (to retrieve upload length, for example), that request also automatically fetches all other information that's needed.

The only downside I see is that the `.info` object has to be updated after each PATCH request, to upload the offset and list of multipart parts. Other than that, are there any potential downsides in that approach?

**Comment by Acconut** [comment]
I remember that this topic has been brought up before. We have been running tusd in production for a long time already and never had any problems with listing parts for completing a multipart upload (although I have to admit that we never explicitly searched for them). Therefore, I would like to ask if you have an specific reason for bringing this discussion up now? Did you experience issues or are you concerned about the performance?

I know that the argument "it has always worked for us" is not a strong one but it's nice to keep that in the back of the head. That being said I am always open for suggestions on how we can improve tusd

> Other than that, are there any potential downsides in that approach?

How is the performance of downloading a bigger `.info` object from S3 compared to listing the multipart uploads parts? I can image both situations, that downloading is faster and slower than listing.

Besides that, live migration could be an issue. This proposal effectively changes to format the tusd uses to store files on S3 and is not compatible with the original format. Therefore, one cannot automatically deploy a new tusd version without risking data loss. It should be able to work around this but we need to keep this in mind.

When trying to come up with any consistency issues, I am not able to find any out of my head for now.

**Comment by janko-m** [comment]
> Therefore, I would like to ask if you have an specific reason for bringing this discussion up now? Did you experience issues or are you concerned about the performance?

No specific reason, I mostly wanted to find out if there was some discussion already about it that I missed, because I wanted to know how the two approaches might compare.

> How is the performance of downloading a bigger .info object from S3 compared to listing the multipart uploads parts? I can image both situations, that downloading is faster and slower than listing.

I imagined that the responses are about the same size when they sum up, so I would think that fewer requests is better. But on the server side the overhead of an HTTP request is probably much less noticeable.

> Besides that, live migration could be an issue. This proposal effectively changes to format the tusd uses to store files on S3 and is not compatible with the original format. Therefore, one cannot automatically deploy a new tusd version without risking data loss. It should be able to work around this but we need to keep this in mind.

Yeah, migration would be tough, there would have to be a strong reason to make the change.

> When trying to come up with any consistency issues, I am not able to find any out of my head for now.

The only thing that surprised me is that AWS is advising against this, implying that there might be some consistency issues (that's just my assumption, they didn't actually explain it). But then again, it's also known that object overwrites are eventually consistent, so relying on an S3 object that has just been updated as a source of truth is technically not safe either.

Thanks for your point, I'll close this issue.

**Comment by Acconut** [comment]
> But then again, it's also known that object overwrites are eventually consistent, so relying on an S3 object that has just been updated as a source of truth is technically not safe either.

Good point, I didn't think about that on my own. However, I believe the same eventual consistency also applies to the ListParts method, as you mentioned. So my understanding is that you cannot build a fully consistent data store purely based on S3 (which is really unfortunate for us).

> Thanks for your point, I'll close this issue.

I didn't meant to end the topic here but I will have a look in the near future if we can improve the performance by not using ListPart.
