### ISSUE TITLE
413 Request entity too large

### ISSUE THREAD

**Issue by azharmalik3** [tus/tusd#205]
I am using tusd in my project for file uploading using `tus-js-client`. 

It's working fine for small size file upload. Less than 1MB file upload without an error but when I try to upload a 2MB file it gives following error:
```
Error: tus: unexpected response while uploading chunk, originated from the request. response text: 413 Request Entity Too Large
```

Is there any configuration to control upload limit? or something else?

**Comment by Acconut** [comment]
tusd has the `-max-size` flag to control the maximum allowed upload size (see https://github.com/tus/tusd#running-tusd). However, by default this flag is disabled, meaning not limit is imposed.

Could it be that you are running a proxy which also restricts the upload size?

**Comment by azharmalik3** [comment]
I fixed this issue by increasing the upload limit in `Nginx`.
Thanks.

**Comment by mraslam** [comment]
@azharmalik3 @Acconut  Good morning, we are facing the same issue. I tried changing the client_max_body_size in multiple places for nginx but still same issue. Do you have any other suggestion?

**Comment by Acconut** [comment]
@mraslam Did you correctly set the `-max-size` option for tusd? Besides configuring tusd and nginx, I don't have any other suggestion right now.
