### ISSUE TITLE
Hooks don't work on Windows

### ISSUE THREAD

**Issue by pixelistik** [tus/tusd#206]
## Steps to reproduce

Download and unzip the latest Windows release https://github.com/tus/tusd/releases/download/0.10.0/tusd_windows_amd64.zip

Create a hook directory `tusd-hooks` with all 5 required hook scripts

Start tusd with the required param 

    tusd.exe --hooks-dir tusd-hooks

Configure your localhost as the endpoint for a Tus client, e.g. Uppy.

Start an upload from the client.

## Result

The upload is reported as failed by the client

For each hook, `tusd` logs the following error
```
"
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="HookInvocationStart" type="pre-create" id=""
[tusd] event="HookInvocationError" type="pre-create" id="" error="exec: "C:\\projects\\myproject\\tusd-hooks/pre-create": file does not exist"
[tusd] event="ResponseOutgoing" status="500" method="POST" path="" error="pre-create hook failed: exec: "C:\\projects\\myproject\\tusd-hooks/pre-create": file does not exist
"
```

Note the critical part `"C:\\projects\\myproject\\tusd-hooks/pre-create": file does not exist`

## Expected

The upload should succeed. The hooks should be executed.

## Version
    Version: 0.10.0
    Commit: 966f1d51639d3405b630e4c94c0b1d76a0f7475c
    Date: Mon Mar 19 11:23:04 UTC 2018

## Notes

I think the problem is a non-portable file path built at https://github.com/tus/tusd/blob/6a474ce89e52b3fe63bedf6bddf865a49eac1dae/cmd/tusd/cli/hooks.go#L149

According to the Go documentation at https://golangcode.com/cross-platform-file-paths/, cross-platform paths should be handled differently, thus the path built with string concatenation with "/" fails on Windows.

**Comment by Acconut** [comment]
Thank you for this detailed report. The latest commit should fix this problem which you correctly identified. Would you mind testing the latest code from the master branch to ensure that it works?

**Comment by pixelistik** [comment]
Thank you for the fix.
The path is now constructed correctly.

**Comment by Acconut** [comment]
Perfect, that's nice to hear. I will cut a new release soon then.
