### ISSUE TITLE
Request to write the info file after upload completes

### ISSUE THREAD

**Issue by ldadams** [tus/tusd#207]
Just a suggestion regarding how storage systems might better understand when file uploads are complete.  We are using Tus with S3 and for the most part everything is working out very well.  One thing we are having to work around is how best to use S3 events to process newly uploaded files.  Currently the .info file is written before the actual file is uploaded.  This makes it a bit tricker to have an efficient way trigger follow up actions to the actual uploaded file.  S3 allows for suffix and prefix filters for events but it's my understanding that current the s3Store does not allow for configuration of the prefix or "folder" that .info and actual upload files are placed.  Also, the actual uploaded file doesn't have an extension so we aren't able to filter just for something like .file.

The current approach we are taking is to use a post-finish hook to write an SQS message.  This will work fine but would be great to take advantage of the already existing events triggered in S3.

I would be willing to add a feature to configure the s3Stores ability to place info files and actual uploaded files in folders / S3 Prefixes if I might get a bit of guidance on how best to contribute that.  This would allow us to not listen for .info file events and just actual file uploads.

Thanks!

**Comment by Acconut** [comment]
> Request to write the info file after upload completes

One comment to the title: It is not easily possible to write the info file after the upload completes. The info file contains part of the upload state which is needed for resuming (e.g. after the connection is interrupted). Therefore, we need to store the state somewhere persistently which is S3 in this case.

> The current approach we are taking is to use a post-finish hook to write an SQS message.

Personally, this sounds like the best approach to me. tusd knows best when an upload is finished especially when working with concatenating uploads. However, I can also understand that this may not be a good approach for your architecture.

> I would be willing to add a feature to configure the s3Stores ability to place info files and actual uploaded files in folders / S3 Prefixes if I might get a bit of guidance on how best to contribute that. This would allow us to not listen for .info file events and just actual file uploads.

I have never thought about different prefixes for the info and binary files but it makes sense. Only very few people in the past have asked about specifying folders for S3 uploads, so we haven't added support for it. However, I would be happy to help with and accept a PR if you are willing to supply.

**Comment by ldadams** [comment]
Thanks for the response.  We implemented the SQS functionality and works well.  If we decided that we would rather have S3 native support by separating out info and actual files will come back and help put this together.  Thanks again!
