### ISSUE TITLE
How to execute code when lifecycle events happen like tus-node-server

### ISSUE THREAD

**Issue by ahmadaidil** [tus/tusd#209]
Hi,

I am new in go and use tusd server for uploading files into minio cloud storage. After the upload finished, I want to save metadata into my database. 

In the tus-node-server, It has lifecycle event that can be execute for the next process like this:
```
const Server = require('tus-node-server').Server;
const EVENTS = require('tus-node-server').EVENTS;

const server = new Server();
server.on(EVENTS.EVENT_UPLOAD_COMPLETE, (event) => {
    console.log(`Upload complete for file ${event.file.id}`);
});
```
so how to get event like above when the upload has completed in tusd ?

Thank you.

**Comment by Acconut** [comment]
tusd has a hook system which is similar to tus-node-server's events. You can more about it in detail at the documentation: https://github.com/tus/tusd/blob/master/docs/hooks.md. Let my know if you have questions afterwards.

**Comment by ahmadaidil** [comment]
Below is my code

package main
```
func main() {
	dotenvErr := godotenv.Load()
	if dotenvErr != nil {
		log.Fatal("Error loading .env file")
	}

	http.Handle("/upload/", http.StripPrefix("/upload/", upload.Handler()))
	err := http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}
```

package upload
```
func Handler() http.Handler {
	godotenv.Load()

	accessKey := os.Getenv("MINIO_ACCESS_KEY")
	secretKey := os.Getenv("MINIO_SECRET_KEY")
	endpoint := os.Getenv("MINIO_ENDPOINT")
	region := os.Getenv("MINIO_REGION")
	bucket := os.Getenv("MINIO_BUCKET")

	sess := session.Must(session.NewSession(&aws.Config{
		Region:      aws.String(region),
		Credentials: credentials.NewStaticCredentials(accessKey, secretKey, "")}))

	s3Config := aws.NewConfig().
		WithEndpoint(endpoint).
		WithS3ForcePathStyle(true)

	svc := s3.New(sess, s3Config)

	store := s3store.New(bucket, svc)

	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	handler, err := Handlernyahandler(tusd.Config{
		BasePath:      "/upload/",
		StoreComposer: composer,
	})
	if err != nil {
		panic(fmt.Errorf("unable to create handler: %s", err))
	}

	return handler
}
```

How can I call hook when the upload is complete ? Could you please give me an example in my code ?

**Comment by Acconut** [comment]
Hooks are meant when you are using the tusd as a binary. This is the easiest way to run tusd and is also in most cases enough. For details on how to do this, please see https://github.com/tus/tusd#running-tusd.

If you are using tusd as a library (what your code looks like), you can utilize the channels in the Handler struct (see https://godoc.org/github.com/tus/tusd#UnroutedHandler). You simply enable the channels in the configuration for your handler and then read from the channels you want. The documentation should answer most questions about them.

**Comment by ahmadaidil** [comment]
I get it, thank you @Acconut .

**Comment by Acconut** [comment]
You're welcome!
