### ISSUE TITLE
Remove .bin suffix on binary filenames of local store

### ISSUE THREAD

**Issue by bench** [tus/tusd#210]
Currently GCS files are stored under `bucket/fileID` where as local files are stored under `baseDir/fileID.bin`.

It would be great if we could **homogeneize the behaviour** of all stores so that all stores follow the same naming convention when saving binary files.

This way, post-processings in hooks could be mutualized more easily.

**Comment by Acconut** [comment]
I am in favor of having a shared naming scheme between the different data stores. Dropping the `.bin` extension and used the uploaded file's extension instead has been discussed before. However, the main reason for not doing it was backwards compatibility, as it may easily break for existing integration. That being said, I would like to consider this change for the next major release (see #212).

> This way, post-processings in hooks could be mutualized more easily.

I do understand the reasoning behind this but I have never come across a situation where you would have tusd servers uploading to different data storages. Do you have such a use case?

**Comment by bench** [comment]
Thank you @Acconut for your quick feedback.

I understand the backwards compatibility reasons and I hope we could integrate this change in the next major release.

> I  do understand the reasoning behind this but I have never come across a situation where you would have tusd servers uploading to different data storages. Do you have such a use case?

Yes we do. My team develops an e-care image analysis solution and we provide a saas solution with data stored on GCS. But some of our customers (for privacy reasons or network limitations) prefer self hosted solutions. In that case we store on disk. 

We use hooks (actually XXXUploads channels of your UnroutedHandler) and try to mutualize as much logic as possible

**Comment by Acconut** [comment]
> Yes we do. My team develops an e-care image analysis solution and we provide a saas solution with data stored on GCS. But some of our customers (for privacy reasons or network limitations) prefer self hosted solutions. In that case we store on disk.

Ok, that makes sense. It's a use case, I have never thought about, thanks for bringing it up.

I will try to integrate this into the next major release of tusd and leave this issue open in the meantime.
