### ISSUE TITLE
Upload-Concat header not in Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by PaddoSwam** [tus/tusd#214]
I tried to make use of the [concatenation](https://tus.io/protocols/resumable-upload.html#concatenation) extension of the tus protocol to improve high-ping transfer speed and ran into an issue with CORS making the final Upload-Concat call from the browser. The error that it gave me was:
```
Access to XMLHttpRequest at 'http://127.0.0.1:1080/files/' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Request header field Upload-Concat is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by Acconut** [comment]
Fixed in your PR #215, thanks!
