### ISSUE TITLE
Anyone managed to disable IPv6 from Nginx -> tusd ?

### ISSUE THREAD

**Issue by dcs3spp** [tus/tusd#218]
Hi, 

I am a newbie running tusd server on macos High Sierra behind an Nginx Proxy running within a docker container. In the logs, I notice that before an _UploadCreated_ event is received there is an attempt to connect to tusd using ipv6 loopback address which fails. 

_[crit] 23#23: *4 connect() to [::1]:1080 failed (99: Address not available) while connecting to upstream, client: 172.22.0.1, server: , request: "POST /files/ HTTP/1.1", upstream: "http://[::1]:1080/files/", host: "test.example.com:1081"_

I am running tusd with `-behind-proxy` and no additional `-host` string, so it is using the default listen address of 0.0.0.0. I am using an nginx configuration derived from the sample posted in the docs folder of the repository.  
```
server {
  listen                          1081 ssl http2;
  #listen [::]:443 http2 ipv6only=on ssl;
  charset                         utf-8;

  access_log                      /dev/stdout;
  error_log                       /dev/stdout;

  ssl_certificate                 /server/certs/tls.crt;
  ssl_certificate_key             /server/certs/tls.key;

  location /files/ {

    resolver 8.8.8.8 4.2.2.2;
    #resolver 8.8.8.8 4.2.2.2 ipv6only=off;

    proxy_pass  http://localhost:1080/files/;
    #proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # Disable request and response buffering
    proxy_request_buffering  off;
    proxy_buffering          off;
    proxy_http_version       1.1;

    # Add X-Forwarded-* headers so that response can reference https and
    # originating host:port
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Allow proxying of websockets if required
    proxy_set_header         Upgrade $http_upgrade;
    proxy_set_header         Connection "upgrade";
    client_max_body_size     0;
  }
```
If I take out the line, _listen                          [::]:1081 http2 ipv6only=on ssl;_ from the server config block, the issue still occurs. 

Upon further reading at [docker](https://docs.docker.com/config/daemon/ipv6/) and [docker-for-mac](https://github.com/docker/for-mac/issues/1432), it appears that ipv6 networking is only available for docker daemons running on Linux hosts???

I have tried adding a resolver and setting ipv6only=off but nginx seems to continue to try and send to the upstream proxy with an ipv6 address. 

I appreciate, based upon what I have read, that this appears to be an issue with configuration of nginx and docker and will post the query to community forums. However, has anybody else experienced and resolved the same issue when using nginx as a proxy?

**Updated**

Solved this by specifying ipv4 address 127.0.0.1 instead of localhost :)

Kind regards

dcs3spp

**Comment by Acconut** [comment]
> Solved this by specifying ipv4 address 127.0.0.1 instead of localhost :)

Haha, perfect. I was just about to suggest testing that :) I am happy to read that you where able to work this out on your own.

I am going to close this issue then, feel free to open another ticket if you have another question.
