### ISSUE TITLE
What is the best practice to download a renamed file?

### ISSUE THREAD

**Issue by yangyadi1993** [tus/tusd#222]
After I uploaded the file using tusd, I used a hook to move it to another directory and renamed it using its original name.

At this time, if I want to download this file, what should I do? I have cloned the repo and plan to do some modification myself. I saw the current way is based on id. So what should be the right way to download a renamed file?

**Comment by mohanklein** [comment]
I do something similar and ended up using nginx to serve downloads, as I didn't know any better. I also need my users to be able to delete these moved files via my backend server which is on a completely different machine ... Ath the moment I create an additional file "secret.key" in post-finish hook which I save together with the uploaded file and its info file in the same directory. I then tell it to my backend server via curl, when the upload is processed/converted. I also created a single lightweight delete endpoint in ruby which deletes a file if the request contains the correct "password" (secret.key file).
This seems to be really bad and complex custom architecture, so I hope there is a better way to to this :-)

**Comment by yangyadi1993** [comment]
As a result, I used Go backend to serve download file directly and used a separate url. I did the same thing with the delete file function. So tusd is only used for upload.

**Comment by Acconut** [comment]
Apologies for my delayed response. I am glad to read that you found a solution.

> So tusd is only used for upload.

I agree, this is the best approach. tusd should not be used to download files except for testing/development purposes. We usually recommend using a proxy such as Nginx/Apache for serving files but your own Go server which is optimized for this task is also a good fit.
