### ISSUE TITLE
Prevent Download

### ISSUE THREAD

**Issue by BrandonSharratt** [tus/tusd#223]
Is there a way to disable the download in the tusd binary, I've looked at all the cli flags and don't see anything in particular about how to disable the download serving. Looking through the code when you're using S3 it looks like it overwrites anything I could do to disable it as it just passes the GetReader on.

(I'm using Minio as the s3 storage)

**Comment by Acconut** [comment]
There is currently no option to disable downloads. If you want to prevent users from downloading the files you could use a proxy to catch GET requests to the `/files/*` endpoint and not forward them to tusd but instead show an error message or similar.

**Comment by DravitLochan** [comment]
@Acconut Any plan to add "disable-download"?

**Comment by Acconut** [comment]
We are open for PRs but do not have a concrete plan to implement it on our own in the near future :)

**Comment by DravitLochan** [comment]
Sure, V2 is the latest branch, right? Also, can you re-open this issue?

**Comment by Acconut** [comment]
Yes and yes. Also, if you are unsure how to approach the implementation, let me know and we can discuss different designs.

**Comment by DravitLochan** [comment]
@Acconut bump!

**Comment by Acconut** [comment]
@DravitLochan Apologies for the late reply! 

> Haven't gone through the TUS code till now but my first set of thoughts are to allow users to set a param in their handler config, say `DisableDownload`, with type = `boolean`.
> 
>     * If set to `true`, we simply throw a `403 forbidden, this method is not allowed` (or something on the similar lines).
> 
>     * In case the above parameter is missing, which makes it the default case, OR the param is set to `false` explicitly, we do nothing and allow the flow as it is.
> 
> 
> What do you think of this as a solution?

I think this approach would sound amazing! In addition, if DisableDownload is true, the GET handler should not be mounted, so the GET requests get directly denied from our HTTP router (i.e. put this line into an conditional statement: https://github.com/tus/tusd/blob/master/pkg/handler/handler.go#L43)

**Comment by omBratteng** [comment]
@Acconut any work being done with this? If not, I can take a look, as we need to prevent downloads.

**Comment by Acconut** [comment]
@omBratteng No, there has been no work done from our side. A simple option to disable the mounting of the GET handler would suffice. Feel free to open a PR for that.

**Comment by omBratteng** [comment]
@Acconut PR opened in #668

**Comment by omBratteng** [comment]
I also added a flag to disable deletion of uploaded files
