### ISSUE TITLE
The new Creation Defer Length Support Breaks existing configurations

### ISSUE THREAD

**Issue by explodingcamera** [tus/tusd#226]
The new changes introduced in https://github.com/tus/tusd/commit/33d12533e79db367bbd432ad912b84b0bdd4ce32 break existing Minio Configurations.
Before this commit, using minio as a s3 server worked flawlessly, but now I'm getting an `404 Not Found` Error on the first PATCH Request and nothing else. It seems like the .info files can't be found (I've checked minio and they do seem to exist and have the correct content).
I'm running the `UnroutedHandler` on go 1.11.4 with the latest version of the tus-js-client & minio/minio:latest.
I'm using no special config options except MaxSize, BasePath and the provided Channels.

**Comment by acj** [comment]
@explodingcamera Thanks for the report. If possible, please give the workaround in #228 a try and let me know if it fixes the problem.

**Comment by KlausVii** [comment]
This is also happening with regular S3, create works, but the PATCH returns 404

**Comment by Acconut** [comment]
I can confirm that the patch from https://github.com/tus/tusd/pull/228 fixes the problem with uploading to S3 for my local setup. I just merged this fix into master. Are you able to resolve the issue now with the latest commit?

**Comment by Acconut** [comment]
> To protect existing deployments, we could add "Forbidden" to the whitelisted responses here. If a bucket is configured such that HeadObject always returns "Forbidden", then incomplete parts won't be included in size calculations. In such a scenario, tusd would return to its previous behavior -- i.e., chunks smaller than MinPartSize would be effectively dropped and would need to be uploaded again.

This sounds like a good approach to me.

> This may result in conflict errors, but I think most clients would consult the server and obtain a fresh offset.

Every "properly" implemented client does it that way, so I would not worry about this. The server also always checks if the Upload-Offset header matches the actual offset to prevent mismatches.

> We also have the option of using GetObject instead of HeadObject even though the GetInfo function doesn't need to read the object's contents. This approach would be fully compatible with existing bucket configurations, but it may carry a small cost in efficiency.

I was thinking about merging the HeadObject and GetObject calls into a single GetObject call to improve performance but we currently don't have the code infrastructure for that. So that's just future talk for now.
