### ISSUE TITLE
upload is not resumed but restarted

### ISSUE THREAD

**Issue by kevin-kirsten** [tus/tusd#234]
Hi all,
     recently I encounter an issue that an upload is keep restarted instead of resumed. everytime when upload a file, the upload is restarted and all uploaded chunks are gone.

I am wondering if this is caused by network unstable, and here is the related log I can found.

```
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="RequestIncoming" method="HEAD" path="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="ResponseOutgoing" status="423" method="HEAD" path="c22685373fb0ee72e3ac500af3290e62" error="file currently locked"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="RequestIncoming" method="POST" path=""
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="pre-create" id=""
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="pre-create" id=""
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="UploadCreated" id="197cced88086f3295294321947c3deb5" size="955467073" url="http://127.0.0.1:1088/files/197cced88086f329529432
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="ResponseOutgoing" status="201" method="POST" path=""
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-create" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-create" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="RequestIncoming" method="PATCH" path="197cced88086f3295294321947c3deb5"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="ChunkWriteStart" id="197cced88086f3295294321947c3deb5" maxSize="955467073" offset="0"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:24 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:25 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:25 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:25 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:25 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="197cced88086f3295294321947c3deb5"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="ResponseOutgoing" status="500" method="PATCH" path="c22685373fb0ee72e3ac500af3290e62" error="read tcp: i/o timeout"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:26 example.com tusd[3440]: [tusd] event="HookInvocationFinish" type="post-receive" id="c22685373fb0ee72e3ac500af3290e62"
Jan 21 11:17:27 example.com tusd[3440]: [tusd] event="HookInvocationStart" type="post-receive" id="197cced88086f3295294321947c3deb5"
```

What i notice above is an upload (c22685373fb0ee72e3ac500af3290e62) encounter an error 423, which is "file currently locked" and a new upload (197cced88086f3295294321947c3deb5) is triggered right after the error, which both upload are the same file. And then the first upload is finally return an error 500 which is "read tcp: i/o timeout". So this is the reason the upload is restarted.

so from the above log, can I concluded that is due to the network unstable and what can I do for the case?

many thanks!

**Comment by kevin-kirsten** [comment]
is this the reason it start a new upload?

https://github.com/tus/tus-js-client/issues/37

but in my case, no 2nd upload manually.

**Comment by Acconut** [comment]
Apologies for my delayed response, I don't have much time at my hands right now. The issue you have linked (https://github.com/tus/tus-js-client/issues/37) was fixed two years ago, so assuming that you are using a rather recent version of tus-js-client, this should not directly affect you.

However, would you mind describing what you are doing on the client-side (e.g. pausing/resuming/etc) to produce this error? In addition, could you post your configuration that is passed to `tus.Upload` from tus-js-client?

**Comment by kevin-kirsten** [comment]
@Acconut  sorry for late reply, and here is the detail

we have several users that will use tusd for continuous upload. However one of the users from china reported that they encountered the above issue even we have moved the server to china.

The user will upload a file by a html input type='file' button, the below jquery script will be triggered by jquery 'change' method when a file is selected. 

the upload just restarted itself without any action by user.

```js
var fileupload = new tus.Upload(file, {
  endpoint: "//"+root_url+tusd_url,
  retryDelays: [0, 1000, 3000, 5000, 10000, 10000],
  metadata: {name: file.name, size: file.size},
  headers:{ "Authorization" : data.header_str},
  onError: function(error) {
    // on error handler
  },
  onProgress: function(bytesUploaded, bytesTotal) {
   // on progress handler
  },
  onSuccess: function() {
   // on success handler
   }
});

fileupload.start();
```

**Comment by Acconut** [comment]
I can't spot any problem with your script you supplied, it looks good to me. The only idea I have right now is that (for some unknown reason) the PATCH request of the first upload fails. After that the client tries to resume but the original upload is still locked (because the server doesn't yet know that the client wants to retry). However, in any recent version of tus-js-client this should not trigger a new upload. What version of tus-js-client and tusd are you using?

Also, in the original log snippet you posted, not all logs for the first upload (c22685373fb0ee72e3ac500af3290e62) are shown. Could you still supply them or reproduce this problem and provide the full logs?

**Comment by kevin-kirsten** [comment]
I am sorry I cannot find the version information about the js client i am using, I have uploaded the file to https://ufile.io/a8alg (valid until 28 Mar 2019), could you please kindly see if there is any hints?

and for the log, I am so sorry they are rotated by the system and I don't found same issue within the active rotation period. Please let me get back to you if this happen again.

**Comment by Acconut** [comment]
> I am sorry I cannot find the version information about the js client i am using, I have uploaded the file to https://ufile.io/a8alg (valid until 28 Mar 2019), could you please kindly see if there is any hints?

The file in the archive has a modification date of May 2017 and it does not contain the patch I linked above. Please upgrade to the *latest* tus-js-client version and then see if the problem persists. The upgrade should be without problems since there were no backwards-compatibility breaking changes in that time.

**Comment by kevin-kirsten** [comment]
many thanks! I will update it to the latest version!
thanks for your great help!
