### ISSUE TITLE
-expose-metrics flag ignored

### ISSUE THREAD

**Issue by brandonkal** [tus/tusd#238]
Thank you for this. I believe I found a bug.

Sending the `-expose-metrics false` flag does nothing. Metrics are still available at /metrics

```
$ tusd -expose-metrics false
tusd    | [tusd] Using '/srv/tusd-hooks' for hooks
tusd    | [tusd] Using 0.00MB as maximum size.
tusd    | [tusd] Using 0.0.0.0:1080 as address to listen.
tusd    | [tusd] Using /files/ as the base path.
tusd    | [tusd] Using /metrics as the metrics path.
tusd    | [tusd] Core: ✓ Terminater: ✓ Finisher: ✓ Locker: ✓ GetReader: ✓ Concater: ✓ LengthDeferrer: ✗
```

Visiting localhost:1080/metrics, all the stats are there.

**Comment by brandonkal** [comment]
Sorry about that.
```
tusd -expose-metrics=false
```
will work as expected.

**Comment by ahmadalli** [comment]
@brandonkal would you please update the documentation too?

**Comment by brandonkal** [comment]
Actually this should be fixed to work with a space as it is inconsistent. The readme shows other flags and their parameters separated by a space.

**Comment by Acconut** [comment]
Go's flag parser doesn't allow a space as a separator for boolean values (see https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax). I understand that this is a bit inconvenient but also not really fixable for us. I am going to update the docs to always use a `=`. Thanks for pointing this out.

**Comment by lshz0088** [comment]
@Acconut 

In order to be compatible with `POSIX` standard, can you replace it with the following `flag`?

Otherwise, parameters cannot be passed in the docker in brackets.

https://github.com/spf13/pflag

**Comment by Acconut** [comment]
@lshz0088 Please open a new issue about this proposal. Replacing the flag parser is possible but might also break the use cases for existing users, so it must be considered very carefully.
