### ISSUE TITLE
Add option to disable post-receive hook

### ISSUE THREAD

**Issue by brandonkal** [tus/tusd#239]
When using HTTP hooks, it would be nice to disable the post-receive hook especially when the receiving server is low power (think raspberry pi) or is slow to respond.

For instance, I have a system with a slow REST API response time (500ms). A single upload can easily tax the CPU with moderate web traffic. My current  solution is to create a seperate php script on this server that checks the event type and calls its actual REST API if the event is not a post-receive. This chained approach works, but a simple cli option to simply not send the HTTP POST would be an appreciated simplification.

**Comment by Acconut** [comment]
I can understand your situation, thanks for bringing this up. Let's discuss implementation details in your PR.

**Comment by Acconut** [comment]
A whitelist for hook events has been added in https://github.com/tus/tusd/commit/f1fe5e26034504f084c97cd53cccc65271425095.
