### ISSUE TITLE
Wrong error if bucket doesn't exists in gcloud storage

### ISSUE THREAD

**Issue by zvictor** [tus/tusd#241]
If I set a bucket name that doesn't exist for Google Cloud Storage, I get a 404 response when I try to upload and the logs show an `upload not found` error:

```haskell
[tusd] Using '/srv/tusd-hooks' for hooks
[tusd] Using 'gcs://ANY_BUCKET_NOT_CREATED' as GCS bucket for storage.
[tusd] Using 0.00MB as maximum size.
[tusd] Using 0.0.0.0:1080 as address to listen.
[tusd] Using /files/ as the base path.
[tusd] Using /metrics as the metrics path.
[tusd] Core: ✓ Terminater: ✓ Finisher: ✓ Locker: ✓ GetReader: ✓ Concater: ✗ LengthDeferrer: ✗
[tusd] event="RequestIncoming" method="OPTIONS" path="169220b41d977e7cf1d15bb612800593"
[tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path="169220b41d977e7cf1d15bb612800593"
[tusd] event="RequestIncoming" method="HEAD" path="169220b41d977e7cf1d15bb612800593"
[tusd] event="ResponseOutgoing" status="404" method="HEAD" path="169220b41d977e7cf1d15bb612800593" error="upload not found"
[tusd] event="RequestIncoming" method="OPTIONS" path=""
[tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path=""
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="HookInvocationStart" type="pre-create" id=""
[tusd] event="HookInvocationFinish" type="pre-create" id=""
[tusd] event="UploadCreated" id="6dedfea1963c146d92abcd6118f9ba86" size="32119393" url="http://127.0.0.1.nip.io/files/6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="ResponseOutgoing" status="201" method="POST" path=""
[tusd] event="HookInvocationStart" type="post-create" id="6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="HookInvocationFinish" type="post-create" id="6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="RequestIncoming" method="OPTIONS" path="6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path="6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="RequestIncoming" method="PATCH" path="6dedfea1963c146d92abcd6118f9ba86"
[tusd] event="ResponseOutgoing" status="404" method="PATCH" path="6dedfea1963c146d92abcd6118f9ba86" error="upload not found"
```

---

server (docker-compose.yml):

```yaml
version: '2.4'

services:
  tusd:
    image: tusproject/tusd:0.11.0
    command: ['--gcs-bucket', 'ANY_BUCKET_NOT_CREATED']
    environment:
      GCS_SERVICE_ACCOUNT_FILE: '/application-credentials.json'
    volumes:
      - ~/application-credentials.json:/application-credentials.json
```

client:

```js
import React from 'react'
import Uppy from '@uppy/core'
import Tus from '@uppy/tus'
import { Dashboard } from '@uppy/react'

const uppy = Uppy({
  meta: { type: 'avatar' },
  restrictions: { maxNumberOfFiles: 1 },
  autoProceed: true,
})

uppy.use(Tus, {
  endpoint: 'http://127.0.0.1.nip.io/files/',
  resume: true,
  autoRetry: true,
  retryDelays: [0, 1000, 3000, 5000],
})

uppy.on('complete', result => {
  const url = result.successful[0].uploadURL
  console.log(url)
})

const Component = () => <Dashboard uppy={uppy} />

Component.displayName = 'UppyPageComponent'
export default Component
```

**Comment by tab1293** [comment]
What is the behavior you are expecting? It should be a prerequisite that the bucket you are trying to upload exists, tusd should not be responsible for creating GCS buckets on the fly.

**Comment by zvictor** [comment]
> tusd should not be responsible for creating GCS buckets on the fly.

I agree, but more descriptive error messages are always welcome since they reduce time wasted in troubleshooting.

In my case, I started using gcloud storage at the same time I started playing with tusd, so the idea of how a bucket was supposed to work was not clear in my mind yet. I could only understand the problem after doing some search and ending up at #98

However, to be honest, I don't think this issue should be a high priority. I was more worried with documenting the issue and helping future people in their troubleshooting.

**Comment by Acconut** [comment]
I agree that we should have a better error message in this case. @zvictor, would you mind giving this a try? I think we only need to consider `storage.ErrBucketNotExist` (https://godoc.org/cloud.google.com/go/storage#pkg-variables) in our error handling here: https://github.com/tus/tusd/blob/master/gcsstore/gcsstore.go#L124-L129

**Comment by zvictor** [comment]
@Acconut how can I try this? I have no experience with go, I am only running the docker image 😅

**Comment by Acconut** [comment]
@zvictor Apologies for my delayed response. I went ahead an issued a patch which should improve the error message when a new upload is created with a non-existing bucket. It will be included in the next release but you can also try it out if you build the latest tusd version on your own. Thanks for offering your help :)
