### ISSUE TITLE
GCS Scope

### ISSUE THREAD

**Issue by Dargmuesli** [tus/tusd#243]
What exactly is the [devstorage.read_write](https://www.googleapis.com/auth/devstorage.read_write) scope mentioned here?

https://github.com/tus/tusd/blob/cbaba850a7d935fe2c306de42c10770556e52391/gcsstore/gcsstore.go#L7-L9

I cannot find this permission in my GC project. Only those seem to be available to me:
```
    storage.buckets.get
    storage.buckets.getIamPolicy
    storage.buckets.setIamPolicy
    storage.buckets.update
    storage.objects.create
    storage.objects.delete
    storage.objects.get
    storage.objects.getIamPolicy
    storage.objects.list
    storage.objects.setIamPolicy
    storage.objects.update
```

Maybe you, @tab1293, can clear things up for me? Maybe I confuse different parts of GCS.

I currently receive this error: `unexpected response while uploading chunk, originated from request (response code: 404, response text: upload not found` and that currently looks like a permission problem and doesn't seem to be related to #241 as my bucket should exist. At least that's what my eyes tell me.

**Comment by tab1293** [comment]
@Dargmuesli you should create a service account file via the GCloud console under `IAM & Admin -> Service accounts` and give it the `storage.admin` role. Then download the service account file and run tusd with `GCS_SERVICE_ACCOUNT_FILE=/path/to/service_account.json` environment variables set.

More on storage IAM roles here: https://cloud.google.com/storage/docs/access-control/iam-roles

**Comment by Dargmuesli** [comment]
That worked indeed, thanks a lot! <3
But why are permissions included in the `storage.admin` role like `storage.buckets.setIamPolicy` or `storage.buckets.delete` needed?

For people landing here who don't know: if you change roles for a service account, you do *not* need to (re)downloaded the service account file.
