### ISSUE TITLE
Resume upload for minio as the storage backend failed

### ISSUE THREAD

**Issue by EvgenyKislyy** [tus/tusd#244]
I've built tusd locally
I've run it looking into the play minio open endpoint

$ echo $AWS_SECRET_ACCESS_KEY
zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

$ echo $AWS_ACCESS_KEY_ID
Q3AM3UQ867SPQQA43P2F 

run server
tusd --s3-bucket test  -s3-endpoint https://play.minio.io:9000

Ok, started fine

Creating very simple uppy page from getting started page
https://uppy.io/docs/

with endpoint 
http://localhost:1080/files/

Just uploading without pause and resume works fine
Then if I press pause and then resume - it's failed
With an error

> [tusd] event="UploadCreated" id="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" size="89027314" url="http://localhost:1080/files/e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" 
> [tusd] event="ResponseOutgoing" status="201" method="POST" path="" 
> [tusd] event="RequestIncoming" method="OPTIONS" path="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" 
> [tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" 
> [tusd] event="RequestIncoming" method="PATCH" path="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" 
> [tusd] event="ChunkWriteStart" id="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" maxSize="89027314" offset="0" 
> [tusd] event="RequestIncoming" method="HEAD" path="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" 
> [tusd] event="ResponseOutgoing" status="423" method="HEAD" path="e155c5e940552b7a6ccd79ec306fa92a+9979cdf4-9bbf-4f98-b769-e69b14d5d1f8" error="file currently locked" 

Could you please help me with checking minio and resumable uploads? 
If there is file storage - pause/continue uploading works fine.

Thanks

**Comment by Acconut** [comment]
Thank you for reporting, could you supply the tus configuration that you are using to initialize Uppy?

**Comment by EvgenyKislyy** [comment]
Sure
It's just simple HTML page from the
https://uppy.io/docs/

the code is
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Uppy</title>
    <link href="https://transloadit.edgly.net/releases/uppy/v0.30.0/dist/uppy.min.css" rel="stylesheet">
  </head>
  <body>
    <div id="drag-drop-area"></div>

    <script src="https://transloadit.edgly.net/releases/uppy/v0.30.0/dist/uppy.min.js"></script>
    <script>
      var uppy = Uppy.Core()
        .use(Uppy.Dashboard, {
          inline: true,
          target: '#drag-drop-area'
        })
        .use(Uppy.Tus, {endpoint: 'http://localhost:1080/files/'})

      uppy.on('complete', (result) => {
        console.log('Upload complete! We’ve uploaded these files:', result.successful)
      })
    </script>
  </body>
</html>
```

**Comment by Acconut** [comment]
You seem to be missing the retryDelays parameter for Uppy.Tus. Please add `retryDelays: [0, 3000, 5000, 10000, 20000]` to its configuration and try again.

**Comment by EvgenyKislyy** [comment]
Cool, thanks @Acconut 
Now it works fine

And I have one more question
So I am doing my upload of a big file to minio
I press pause from time to time, and checking the minio file size
And Even if I upload 50% of 500 mb file
In the minio I see 

e4c1eb7afc420bb5db3c5c82d13f5bce.info
328 bytes
Feb 27, 2019 2:14 PM


e4c1eb7afc420bb5db3c5c82d13f5bce.part
645.47 KB
Feb 27, 2019 2:18 PM

So the *.part file is always small
If 50% of 1GB file is already uploaded, where you are storing this 500MB?
Cannot see them in Minio Web Browser
Are they somewhere locally on my PC?

**Comment by Acconut** [comment]
> Are they somewhere locally on my PC?

No, don't worry, that's not the case. Storing it locally wouldn't make any sense if you try to upload something.

To answer your question, you have to look at the implementation. The S3Store stores your upload in three different places:
* The `.info` object contains basic details about the upload, e.g. metadata or the upload size.
* The `.part` object contains parts of the last uploaded chunk. This object only exists while the upload is not complete and is **not** the actual file but rather a temporary buffer. It's size is usually bellow 5MB.
* The actual file is stored in a multipart upload (https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). While a multipart upload is not finished (i.e. the tus upload is not completed), you cannot see the file is any browser as it's still in progress (Minio does store it on disk but I don't know where). Once the upload is finished, you will see a new object without any file extension (e.g. 
e4c1eb7afc420bb5db3c5c82d13f5bce) appear in your browser.
