### ISSUE TITLE
limitedStore should purge oldest files rather than largest

### ISSUE THREAD

**Issue by chendo** [tus/tusd#254]
This is less likely to cause issues for end users where they're uploading multiple large files in succession as it's currently causing files to 404 when uploads are being processed.

**Comment by Acconut** [comment]
I agree that the current situation is not ideal. You can adjust the deletion order by modifying `limitedstore.go` (https://github.com/tus/tusd/blob/master/limitedstore/limitedstore.go). I would be happy to accept a PR for it but we don't have the resources right now for that on our own (especially considering that limitedstore is going to be removed in the next major version).

**Comment by Acconut** [comment]
Closing this since the limitedstore package will be removed in the next release 1.0. See https://github.com/tus/tusd/issues/212 for more details.
