### ISSUE TITLE
Listening multiple paths

### ISSUE THREAD

**Issue by ahmetcetin** [tus/tusd#261]
**Question**
Using tusd, is it possible to listen multiple paths and save them in different folders? For example, I want to have both:
-base-path /upload/images -dir ./data/images
-base-path /upload/videos -dir ./data/videos

is it possible to do it somehow?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux, macOS]
- Used tusd version: latest
- Used tusd data storage: disk store
- Used tusd configuration: as described above
- Used tus client library: tusd, uppy.js

**Comment by Acconut** [comment]
tusd does not directly support this and you would need a proxy for this. The setup looks like following: You spawn two different tusd processes listening on two different ports, storing data in two different directories, and having different base paths. A proxy is configured to route traffic towards the first or second tusd instance depending on the URL.

Alternatively you can write your own HTTP server using Go and use the tusd Go package but that would involve a look more manually work than configuring a proxy.
