### ISSUE TITLE
CORS policy issue

### ISSUE THREAD

**Issue by mihalo** [tus/tusd#262]
**Question**
I'm trying to run tusd server in AWS EC2 instance and docker. When uploading with tus-js-client I'm getting error: Access to XMLHttpRequest at 'http://xx.xxx.xx.xx:1080/files' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

I have also tested this setup on localhost with docker but no success. 

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: 
```
/srv/tusd-data # tusd -version
Version:
Commit: b1a657049e9d11d05886bb328174c7b6741eaf4f
```
- Used tusd data storage: disk store
- Used tusd configuration: Docker image default
- Used tus client library: tus-js-client v. 1.6.1

**Comment by Acconut** [comment]
As the README (see https://github.com/tus/tusd#running-tusd) says, you have to use the endpoint `http://xx.xxx.xx.xx:1080/files/` for accessing tusd with proper CORS support (notice the trailing slash, it is important). I updated the README to make this point more prominent.

**Comment by mihalo** [comment]
Thank you! Didn't notice that small mistake. Issue solved :)
