### ISSUE TITLE
[Info] Status Code: 423 "file currently locked" Using tusd manually

### ISSUE THREAD

**Issue by Demitroi** [tus/tusd#271]
Hi

I was integrating tusd with third party web framework ([gin-gonic](https://github.com/gin-gonic/gin)). On the client side i used [go-tus](https://github.com/eventials/go-tus) and [uppy](https://github.com/transloadit/uppy) in their latest versions respectively. When i intentionally disconnected the network the upload does not resume, but using the pre-built binary ([0.11.0](https://github.com/tus/tusd/releases/tag/0.11.0)) resumes successfully.

The solution: In the web framework set a timeout.
[https://github.com/gin-gonic/gin#custom-http-configuration](https://github.com/gin-gonic/gin#custom-http-configuration)

```go
func main() {
	router := gin.Default()

	s := &http.Server{
		Addr:           ":8080",
		Handler:        router,
		ReadTimeout:    30 * time.Second, // Important
		WriteTimeout:   30 * time.Second, // Important
		MaxHeaderBytes: 1 << 20,
	}
	s.ListenAndServe()
}
```
And now works perfectly using a custom authentication middleware :)

**Comment by Acconut** [comment]
Exactly, glad to read that you found a solution! The tusd binary includes it own timeout manager (see https://github.com/tus/tusd/blob/0dd8efd60637cd15b80c58cfa3b633eb425dc964/cmd/tusd/cli/listener.go#L14-L34) which isn't included if you use your own HTTP web server.

Thanks, for bringing that to our attention. We'll see if we can improve the documentation there. BTW, I would recommend using a smaller timeout if you want faster reconnection times. For master.tus.io we are currently experimenting with 6s and it working great.
