### ISSUE TITLE
Remove/Change CORS

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#272]
**Question**
How to change Origin?

**Setup details**
Access to XMLHttpRequest at 'http://server.com:1080/' from origin 'http://server.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. their is no problem if http://server.com:1080 from http://server.com:1080.

**Comment by Acconut** [comment]
This does not look like a CORS issue but you are likely using the wrong endpoint. Try using http://server.com:1080/files/ instead of http://server.com:1080 as the endpoint for your tus client.

**Comment by alameenlr** [comment]
POST http://localhost:1080/files/ 500 (Internal Server Error)
tusd.php:27 Failed because: Error: tus: unexpected response while creating upload

**Comment by alameenlr** [comment]
Error shown in Cmd
`error="s3store: unable to create multipart upload: MissingRegion: could not find region configuration"`

**Comment by alameenlr** [comment]
```
[tusd] Using 's3://temp-94955' as S3 bucket for storage.
[tusd] Using 0.00MB as maximum size.
[tusd] Using 0.0.0.0:1080 as address to listen.
[tusd] Using /files/ as the base path.
[tusd] Using /metrics as the metrics path.
[tusd] Core: ✓ Terminater: ✓ Finisher: ✓ Locker: ✓ GetReader: ✓ Concater: ✓ LengthDeferrer: ✓
[tusd] event="RequestIncoming" method="OPTIONS" path=""
[tusd] event="ResponseOutgoing" status="200" method="OPTIONS" path=""
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="ResponseOutgoing" status="500" method="POST" path="" error="s3store: unable to create multipart upload:
MissingRegion: could not find region configuration"
```
export AWS_REGION=us-east-2
export AWS_SECRET_ACCESS_KEY="SECRET_ACCESS"
export AWS_ACCESS_KEY_ID="KEY_ID"

**Comment by alameenlr** [comment]
how to
