### ISSUE TITLE
The request signature we calculated does not match the signature you provided. 

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#273]
*SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.*

`[tusd] event="ResponseOutgoing" status="500" method="POST" path="" error="s3store: unable to create multipart upload: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

The error occurred whether Large files tried to upload

**Comment by Acconut** [comment]
We can't help you if you don't fill out the questions for a bug report. Please use the template as you were prompted when creating a bug report (you can find the template here: https://github.com/tus/tusd/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by alameenlr** [comment]
s3:AbortMultipartUpload
s3:DeleteObject
s3:GetObject
s3:ListMultipartUploadParts
s3:PutObject

These are the permissions allowed.

**Comment by alameenlr** [comment]
**Describe the bug**
There is no problem with Small Size Files It Will return 100%,(~50MB) , Whether Large files tried to upload Browser Shown The `Error 500`
```
POST https://server.com/files/ 500
tusd.php:27 Failed because: Error: tus: unexpected response while creating upload
```
In Server
`[tusd] event="ResponseOutgoing" status="500" method="POST" path="" error="s3store: unable to create multipart upload: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**To Reproduce**
Steps to reproduce the behavior:
1. Execute command '...'
2. Start upload '....'
3. See error

**Expected behavior**
Same as Previous

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: n/a (not available)
- Used tusd data storage: AWS S3 (Custom Server Wasabi)
- Used tusd configuration:
   `-s3-bucket upload-store` `-s3-endpoint https://s3.eu-central-1.wasabisys.com` 
   `-max-size 1073741824` ` -timeout 0`
- Used tus client library: tus-js-client

**Comment by alameenlr** [comment]
s3:AbortMultipartUpload
s3:DeleteObject
s3:GetObject
s3:ListMultipartUploadParts
s3:PutObject

These are the permissions allowed.

**Comment by Acconut** [comment]
That looks very much like an incompatibility issue on Wasabi's side. tusd works fine with AWS S3 and Minio, and there are other problems reported in combination with Wasabi, e.g. https://github.com/shrinerb/shrine/issues/355 

Are you sure you properly setup your credentials using the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_REGION environment variables? Are you able to get it working using AWS S3 itself?

**Comment by alameenlr** [comment]
```
metadata: {
	filename: {customname[a-zA-Z0-9]}.ext
	filetype: file.tye
}
```
Solved my Problem With wasabi

**Comment by mosi-kha** [comment]
Hi
i use s3 as backend and got randomly error on `SignatureDoesNotMatch` but in the error do not mention s3store
these are the last 10 tusd's log:
`[tusd] 2022/07/25 13:06:02 event="ChunkWriteComplete" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" bytesWritten="500000" 
[tusd] 2022/07/25 13:06:02 event="ResponseOutgoing" status="204" method="PATCH" path="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" requestId="" 
[tusd] 2022/07/25 13:06:02 event="RequestIncoming" method="PATCH" path="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" requestId="" 
[tusd] 2022/07/25 13:06:02 event="ChunkWriteStart" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" maxSize="500000" offset="48500000" 
[tusd] 2022/07/25 13:06:03.960933 event="HookInvocationStart" type="post-receive" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" 
[tusd] 2022/07/25 13:06:03.969287 event="HookInvocationFinish" type="post-receive" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" 
[tusd] 2022/07/25 13:06:04.961186 event="HookInvocationStart" type="post-receive" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" 
[tusd] 2022/07/25 13:06:04.968753 event="HookInvocationFinish" type="post-receive" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" 
[tusd] 2022/07/25 13:06:35 event="ChunkWriteComplete" id="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" bytesWritten="0" 
[tusd] 2022/07/25 13:06:35 event="ResponseOutgoing" status="500" method="PATCH" path="e4cf9cf969f3d6563d0596747bb6f2a7+2~WSdh726Nr02zF1QhEgGpzWf6B9Lq1QR" error="SignatureDoesNotMatch: 
        status code: 403, request id: tx00000e18bb708b10ffb71-0062de5613-158baee2-default, host id: " requestId=""`

**Comment by Acconut** [comment]
@mosi-kha This issue has been closed for three years. Please open a new issue and include all relevant details as asked in the issue template.

**Comment by mosi-kha** [comment]
#776
