### ISSUE TITLE
It is possible to add timestamp info to tusd log?

### ISSUE THREAD

**Issue by jjrodrig** [tus/tusd#274]
**Question**

Tusd is not reporting trace timestamp in the tusd.log file. It is possible to add timestamps to log? 

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: 0.11.0
- Used tusd data storage:  disk store
- Used tusd configuration: --hooks-dir=./hooks -behind-proxy 
- Used tus client library: tus-android-client

**Comment by Acconut** [comment]
There is no option available right now to add timestamps but we would be happy to accept a PR for this. Adding this feature should be a simple change to add the corresponding flag to the following line: https://github.com/tus/tusd/blob/master/config.go#L50 (Documentation for log.New: https://golang.org/pkg/log/#New and the logging flags: https://golang.org/pkg/log/#pkg-constants)

Would you like to give this implementation a try?
