### ISSUE TITLE
How to receive session- or context-info in channel CompleteUploads?

### ISSUE THREAD

**Issue by tobias74** [tus/tusd#280]
**Question**
I have successfully  received the FileInfo in the CompleteUploads-Channel of the Handler. Now I need to know which user (session)  actually uploaded the file. The go-routine I have set up to listen on the channel "CompleteUploads" has no concept of session, since it runs outside of the request (or its middleware).

Basically I need to associate an uploaded file with information from the current session.
Is there any way to do this?

**Comment by aka-toxa** [comment]
The same question from me didn't found any clues on how to define the user

**Comment by Acconut** [comment]
It's already possible. You can add the user ID or token to the upload's metadata. This metadata is available in the FileInfo struct that is passed to the hooks where you can access the user ID and handle it in your application-specific approach.

**Comment by Acconut** [comment]
> The same question from me didn't found any clues on how to define the user

I'm sorry to read that. We know that this information is not as easily discoverable as we would like to but our resources are limited. We have plans to improve the documentation but this is a process that takes time. Of course, your help is always appreciated if you can.

**Comment by aka-toxa** [comment]
I'm not sure that it's a good approach, because of user session info shouldn't be a part of any FileInfo and anyway, in existing systems, that approach will cause some hacks (exceptions in front-ends for file upload)

maybe it worth to extend functions signature in DataStore interface and pass HTTP headers map inside each DataStore method? 

I can prepare PR

**Comment by aka-toxa** [comment]
actually, I found the workaround you no one want to patch their front-ends

```golang
func PrepareUserSessionInfo(r *http.Request) {
    sessionID := r.Header.Get("X-SESSION-ID")
    uploadMetadata := r.Header.Get("Upload-Metadata")
    uploadMetadata += ",session " + base64.StdEncoding.EncodeToString([]byte(sessionID))
    r.Header.Set("Upload-Metadata", uploadMetadata)
}

mux.Handle("/files/", func(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        PrepareUserSessionInfo(r)
        next.ServeHTTP(w, r)
    })
}(http.StripPrefix("/files/", tusHandler)))
```

**Comment by Acconut** [comment]
> maybe it worth to extend functions signature in DataStore interface and pass HTTP headers map inside each DataStore method?

Thank you for your offer, but I don't think this is a great idea. There were attempts to implement exactly this (e.g. #278) but passing the HTTP request to the DataStore is semantically not correct, so we decided against this solution. There are plans to add this feature in the next major release of tusd (see #212) and we are currently working on this.

**Comment by aka-toxa** [comment]
agreed that was semantically not correct at all

we can use `context` for that:

```golang
func (store *MyDataStore) NewUpload(context context.Context, info tusd.FileInfo) (id string, err error) {
	user := context.Value("user")
        ....
}

func (store *MyDataStore) WriteChunk(context context.Context, id string, offset int64, src io.Reader) (int64, error) {
	...
}
```

and provide the ability to configure keys in context object in "create handler" configuration

```golang
contextComposer := func (r *http.Request) context.Context {
   ...
}
...
handler, err := tusd.NewHandler(tusd.Config{
    BasePath:      uploadBasePath,
    StoreComposer: composer,
    ContextComposer: contextComposer
})
```

or something like that


it will also give us the ability to manage requests to other backends with passed context

**Comment by aka-toxa** [comment]
I think it's a proper approach because all HTTP stuff is handled on "HTTP layer" 

and DataStore will handle only ready for use context which is very useful in order to control timeouts/cancels/any context-related data

**Comment by Acconut** [comment]
Frankly, I am not a fan of using context for this, instead the current plan would be to pass the request information not to the DataStore at all but provide it to the hooks using a special HookEvent struct, as proposed in https://github.com/tus/tusd/pull/278#issuecomment-498060546.

Is there a specific reason why you need the HTTP request information inside the DataStore and not the hooks?

**Comment by aka-toxa** [comment]
as for me and my project requirements, it would be enough to just have a HTTP request info inside the hook actually.

But I don't feel very confident with that because in the case when upload-service is scaled and the client makes, for example, upload with the concatenation extension in parallel on different nodes, which request's information will be passed to complete hook?

Or what if client started upload, then paused it, then resumed. Which headers will be passed to the hook? How can I make sure that "resume" was initiated with valid session of valid user? 

how we will secure PATCH requests? I mean how I can make sure that every call was performed from the same valid user?

**Comment by Acconut** [comment]
I am not sure whether we are talking about the same thing. When I say "passing HTTP request to the hook", I refer to the HTTP request that directly caused the hook to be executed. So the post-receive hook gets the corresponding PATCH request, the pre-create/post-create hook gets the corresponding POST request and the post-terminate hook gets the corresponding DELETE request. Maybe that's more clear when I answer your questions:

> for example, upload with the concatenation extension in parallel on different nodes, which request's information will be passed to complete hook?

When you use the concatenation extension, there will be one POST request that tells the server to stitch a provided list of uploads together. This POST request will then be passed to the post-finish hook.

> Or what if client started upload, then paused it, then resumed. Which headers will be passed to the hook?

The request information about the second PATCH request will be passed to the hook.

> how we will secure PATCH requests? I mean how I can make sure that every call was performed from the same valid user?

That's out of tusd's scope. You can do basic authentication during the pre-create hook but if you want to ensure that the upload is also continued by the same user, you have to use a proxy or Go wrapper around tusd to check every request. This may involve more work for you but tusd is focused on uploads and not on handling authentication.

**Comment by tobias74** [comment]
> You can add the user ID or token to the upload's metadata.

That would be sufficient for me! I know how to access the Metadata from within the hook, but I am unsure how to attach the userId to the Metadata.

I create the handler like this:

`handler, err := tusd.NewHandler(tusd.Config{
		BasePath:      "/files/",
		StoreComposer: composer,
	})`

Then I let it be handled on a certain route:

`http.Handle("/files/", http.StripPrefix("/files/", handler))`


Now my question is: how do I get in there? Do I need to wrap the tusd.NewHandler with some middleware?

**Comment by Acconut** [comment]
@tobias74 You can either use @aka-toxa workaround for injecting the user ID (https://github.com/tus/tusd/issues/280#issuecomment-501402777) or set the metadata from your tus client. The exact procedures for that depend on what tus client you are using.

**Comment by Acconut** [comment]
The hooks and channels (such as CompleteUploads) since tusd v1.0.0 now also contain information about the HTTP request. Therefore, this issue has been solved, I guess.
