### ISSUE TITLE
Error 400 "missing or invalid Upload-Length header" on deferred upload

### ISSUE THREAD

**Issue by dmanchon** [tus/tusd#283]
**Describe the bug**
I am trying a defer length upload. While the final size still unknown i set the header `Upload-Defer-Length:1`, once i know the actual size that header is substituted by `Upload-Length:{size}` in the next patch request

**To Reproduce**

```
~ » curl -I -XPOST -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  http://localhost:1080/files/
HTTP/1.1 201 Created
Location: http://localhost:1080/files/563b16ebc184b1e00cf43fb79d5d6164
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
Date: Thu, 20 Jun 2019 19:23:01 GMT
Content-Length: 0

~ » curl -i -XPATCH -H "Upload-Offset:0" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  http://localhost:1080/files/563b16ebc184b1e00cf43fb79d5d6164 -d 'XXXXX'
HTTP/1.1 204 No Content
Tus-Resumable: 1.0.0
Upload-Offset: 5
X-Content-Type-Options: nosniff
Date: Thu, 20 Jun 2019 19:23:55 GMT

~ » curl -i -XPATCH -H "Upload-Offset:5" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  http://localhost:1080/files/563b16ebc184b1e00cf43fb79d5d6164 -d 'XXXXX'
HTTP/1.1 204 No Content
Tus-Resumable: 1.0.0
Upload-Offset: 10
X-Content-Type-Options: nosniff
Date: Thu, 20 Jun 2019 19:24:05 GMT

~ » curl -i -XPATCH -H "Upload-Offset:10" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Length:20"  http://localhost:1080/files/563b16ebc184b1e00cf43fb79d5d6164 -d 'XXXXXYYYYY'
HTTP/1.1 400 Bad Request
Content-Length: 40
Content-Type: text/plain; charset=utf-8
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
Date: Thu, 20 Jun 2019 19:25:46 GMT

missing or invalid Upload-Length header

```

**Expected behavior**
Once the length is known and the header 'Upload-Length' is defined the server should accept it. According to the protocol documentation:

> Once it is known the Client MUST set the Upload-Length header in the next PATCH request

I think that this condition https://github.com/tus/tusd/blob/a6ebba689fc02d63735d81bc041b84dcbd37c7c4/unrouted_handler.go#L476 might be wrong, according to the protocol the condition is that the two headers shouldnt be set at the same time.

**Setup details**
- Operating System: macOS
- Used tusd version: master branch
- Used tusd data storage: file
- Used tusd configuration: `tusd` without args
- Used tus client library: custom client and also manually with curl

**Comment by Acconut** [comment]
Thank you very much for providing the details instructions. However, I am not able to reproduce this problem on my machine. I also tried replicating it using a script but that also worked without problems. Can you try running following bash script to see if that works for you or if it also returns the 400 error? 

```sh
#!/bin/sh

set -e
set -x

uploadUrl="$(curl -I -XPOST -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  http://localhost:1080/files/ | grep Location | tr -d '\r' | cut -d' ' -f 2)"

curl -i -XPATCH -H "Upload-Offset:0" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:5" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:10" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Length:20"  $uploadUrl -d 'XXXXXYYYYY'
```

Also, you don't need to supply the Upload-Defer-Length header in PATCH requests. You only have to specify it in the initial POST request. After that it's enough to add the Upload-Length header once when you now the final size.

**Comment by dmanchon** [comment]
thanks @Acconut, the script works, i am sorry since i confused the curl commands that i pasted , those worked fine, the problem happened if the header `Upload-Lenght` is present in more than one chunk (not just the last),  like this:

```
#!/bin/sh

set -e
set -x

uploadUrl="$(curl -I -XPOST -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  http://localhost:1080/files/ | grep Location | tr -d '\r' | cut -d' ' -f 2)"

curl -i -XPATCH -H "Upload-Offset:0" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:5" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:10" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Defer-Length:1"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:15" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Length:25"  $uploadUrl -d 'XXXXX'

curl -i -XPATCH -H "Upload-Offset:20" -H "Content-Type:application/offset+octet-stream" -H "Tus-Resumable:1.0.0" -H "Upload-Length:25"  $uploadUrl -d 'XXXXX'
```
I am unsure is that is part of the standard, or once you know the actual lenght every remaining bytes should be send within that chunk.

**Comment by Acconut** [comment]
Thanks for clarifying. Yes, that is the intended behavior. When using tusd, the Upload-Length header must only be set in one PATCH request. The specification says following about it:

> [The POST request must contain] Upload-Defer-Length: 1 if upload size is not known at the time. Once it is known the Client MUST set the Upload-Length header in the next PATCH request. Once set the length MUST NOT be changed.

For tusd we interpreted "Once set the length MUST NOT be changed" as if the Upload-Length header must only be in one PATCH request, although it might be valid to supply the Upload-Length header multiple times with the same value (as you did).

Anyways, you can remove the Upload-Defer-Length and Upload-Length headers for all but one PATCH requests and you should be fine.

**Comment by dmanchon** [comment]
I see, thanks for the clarification!! If this is intentional then ill close the issue.
Thanks again.
