### ISSUE TITLE
tusd over https

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#285]
**Question**
How can I access tusd using HTTPS?

**Setup details**
Apache2 Server,
I didn't found any solution for this case,
tus.min.js:1 Mixed Content: The page at 'https://www.myserver.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.myserver.com/files/5ebac0ae4a630a70b54c0204523a49cf+75npEEsAhbvUiKv3He40s3mR3LvJid9BBxoe3yPbccoS63-HfVVaTAieeekgoDLlj8YtOyS1CSQvL0rIuD86rUXRAeUzyop7OT_eF0NL5899QfQBRMP4PcFWscf1RE_4'. This request has been blocked; the content must be served over HTTPS.

**Comment by Acconut** [comment]
Did you read the FAQ entry about running tusd with HTTPS? https://github.com/tus/tusd#how-can-i-access-tusd-using-https

**Comment by alameenlr** [comment]
Sorry I didn't Read the [Can I run tusd behind a reverse proxy?](https://github.com/tus/tusd#can-i-run-tusd-behind-a-reverse-proxy)..
Solved My problem Thanks for Your Support

**Comment by Acconut** [comment]
You're welcome!
