### ISSUE TITLE
tusd binary file not created

### ISSUE THREAD

**Issue by Mr-viv1gupta** [tus/tusd#287]
**Question**
tusd binary file not created on command "go build -o tusd cmd/tusd/main.go" ?

Checked go/bin folder tusd binary file dont exist.

**Setup details**
- Operating System: Windows
- Used tusd data storage: disk store [localhost]
- Go version : go version go1.12.6 windows/amd64

**All other commands of setup **
go get -u github.com/aws/aws-sdk-go/...
go get -u github.com/prometheus/client_golang/prometheus
**runs successful**

**On running "go run /cmd/tusd/main.go"**
![image](https://user-images.githubusercontent.com/26483180/60081547-9df80b00-974f-11e9-818f-59bff1747ec4.png)

** On running "go build -o tusd cmd/tusd/main.go"**
![image](https://user-images.githubusercontent.com/26483180/60081914-69d11a00-9750-11e9-97bf-3cff6f893c24.png)

**Comment by Acconut** [comment]
> Checked go/bin folder tusd binary file dont exist.

The command you are using does not place the binary inside `$GOPATH/bin`. It places the generated tusd binary in your current directory. You should be able to find it at `./tusd`.

**Comment by Mr-viv1gupta** [comment]
Thanks. Solved
