### ISSUE TITLE
Support context for datastore interfaces

### ISSUE THREAD

**Issue by rickypai** [tus/tusd#288]
**Is your feature request related to a problem? Please describe.**

The current upload interfaces does not support `context.Context`. For example, in the `DataStore` interface, the methods do not take context into account:

https://github.com/tus/tusd/blob/d23be46d7a236714c451601f87fe6bbab7776d45/datastore.go#L47-L52

What this means is we're not able to propagate things like request cancellation into the datastore. It seems useful to support this as context has become one of the standard concurrency patterns in golang.

**Describe the solution you'd like**

For interface methods and their implementations, instead of:

```golang
type DataStore interface { 
 	NewUpload(info FileInfo) (id string, err error) 
}
```

```golang
type DataStore interface { 
 	NewUpload(ctx context.Context, info FileInfo) (id string, err error) 
}
```

This would mean breaking existing APIs. If we're ok with this (might be ok since it's only internal API), this can be handled in the release notes. For example, another SDK (Firebase Admin SDK), made an API-breaking release just for supporting context: https://github.com/firebase/firebase-admin-go/releases/tag/v3.0.0

**Describe alternatives you've considered**

To make the API more backwards compatible, one might add context-aware interfaces alongside with existing interfaces:

```golang
type DataStore interface { 
 	NewUpload(info FileInfo) (id string, err error) 
}

type ContextAwareDataStore interface { 
 	NewUpload(ctx context.Context, info FileInfo) (id string, err error) 
}
```

But that might end up with more confusion.

The consumer could also make their own custom context-aware wrapper, but it'd be nicer if it were supported by the official implementation.

**Can you provide help with implementing this feature?**

Yes

**Additional context**

None

**Comment by Acconut** [comment]
That's a good idea, thanks for bringing it up. Unfortuately, the DataStore API is not internal but public, so we cannot change it would a breaking API change. Implementing a context-aware interface looks like a high cost for little benefit.

Instead, I think this is a good candidate for the next major release of tusd where we are making multiple breaking changes. We currently have collected a list of ideas in #212 and already started implementing a few of them. I added your proposal to this list.

**Comment by rickypai** [comment]
Thanks a lot for the quick reply. I think making it as part of v1 makes sense.

**Comment by Acconut** [comment]
Perfect, I will leave this issue open as a reminder until the feature has been implemented in v1.
