### ISSUE TITLE
Is it possible to have a parameterizable URL?

### ISSUE THREAD

**Issue by enflo** [tus/tusd#293]
**Question**
Is it possible to use a path that allows to indicate the directory where the images should be saved?
In our case we are interested in something similar to /files/ID/ where the ID indicates the directory where the image is saved.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux-Docker
- Used tusd version: latest
- Used tusd data storage: Google Cloud Storage
- Used tusd configuration: -gcs-bucket GCS-NAME
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
There is currently no feature to let the client directly specify the destination directory for the uploads. However, there are two methods for achieving this on your own:

1. Start multiple tusd servers pointing to different destinations. While this is a bit hacky, it's the easiest and quickest way if you have a limited set of folders.
2. Use the post-finish hook (https://github.com/tus/tusd/blob/master/docs/hooks.md) to move the completed file into the desired folder, based on the upload's metadata. The client can then specify the upload destination in the metadata.

**Comment by enflo** [comment]
Thank you for your reply
