### ISSUE TITLE
Update cloud.google dependencies

### ISSUE THREAD

**Issue by kkwak** [tus/tusd#298]
The cloud.google dependencies are very old and some features are not enabled (namely cloud kms for bring-your-own-key buckets).

I tried to update, but there were loads of transitive dependency changes, so I'm not very sure about it. Would be great if someone who knew the codebase could take a look.

Thanks.

**Comment by Acconut** [comment]
Did you try using govendor (https://github.com/kardianos/govendor)? That's the tool we are using for dependency management. We are in the process of moving to Go modules (see #212) but that is likely going to take some more time.

**Comment by kkwak** [comment]
Sorry for the late reply. Wow that's a big list of TODOs!

I've got a fairly restricted environment and govendor wouldn't work for me.
I switched to go mod and set the GOPROXY and it's working fine (for my very simple use-case). All existing tests pass as well.

Also updated the google libs only to find out that it's still an unimplemented feature.
For anyone on GCS, Buckets using CMEK (custom managed encryption keys) is (1) slow (2) ComposeFrom doesn't work. They may never fix (but no earlier than 2020 Q1 if ever).

For my use-case I patched tusd to use Copier instead of Composer if there is only one chunk. Would anyone be interested in a PR for that? It's a minor change.

**Comment by Acconut** [comment]
> Also updated the google libs only to find out that it's still an unimplemented feature.
For anyone on GCS, Buckets using CMEK (custom managed encryption keys) is (1) slow (2) ComposeFrom doesn't work. They may never fix (but no earlier than 2020 Q1 if ever).

That's good to know. So is upgrading the Google Cloud SDK of no benefit right now?

> For my use-case I patched tusd to use Copier instead of Composer if there is only one chunk. Would anyone be interested in a PR for that? It's a minor change.

If there is a benefit, we would be very interested in a PR! Does it improve performance or what is the reason for this change? Sorry for the question but I am not too experienced with GCS.

**Comment by kkwak** [comment]
Correct. No real benefit for my particular scenario - CMEK.
In fact, the PR is not required, as the Copier takes just as long to upload and causes performance to drop by half. For the time being, we decided to just wrap gsutil as it works well enough for us. Thank you for the feedback and such.

**Comment by Acconut** [comment]
You're welcome! Thank you for your efforts!
