### ISSUE TITLE
Add an event driven hook implementation

### ISSUE THREAD

**Issue by sagikazarmark** [tus/tusd#305]
**Is your feature request related to a problem? Please describe.**
I would like to react to events happening inside Tus, without having to rely on delivery guarantees provided by Tus. For example, I want to display uploads and progress to other users in the system.

**Describe the solution you'd like**
Tus currently can send hooks to a process or an HTTP, but in a distributed system that's often not enough (process) or does not provide enough guarantees (HTTP). Looking at the hooks, they can easily be considered as events (UploadCreated, etc) which would be perfect for post-processing (display progress, auto-cancel certain uploads, etc). Using whatever message queue in the background would provide much better guarantees than the current solutions.

**Describe alternatives you've considered**
The alternative is an HTTP implementation that sends events to a message queue, which might fit tusd better, since it's a reference implementation, but does not address the delivery guarantee concerns.

**Can you provide help with implementing this feature?**
Sure, I'd love to.

**Additional context**
[Watermill](https://github.com/ThreeDotsLabs/watermill) is a great generic messaging library.

**Comment by Acconut** [comment]
Thank you very much for this interesting proposal. I am still having a hard time understanding what you are missing from the process and HTTP hooks.

Why are processes "often not enough"? What delivery guarantees are you missing from the HTTP hooks? They provide retries with exponential backoff IRC.

**Comment by sagikazarmark** [comment]
IMHO using the process hook is not a viable option in a distributed system. I want to run and scale tusd instances independently from hooks.

As for delivery guarantees: in case the HTTP hook is processed asynchronously (probably by using a message queue), it's probably fine, that's why I suggested it as an alternative.

A synchronously processed hook however is prone to a large number of errors:

- eventually the backoff will exceed the limit (eg. a service is down). A message however can sit in a queue forever
- Retry is an active resiliency measurement, tusd actually has to keep retrying. A message sitting in the queue doesn't require such responsibility.
- Bugs in a synchronous hook processor cannot be mitigated easily, while messages can be replayed

Obviously, the connection between tusd and a message queue must also be resilient enough (so retries and backoff are probably necessary there as well), but from that point tusd is no longer responsible for delivering the hook which puts it a far more limited responsibility on it.

As I said, a simple HTTP proxy between a message queue and tusd can also work, but I thought it would be interesting to have this feature in tusd. But on second thought, I think this "proxy" is actually a better idea. That way tusd does not have to be aware of all the MQ protocols in the world.

**Comment by Acconut** [comment]
Yes, I agree that a HTTP proxy is likely the best option in this case! Watermill seems to be an amazing project but it would also be a heavy dependency for tusd which comes with its own downsides (we already have to deal with the AWS and Google Cloud SDKs enough :) ).

**Comment by Acconut** [comment]
Closing this issue since we agreed that this should not be part of the tusd core.
