### ISSUE TITLE
add OpenTelemetry support for Observability

### ISSUE THREAD

**Issue by inigohu** [tus/tusd#310]
**Is your feature request related to a problem? Please describe.**
Add standard tool for observability tool to support diffent backends.

**Describe the solution you'd like**
[OpenTelemetry](https://opentelemetry.io/) provides a single set of APIs to capture distributed traces and metrics from the application. 
You can export those traces and metrics to a [collector](https://github.com/open-telemetry/opentelemetry-collector) and be agnostic of different backends like Prometheus, Jaeger, and other observability tools.
The start point would be to instrument the [HTTP server](https://github.com/open-telemetry/opentelemetry-go) and then propagate that instrumentation to the HTTP hooks.

**Describe alternatives you've considered**
[Opencensus](https://opencensus.io/) is in a more stable version and is compatible with OpenTelemetry.

**Can you provide help with implementing this feature?**
I can prepare a PR

**Additional context**
I think that instead of giving support to multiple observability backends, project like this, should use solutions like OpenTelemetry.

**Comment by Acconut** [comment]
tusd currently exposes metrics in the Prometheus format as explained in https://github.com/tus/tusd/blob/master/docs/monitoring.md. What would the benefit of OpenTelemetry or OpenCensus be? In my experience a lot of tools understand the Prometheus format.

**Comment by inigohu** [comment]
Yes, you are right, but with OpenTelemetry you can export metrics to different backends, not just to Prometheus.

Te biggest advantage is that OpenTelemetry also supports traces (and logs in the future). I would like to create and propagate traces through **tusd** server and hooks. This way, I will have more visibility of my entire workflow.

In other words, it will give a more powerful observability tool.

**Comment by Acconut** [comment]
> Yes, you are right, but with OpenTelemetry you can export metrics to different backends, not just to Prometheus.

If I understand correctly, OpenTelemetry is also able to pull in data using the Prometheus format, isn't it? At least that's how I understand https://github.com/open-telemetry/opentelemetry-collector.

Another point is that OpenTelemetry is not stable, right? According to https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md it is still going to take a few months and I would like to avoid have to adapt to the changes in half a year again.

**Comment by inigohu** [comment]
> If I understand correctly, OpenTelemetry is also able to pull in data using the Prometheus format, isn't it? At least that's how I understand https://github.com/open-telemetry/opentelemetry-collector.

Opentelemetry-collector is the service that would receive metrics/traces from different aplications. You can export metrics to Prometheus directly or export to a opentelemetry-collector and from there to Prometheus. My proposar is:

1. Instrument **tusd** server with [ochttp server plugin](https://opencensus.io/guides/http/go/net_http/server/). 
2. Add [ocagent exporter](https://opencensus.io/exporters/supported-exporters/go/ocagent/) to send metrics/traces to [opencensus-service](https://github.com/census-instrumentation/opencensus-service) or [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector)
3. Instrument **hooks** with [ochttp client](https://opencensus.io/guides/http/go/net_http/client/) 

> Another point is that OpenTelemetry is not stable, right? According to https://github.com/open-telemetry/opentelemetry-specification/blob/master/milestones.md it is still going to take a few months and I would like to avoid have to adapt to the changes in half a year again.

OpenTelemetry is the merger of OpenTracing and Opencensus. Now it's still in development and it's risky to use it in production, but you can use opencensus and in the future, upgrade it to opentelemetry.
Opencensus is compatible with opentelemetry. You can use applications instrumented with opencensus along with the opentelemetry-collector.

**Comment by kvz** [comment]
To me this sounds like quite an undertaking when the primary mentioned metric target is still prometheus, and most other frameworks have prometheus-compatible aggregators available. Adding to this that I'd never heard of OT or OC (could totally be my fault!), and that they're currently undergoing some organizational shift, it's not so very attractive to me to build/maintain this?

**Comment by inigohu** [comment]
> Adding to this that I'd never heard of OT or OC (could totally be my fault!)

OpenTelemetry is a [Cloud Native Computing Foundation sandbox project](https://www.cncf.io/sandbox-projects/)

**Comment by kvz** [comment]
Ah thanks, that helps a lot! I think for a project like tusd, i makes sense for it to leave the sandbox stage and then we can reconsider, what do you think?

**Comment by inigohu** [comment]
> Ah thanks, that helps a lot! I think for a project like tusd, i makes sense for it to leave the sandbox stage and then we can reconsider, what do you think?

I agree. 
I think that could be interesting to add some observability tools like opentelemetry to ### tusd in the future. Thanks for considering it.

**Comment by Acconut** [comment]
Thanks for bringing this up, @inigohu, but I agree with @kvz that its not beneficial for tusd to pull in OpenCensus just to change it to OpenTelemetry after a few months. That being said, I am always open to add more metrics and instrumentation to tusd, preferably with the current setup.

**Comment by pcfreak30** [comment]
@Acconut Sorry to grave dig this issue, however I am in the processing of wiring up my software with a ton of observability, and found this issue.

The current status quo now seems to be, use prometheus for metrics, and OTEL for spans and logs. I am adding in both systems based on my own research of what seems to meet my requirements.

What your opinion on supporting the OTEL (opentelemetry) framework on tusd? Would you require a PR or able to prioritize this at all?

**Comment by pcfreak30** [comment]
> [@pcfreak30](https://github.com/pcfreak30) Can you briefly describe what changes (code changes, new logic, additional CLI flags) are necessary to support OpenTelemetry?

OTEL is context based. You would need to do something like https://github.com/LumeWeb/portal/blob/d41c2432580cbcf0e2b4616c727344ec08e6c0d9/service/auth.go#L51.

Granted, I created a very light wrapper for my projects framework, but the core of it is.

`span:= otel.Tracer("X").Start(ctx, name, opts...)` `span.End()`.

The OTEL config is setup as global singletons, so as long as its configured before a call is made the data gets collected IIRC. https://github.com/LumeWeb/portal/blob/d41c2432580cbcf0e2b4616c727344ec08e6c0d9/core/otel_setup.go#L30 is an example, though fairly specific to my stuff.

You need to spans on everything you want to wire, including any attributes/meta you want to add, and they all must be methods with a context. This can definitely be automated as well. I forked a tool that does AST processing for my needs, but the crux is you have to do the same on every method, and could improve the reporting from that point on.

**Comment by pcfreak30** [comment]
> I see. Adding the code to record spans seems doable and shouldn't be a problem. We then tusd would also have to support different exporters, wouldn't it? You seem to be using Uptrace in your example, but that would likely not be helpful for the majority of users, would it? Do you have an idea what exports tusd should support?

uptrace is a very light abstraction to the std sdk. See https://github.com/uptrace/uptrace-go/blob/master/uptrace/uptrace.go#L24.

Basically all interfaces are defined by the `go.opentelemetry.io/otel` library. Realistically, `tusd` should only need to support the framework, and put everything else out of scope as part of `otel` configuration and effectively the users problem. `tusd` only needs the traces added in really, nothing more. If traces run with no config, AFAIK its a no-op.

Its not that different from the prom config where you define the metrics then record the bean counter and leave it to the user to wire it to their registry object(s). I do that here for ex https://github.com/LumeWeb/portal/blob/511956f3383f5da042a83ad6e5be73a61951b776/service/internal/tus/tus.go#L342.

Thoughts?

**Comment by Acconut** [comment]
That works for people using tusd as a library. Can we also bring that function to users of the tusd binary? We could add a CLI flag to export traces to the OLTP collector, which seems to be a vendor-agnostic interface: https://opentelemetry.io/docs/collector/

**Comment by pcfreak30** [comment]
> That works for people using tusd as a library. Can we also bring that function to users of the tusd binary? We could add a CLI flag to export traces to the OLTP collector, which seems to be a vendor-agnostic interface: https://opentelemetry.io/docs/collector/

You can, though then you have to decide if you want the uptrace abstraction or not. personally, I started with the std, but found the DSN abstraction they created very useful and was using a local uptrace instance, so 🤷 .

You would have to figure out in the binary what to support.
