### ISSUE TITLE
tusd responses for errors from http hooks are always text/plain

### ISSUE THREAD

**Issue by dantman** [tus/tusd#314]
**Is your feature request related to a problem? Please describe.**
I have a HTTP hook, when I return a 400 error the upload is rejected and the content is passed back.

However while my API server returns JSON error responses and I'm pretty sure includes the correct content-type header, the errors that are passed back through tusd are text/plain.

Here's an example HTTP response from tusd:
```http
HTTP/1.1 400 Bad Request
Content-Length: 67
Content-Type: text/plain; charset=utf-8
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
Date: Wed, 09 Oct 2019 23:12:41 GMT
Connection: close

{"statusCode":400,"error":"Bad Request","message":"jwt malformed"}
```

**Describe the solution you'd like**
I think the Content-Type from a HTTP hook should be passed along like the body and status code is.

**Can you provide help with implementing this feature?**
For now I may workaround the limitation instead, I haven't even finished my uploader implementation yet.

**Comment by Acconut** [comment]
That's true, current the response headers from HTTP hocks are not interpreted or even passed to the client. We would be happy to accept a PR for this if you have the time.

**Comment by gajus** [comment]
It would be useful to have "limitations" section in README.md. There are tons of loose ends.

**Comment by Acconut** [comment]
@gajus If you want to help us improve tusd, we are also happy to assist with PRs.

**Comment by Acconut** [comment]
The v2 release will contain features to fully customize the response, including headers: #672
