### ISSUE TITLE
Official s3 storage plugin

### ISSUE THREAD

**Issue by nodesocket** [tus/tusd#32]
Would be awesome to get an officially maintained s3 storage plug using `tusd.DataStore`.

**Comment by kvz** [comment]
+1

**Comment by Acconut** [comment]
A backend for S3 is also in our interest, so you can expect an official storage module from our side pretty soon.

**Comment by redaready** [comment]
+1 
and https://github.com/minio/minio

**Comment by Acconut** [comment]
@redaready I am planning to finish the S3 storage this week. Mostly tests and documentation is missing at the moment. Minio looks as an interesting alternative to Riak CS, and particularly their Go SDK is a more lightweight alternative to AWS' official one.

**Comment by liamdon** [comment]
Hey @Acconut, any update? I was going to start an s3 storage plugin as it's a blocker for us to use tus, but I don't want to duplicate work. If you have an early version that you can push I would be happy to contribute.

**Comment by liamdon** [comment]
My bad, I see that it was checked in 10 days ago! Awesome :smile:

**Comment by Acconut** [comment]
@liamdon Haha, no problem. :) Brushing up the README with some more information is already on my todo list.
