### ISSUE TITLE
How to get metadata in pre-create hook using node

### ISSUE THREAD

**Issue by coconut097** [tus/tusd#323]
I am trying get the metadata of the file using some javascript code, but the "process.stdin.read()" always return null to me. However, the stdin did return correct info when i using bash to do it. What is the proper way to get the metadata in hook by using JavaScript? Below is the code in my pre-create:

```
#!/usr/bin/env node

var data = process.stdin.read();

if(data == null)
{
    console.log('Cannot get data');
    process.exit(1);
}
```

**Setup details**
- Operating System: Linux
- Used node version: v8.16.2
- Used tusd data storage: disk store
- Used tusd configuration: tusd --hooks-dir ./tusd-hooks
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
You're Node.js code is incorrect. `process.stdin` is a readable stream, so you have to wait until the data is available using events. Something like this should work:

```js
let data = '';
process.stdin.on('data', (buffer) => {
  data += buffer.toString('utf8');
});
process.stdin.on('end', () => {
  console.log("Hook info", data);
}
```

I recommend you to read and learn about Streams since that is a very basic and core principle of Node.js.

**Comment by coconut097** [comment]
Its work, thanks for your guidance. i will learn more about the basics.
