### ISSUE TITLE
Impossible to use "/" as base-path

### ISSUE THREAD

**Issue by misiek08** [tus/tusd#325]
**Describe the bug**
It's impossible to set "/" as base path.
Probably it's cause by stripping prefix/suffix while preparing path for handler and it ends up as empty string, which is illegal in Go: https://golang.org/src/net/http/server.go?s=73935:73995#L2396

**To Reproduce**
1. Execute command '/usr/local/bin/tusd -base-path /'
2. See error

**Expected behavior**
tusd should start without any errors and serve traffic

**Setup details**
- Operating System: Linux, Ubuntu
- Used tusd version:
```Version: v1.0.1
Commit: 57be489b8bf8ee1231e549876388740946fc3df3
Date: Sun Sep 29 18:38:02 UTC 2019```
- Used tusd data storage: disk, but doesn't matter
- Used tusd configuration: -base-path /
- Used tus client library: doesn't matter, tusd won't start

**Comment by Acconut** [comment]
Thank you very much for reporting, this should be fixed now in the master branch.
