### ISSUE TITLE
how to upload by directing the path in S3 storage

### ISSUE THREAD

**Issue by arck123** [tus/tusd#327]
how to upload by directing the path in S3 storage ?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: lastest
- Used tusd data storage: Minio S3
- Used tusd configuration: 
- Used tus client library: tus-js-client

**Comment by arck123** [comment]
![tes2](https://user-images.githubusercontent.com/18304433/69144849-43fb3780-0a9a-11ea-8160-28ddeadc4fa9.png)

i want upload to folder /videos .. not copy folder parent to folder child , but when uploaded directly to folder /videos

my config
		s3Config := &aws.Config{
			Credentials:      credentials.NewStaticCredentials(config.AccessKeyID, config.SecretAccessKey, ""),
			Endpoint:         aws.String(config.Endpoint),
			Region:           aws.String(config.Location),
			DisableSSL:       aws.Bool(true),
			S3ForcePathStyle: aws.Bool(true),
		}

thanks

**Comment by Acconut** [comment]
Use the ObjectPrefix property of the S3Store struct: https://godoc.org/github.com/tus/tusd/pkg/s3store#S3Store

**Comment by arck123** [comment]
> Use the ObjectPrefix property of the S3Store struct: https://godoc.org/github.com/tus/tusd/pkg/s3store#S3Store

i'm implementation store.ObjectPrefix work ...

thankss

**Comment by Acconut** [comment]
Great!
