### ISSUE TITLE
How to implement finishUpload tus v1.xx ?

### ISSUE THREAD

**Issue by arck123** [tus/tusd#328]
i ask again ..
old part my source not work and mesasge error
./router.go:608:25: undefined: handler.FinisherDataStore
./router.go:611:11: composer.UseFinisher undefined (type *handler.StoreComposer has no field or method UseFinisher)

tusd v0.xxx work this code
tusd v1.xxx not work this code

code router
var finisherDataStore tusd.FinisherDataStore = controllers.FinisherDataStore{
Store: store,
}
composer.UseFinisher(finisherDataStore)

code controller
func (finisherDataStore FinisherDataStore) FinishUpload(id string) error {
xxx
xx
}

**Setup details**
Please provide following details, if applicable to your situation:
Operating System: Linux
Used tusd version: new version
Used tusd data storage: Minio S3
Used tusd configuration:
Used tus client library: tus-js-client

**Comment by arck123** [comment]
your solution:
Yes, that's expected. The UseFinisher function does not exist anymore. You should read the release notes for the reasoning behind it: https://github.com/tus/tusd/releases/tag/v1.0.0. TLDR: It's not needed anymore.

but i have not idea to implement finishUpload tus v1.xx
do you have example implement finishupload in controller ? and  what change composer.UseFinisher(finisherDataStore) ?

thanks

**Comment by arck123** [comment]
i should implementation HTTP hooks ?
do you have example code implementation finishupload/HTTP hooks ?

thanks

**Comment by Acconut** [comment]
Have a look at this example to see how to listen for complete uploads when using tusd as a *package*: https://github.com/tus/tusd/blob/master/examples/server/main.go

The tusd *package* does not provide HTTP hooks, that's only available when using the tusd *binary*.

**Comment by arck123** [comment]
how to call functon in controller ?  i want run event in function finishUpload after complete upload

go func() {
 for {
	event := <-handler.CompleteUploads
 }
}()

**Comment by Acconut** [comment]
What do you want to do inside FinishUpload? Please explain, so we can find a solution for you. It is meant for people implementing their own DataStores (e.g. against another cloud provider). If you only want to react to finished uploads, you should not use FinishUpload anymore, and instead rely on the CompleteUploads channel as in the example.

**Comment by arck123** [comment]
i want implementation inside FinishUpload
- Update video data to database
- Move to real temporary video file before transcoding process

update video data and Move to real temporary video file before transcoding process already working in tusd v0.xx but not working in tusd1.xx because i'cant call 
func (finisherDataStore FinisherDataStore) FinishUpload(id string) error {
"COLUMN_CREATE('format', '" + inputFormat + "', " +
xxxx
xxxx
}

- tusd 0.xx func (finisherDataStore FinisherDataStore) FinishUpload(id string) error { ... } and useFinisher ==> working
- tusd 1xx func (finisherDataStore FinisherDataStore) FinishUpload(id string) error { ... } and useFinisher ==> not working

**Comment by arck123** [comment]
do you have example call event after complete upload ?

thanks

**Comment by Acconut** [comment]
> do you have example call event after complete upload in tusdv1.xx ?

Yes, it's the same example as above: https://github.com/tus/tusd/blob/master/examples/server/main.go

```go
	// Start another goroutine for receiving events from the handler whenever
	// an upload is completed. The event will contains details about the upload
	// itself and the relevant HTTP request.
	go func() {
		for {
			event := <-handler.CompleteUploads
			fmt.Printf("Upload %s finished\n", event.Upload.ID)

			// HERE goes your code for handling complete uploads. See the docs at https://godoc.org/github.com/tus/tusd/pkg/handler#HookEvent for what values `event` has.
		}
	}()

**Comment by arck123** [comment]
Thanks solve

**Comment by arck123** [comment]
filefo.Upload.ID : 4b88b7efc90cd1ece4e7c1ca5156982e+a72427ac-9754-421f-bee0-53a302177504

How to get only 4b88b7efc90cd1ece4e7c1ca5156982e ?
because name file only 4b88b7efc90cd1ece4e7c1ca5156982e in storage

thanks

**Comment by Acconut** [comment]
> How to get only 4b88b7efc90cd1ece4e7c1ca5156982e ?

See the `event.Upload.Storage` map. It will contain a property for that.

**Comment by arck123** [comment]
workk !!
thank you very much ..

**Comment by arck123** [comment]
how to get extension.
video.mp4 ..  get mp4 ?

**Comment by Acconut** [comment]
See https://tus.io/faq.html#how-can-i-get-the-file-name-or-file-type-for-an-upload

**Comment by arck123** [comment]
work .. thanks
