### ISSUE TITLE
Non-Blocking hooks to blocking hook

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#331]
I want to change ```post-create``` non-blocking hooks to blocking hooks how?

**Comment by Acconut** [comment]
That's not possible. Why would you like to do that? Can you explain your reasons behind that question?

**Comment by alameenlr** [comment]
I want to insert the ```upload id``` to db table before start upload. cloud you please add additional option like set  ```blocking-hooks```

**Comment by Acconut** [comment]
> cloud you please add additional option like set blocking-hooks.

Sorry, but our current code does not allow for that easily and we don't have resources to work on this.

> I want to insert the upload id to db table before start upload.

I would recommend you to design your hooks, so they can handle being executed without the upload ID being stored in the DB. That's how we used tusd in production and it is working fine.

**Comment by alameenlr** [comment]
okay

**Comment by alameenlr** [comment]
Could you Help me.? Please!

**Comment by Acconut** [comment]
As I said, we don't have the resources to work on your feature request. But if you were to describe your problem in more than one sentence, we might be able to give you some advice.

**Comment by gajus** [comment]
> As I said, we don't have the resources to work on your feature request. But if you were to describe your problem in more than one sentence, we might be able to give you some advice.

The reason @alameenlr is a valid one. I have the same issue.

I use `post-create` to add a record to the database. All other hooks that follow depend on that record to be present. There is no straightforward way to make other hooks not depend on the record being present.

It would be nice if all HTTP hooks were blocking by default.

**Comment by gajus** [comment]
Here is an example code:

```js
router.post('/hooks', async (incomingMessage, outgoingMessage) => {
  const hookName = incomingMessage.headers['hook-name'];

  log.debug('received %s hook', hookName);

  const payload = incomingMessage.body;

  if (payload.Upload.ID) {
    if (hookName === 'post-create') {
      await pool.query(sql`
        INSERT INTO file_upload
        (
          user_account_id,
          foreign_tus_id,
          file_name,
          file_type,
          size
        )
        VALUES
        (
          ${userAccountId},
          ${payload.Upload.ID},
          ${payload.Upload.MetaData.filename || null},
          ${payload.Upload.MetaData.filetype || null},
          ${payload.Upload.Size || null}
        )
      `);
    }

    if (hookName === 'post-finish') {
      const fileUploadId = await pool.oneFirst(sql`
        SELECT id
        FROM file_upload
        WHERE foreign_tus_id = ${payload.Upload.ID}
      `);

      const temporaryFileName = createTemporaryNameSync();

      const uploadedFileUuid = uuid();

      // @todo Handle failed conversion.
      await sharp(path.resolve(argv.uploadDirectory, payload.Upload.ID))
        .webp({
          lossless: true,
        })
        .toFile(temporaryFileName);

      const file = googleStorageBucket.file('images/' + uploadedFileUuid);

      // @todo Use offset https://googleapis.dev/nodejs/storage/latest/global.html#CreateWriteStreamOptions
      await file.save(temporaryFileName, {
        gzip: true,
        predefinedAcl: 'publicRead',
        resumable: false,
        validation: 'md5',
      });

      await pool.oneFirst(sql`
        INSERT INTO uploaded_file
        (
          file_upload_id,
          user_account_id,
          uid,
          file_name,
          file_type,
          size
        )
        VALUES
        (
          ${fileUploadId},
          ${userAccountId},
          ${uploadedFileUuid},
          'foo',
          'bar',
          1
        )
        RETURNING id
      `);
    }

    if (hookName === 'post-receive') {
      await pool.query(sql`
        UPDATE file_upload
        SET "offset" = ${payload.Upload.Offset}
        WHERE foreign_tus_id = ${payload.Upload.ID}
      `);
    }

    if (hookName === 'post-terminate') {
      await pool.query(sql`
        DELETE FROM file_upload
        WHERE foreign_tus_id = ${payload.Upload.ID}
      `);

      // @todo delete any uploaded files.
    }

    outgoingMessage.end();

    return;
  }

  // @todo assert authentication
  // @todo assert file restrictions
  outgoingMessage.send('OK');
});

```

**Comment by Acconut** [comment]
> It would be nice if all HTTP hooks were blocking by default.

I disagree but let's not discuss this here. I am also not a fan of adding a flag to make all hooks sync/async. If it's so necessary for you, we can talk about adding an additional sync post-create hook, assuming your are willing to work on a PR.
