### ISSUE TITLE
How to upload file with custom name to s3(using s3store)?

### ISSUE THREAD

**Issue by ayush92garg** [tus/tusd#333]
**Question**
Hi, my sincere apologies if this is a stupid question but I'm unable to find a way to upload files to s3 with a custom name and headers. I am using s3 store to directly upload files to my bucket.

I am able to read the original filename once the file is uploaded(below is the code), but how do I use this name while uploading? Do I need to rename the file once it is uploaded or is there a way to pass it before the upload starts? Any help would be really appreciated.

`go func() {
		for {
			event := <-handler.CompleteUploads
			filename, filetype := event.Upload.MetaData["filename"], event.Upload.MetaData["filetype"]
			fmt.Println("Uploaded. File Details -->> ", filename, filetype)
		}
	}()`

**Setup details**
- Operating System: macOS
- Used tusd data storage: AWS S3
- Used tusd configuration: programmatic implementation
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
tusd does not have a native feature for this but you can rename the upload after it is completed. I added a FAQ entry for this: https://github.com/tus/tusd/blob/master/docs/faq.md#how-can-i-keep-the-original-filename-for-the-uploads

**Comment by segevfiner** [comment]
S3 doesn't support rename directly, meaning you will need to do a copy and delete, which can be extremely slow, sometimes taking as much time as the upload itself.

**Comment by Acconut** [comment]
I know this may not be a satisfying answer for you, but if renames are to slow, you might have design your system without using the original file names. We are open to discuss alternative solutions but tusd currently does not offer such a feature.

Closing this issue since the original question was answered.

**Comment by segevfiner** [comment]
Sadly that probably won't do for the kind of system we have in place that will use tusd. So we will have to either cope with the slow renames, or I'll might just try and see what it will take to add support to use the passed name instead of random IDs to tusd.
