### ISSUE TITLE
Unrouted handler imposes unnecessary requirement on upload path

### ISSUE THREAD

**Issue by innovate-invent** [tus/tusd#340]
**Describe the bug**
The existence of [this function](https://github.com/tus/tusd/blob/b4db495cc65344770bcd26536022a660c3a05084/pkg/handler/unrouted_handler.go#L1193-L1200) imposes an unnecessary restriction on the URI path and software attempting to use the dependent library.

**Expected behavior**
`extractIDFromPath()` should be replaced with a callback:

```golang
type UnroutedHandler struct {
...
   GetID func(r *http.Request)(string, error)
}
```

GetID can default to the current functionality

**Setup details**
golang tusd handler library

**Comment by Acconut** [comment]
See the corresponding PR for more discussion: https://github.com/tus/tusd/pull/341

**Comment by Acconut** [comment]
Closing this issue as recent tusd versions provide support for customizing upload URLs. See https://github.com/tus/tusd/pull/341#issuecomment-1910019932 for more details.
