### ISSUE TITLE
Slow upload speed on S3 compatible service

### ISSUE THREAD

**Issue by cberescu** [tus/tusd#344]
**Describe the bug**
I am using the wasabi.com that supports s3 compatible storage, everything works as expected the only issue being the upload speed. 
Made 2 tests  : 
- used local storage, upload speed uses mximum bandwith 10MB+ , if i go for the s3 storage upload speed decreases to around 1.5MB - 2.5MB . Tried different chunk sizes (5MB, 15MB). On the bigger size the speed increases by aprox 1MB

- tried the s3cmd to upload a file to wasabi.com, speed goes easily over 10MB.

So the issue is not the connection from my browser to the server, or from the server to s3 storage but on how tusd uploads the data to s3 storage. 

Tried both with the hooks and without it. 

**Setup details**
Please provide following details, if applicable to your situation:

- Operating System: Linux Ubuntu 18.04
- Used tusd version: 1.0.2
- Used tusd data storage: AWS S3
- Used tusd configuration: -s3-bucket <bucket_name> -s3-endpoint <s3_endpoint> -host 127.0.0.1 -behind-proxy --hooks-http <hooks_api>
- Used tus client library:  tus-js-client

**Comment by Acconut** [comment]
Thanks for the report. We didn't experience upload speed problems when running tusd on AWS instances while uploading to S3. We have some ideas on how to make the upload handling in tusd more efficient but currently we don't have the resources to work on this. Help is greatly appreciated if you are interested in contributing.

> Tried different chunk sizes (5MB, 15MB). On the bigger size the speed increases by aprox 1MB

As a general rule which for improving speed, try not to set any chunk size at all. It is an unnecessary restriction that will only degrade performance.

**Comment by cberescu** [comment]
Hi @Acconut and thanks for the reply. 
Unfortunately i need to set size limits , and the speed is great if i upload where tusd app is located(on that server) only the upload to wasabi(s3) is slower. 

Maybe s3cmd, witch i have used to compare tusd with, uses parallel uploads. Anyway, thanks again for the reply.

**Comment by Acconut** [comment]
Ok, too bad, that's good to know. Going to close this issue unless you have another question regarding this issue.

**Comment by runar-indico** [comment]
We currently see some issues like this in #376 , and would like to contribute.

I have done some custom-work on the s3-datastore in our system, as well as extending and customizing tusd, so I do have some knowledge the project. 

But for this I would need more information about what could be done to make this more efficient. 

If you are able to share your ideas about this, I might be able to do it.

**Comment by Acconut** [comment]
@runar-indico I am happy to discuss this but please open another issue about it.
