### ISSUE TITLE
Possibility to enable both file hook and http hook at the same time?

### ISSUE THREAD

**Issue by andy23512** [tus/tusd#345]
From this part of code, https://github.com/tus/tusd/blob/7fd41f1bfc6eaa35e37f289100b9f29ba74586dd/cmd/tusd/cli/hooks.go#L47-L60
it seems that one will only get file hook works if passing both file hook and http hook arguments to the tusd command.
But in my case, I need to use http hook to do authentication and save result to database, also need file hook to change the extension name of uploaded files (or can http hook do this thing?).

A possible workaround is to save the extension name into the database for further usage. Is there any better way or suggestion? I think it will be really complicated to solve the order or dependencies between these two type of hooks if both enabled.

**Comment by Acconut** [comment]
No, you cannot use multiple different hooks at the same time. As you said, this would require a system to resolve conflicts, so there is little chance that such a feature gets its way into tusd.

In your case, I would recommend so send the HTTP request using curl or similar tools from the file hooks. That sounds like the easiest way to proceed for now.

**Comment by andy23512** [comment]
Got it, thanks for the suggestion!

**Comment by geek-at** [comment]
Took me longer than I'd like to admit but here's my working script that handles json in a way that can be forwarded to an API using curl

It gets the hook name from the file name. so you can put the same code in th ehook pre-create, post-create, etc..

```bash
#!/bin/bash
name=`basename "$0"`                # for example if the hook pre-create is called, the $name is "pre-create"
STDIN=$(cat /dev/stdin | jq -R .)   # Treating the JSON as raw which escapes the json string so we can curl without problems
echo "[i] New $name"                # [i] New pre-create if that's what's called
status=$( curl -s -d "$STDIN" http://localhost:8081/tus/$name | jq -r .status ) # my backend returns an answer like {"status":"ok"} if it worked/is allowed, {"status":"error"} when it's not ok

# so if the response is not "ok", throw an error
if [ "$status" != "ok" ]; then
    echo "Answered with error '$status'"
    exit 1
fi
```
