### ISSUE TITLE
How does Tusd handle huge files with a server with low storage space if saving to S3?

### ISSUE THREAD

**Issue by ChadTaljaardt** [tus/tusd#346]
**Question**
If i were to deploy a system like this on amazon or digital ocean with a server with around 20GB storage, what would happen in the case where a client tried to upload a file thats around 100GB? Would the server be able to handle this or not? The client will download the file directly from S3, so that wont be a issue, uploading is my only questions regarding this. 

Thanks!

**Comment by Acconut** [comment]
tusd splits up the file into smaller chunks which are just temporarily cached on disk and does not keep the entire 100GB file on disk. So, you should be able to upload files bigger than the disk using tusd. However, you may run into disk space limitation if you have multiple uploads running at the same time and every upload requires disk space for their own intermediate caches.

**Comment by ChadTaljaardt** [comment]
Are these chunk sizes configurable?

**Comment by Acconut** [comment]
Not if you are using tusd as a binary. If you use tusd as a Go package you can set the upper and lower limits for the part sizes: https://github.com/tus/tusd/blob/master/pkg/s3store/s3store.go#L112-L127

**Comment by ChadTaljaardt** [comment]
Thanks for the information @Acconut
