### ISSUE TITLE
Add a synchronous CompleteUpload hook

### ISSUE THREAD

**Issue by segevfiner** [tus/tusd#350]
**Is your feature request related to a problem? Please describe.**
The current `CompleteUpload` hook is asynchronous, this makes it difficult to synchronize any completion operations performed by it with the uploading client and will require an out-of-band mechanism to do so. 

**Describe the solution you'd like**
Add a synchronous `CompleteUpload` hook blocking the response to the final request that complete the upload until it is done.

**Describe alternatives you've considered**
Possibly adding a mechanism/extension to the TUS protocol that can be used to wait for the completion of such post upload post processing as additional requests integrating it with the existing async hook.

**Can you provide help with implementing this feature?**
Possibly. But the exact interface needs to be discussed.

**Comment by Acconut** [comment]
Good idea, that might be useful for some. I currently don't have the time to work on this but we are always open to assist with PRs!
