### ISSUE TITLE
gRPC Hooks headers does not contain Hook-Name

### ISSUE THREAD

**Issue by Clementp57** [tus/tusd#362]
**Describe the bug**
Hook Name is not provided in the gRPC hook metadata

**To Reproduce**
1. Execute command 'tusd -hooks-grpc <grpc_service_address> -hooks-enabled-events pre-create,post-create,post-finish [...]'
2. Start upload using tus-js-client
3. gRPC call metadata does not contain the Hook-Name : 

```
Metadata(content-type=application/grpc,user-agent=grpc-go/1.29.0-dev)
``` 

**Expected behavior**
There should be a Hook-Name entry in the gRPC call metadata.

**Setup details**
- Operating System: Windows 10 pro - Docker version 19.03.5, build 633a0ea
- Used tusd version: v1.1
- Used tusd data storage: S3 - minio inside docker container
- Used tusd configuration: 'tusd -s3-bucket tusd.upload -s3-endpoint http://host.docker.internal:9000 -hooks-grpc <grpc_service_address> -hooks-enabled-events pre-create,post-create,post-finish'
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
You are right, there is no hook name information in https://github.com/tus/tusd/blob/master/cmd/tusd/cli/hooks/proto/v1/hook.proto. Would you be willing to open a PR for this? If not we could also @inigohu for help again.

**Comment by Clementp57** [comment]
I'm not familiar with go, but I'll give it a shot.
