### ISSUE TITLE
Header case in hooks

### ISSUE THREAD

**Issue by hamishforbes** [tus/tusd#370]
Not exactly a bug but due to Go's [header case normalisation](https://github.com/golang/go/issues/5022), request headers in a hook's JSON body can have different case to the original request.
While HTTP(1.1) headers are case insensitive, JSON is not.

This can be confusing and tricky to debug.
Unfortunately there's no consensus in the Go world on how to solve this.

Perhaps tusd could lowercase all header keys in the JSON body so that they are at least always consistent and easy to find accurately in hook receivers?

However this would be a breaking change so understandable if you do not want to implement.

At least this issue should come up if anyone runs into similar issues!

**Comment by Acconut** [comment]
Thank you very much for bringing this to our attention! I wasn't aware for that normalization. I agree with you that lowercasing all header names would be a breaking change that I would like to avoid. However, it sounds like a good candidate to be added to the documentation. Would you be willing to open a PR for that?
