### ISSUE TITLE
S3-store: Writechunk does not match Offset

### ISSUE THREAD

**Issue by runar-indico** [tus/tusd#376]
**Question**
We have a strange event happening consistently for a customer, and we are somewhat at a loss. We are unable to replicate the issue outside the customer-environment, and I hope that somebody here might be able to shed a light on what might be going on.

Timeline, from what we see in the server-logs:
1. Upload is created with a size of 57578400 bytes (58 MB).
2. First chunk is uploaded, with a size of 6291456 bytes (exactly 6 Mebibytes).
  - upload.WriteChunk logs that it did indeed write 6291456 bytes.
  - StatusCode 204 is sent back to the client for this chunk
3. Second chunk is attempted to upload, same chunk-size as last time.
  - upload.GetInfo returns that the offset is 5242880 bytes (exactly 5 Mebibytes)
  - 409 Conflict is returned to the user.

We have successfully used tusd on our own solution for quite some time now, and have never encountered an issue like this. I find it very strange that the Offset is different, especialllly since WriteChunk reports the expected size. Also, the difference is exactly 1 MebiByte. 

The customer is using a Storage-Grid S3-storage. Could this perhaps be the issue? I don't expect you to know the details of Storage-Grid, just me thinking out loud here. 

Any help on this would be greatly appreciated. Note that 

**Setup details**

Please provide following details, if applicable to your situation:
- Operating System: Container-less destribution (linux), Kubernetes-environment.
- Used tusd version: 1.1.0
- Used tusd data storage: S3-compatible (specifically a [NetApp StorageGrid](https://www.netapp.com/us/products/data-management-software/object-storage-grid-sds.aspx)
- Used tusd configuration: custom-build, but here is the relevant s3-config used:
```golang
s3 := s3store.S3Store{
		Bucket:            bucket,
		Service:           service,
		ObjectPrefix:      objectPrefix,
		MaxPartSize:       5 * 1024 * 1024 * 1024,
		MinPartSize:       5 * 1024 * 1024,
		MaxMultipartParts: 10000,
		MaxObjectSize:     5 * 1024 * 1024 * 1024 * 1024,
		BaseConfig:        base,
	}
```
- Used tus client library: dotNet-library

**Comment by Acconut** [comment]
Thank you very much for the detailed writeup! I haven't seen this particular issue on our side. We are using AWS S3 and never experience this issue. Therefore, my first guess would be on Storage-Grid. In the past, problems were sometimes caused by storage backend which are not entirely S3-compatible. Maybe it would be possible for you to get in touch with them and see what their support for S3 multipart uploads looks like?

**Comment by runar-indico** [comment]
Thank you for quick feedback. Really appreciate it. 

According to the [Storage-Grid documentation](https://docs.netapp.com/sgws-113/index.jsp?topic=%2Fcom.netapp.doc.sg-s3%2FGUID-4F529931-BF45-49ED-BB24-C10266B81F5E.html&resultof=%22%69%6e%63%6f%6d%70%6c%65%74%65%22%20%22%69%6e%63%6f%6d%70%6c%65%74%22%20), they should support multipart uploads and it looks to be compatible, from what I can gather. 

We are investigating further remotely with the customer. 

I’ll post our findings here shortly. We added  more logging in the s3-datastore for now, so we should get more information shortly.

**Comment by runar-indico** [comment]
It seems when `store.listAllParts` is run, it returns successfully all parts, but `getIncompletePartForUpload` never returns any parts. I believe that is where we are missing 1 MiB.

We fixed this for now by forcing the chunk size to always be 5 MiB, or disable chunking altogether.

So, we now are able to upload. We did run into another problem, though. We get a very limited upload-speed, even on local network. Typically, 2-2.5 MB per second. We are promised that network issues is not the problem, and that they typically see far better results in other upload to the same s3-storage.

Any ideas about where we could start to debug this?

I know the s3-datastore saves the current chunk to disk somewhere. Could this be a limiting factor?

Should I start a separate issue for this question?

**Comment by Acconut** [comment]
> It seems when store.listAllParts is run, it returns successfully all parts, but getIncompletePartForUpload never returns any parts. I believe that is where we are missing 1 MiB.

It would make sense, but I have no idea why getIncompletePartForUpload is never returning anything. What tusd version are you using? Did you make any modifications to the code?

> I know the s3-datastore saves the current chunk to disk somewhere. Could this be a limiting factor?

I don't think so. Unless your disk is fully utilized all the time, disk performance is usually not a problem.

> Should I start a separate issue for this question?

Yes, please.

**Comment by runar-indico** [comment]
we are using tusd v1.1.0.

We extended the functionality, but we still use the s3-datastore provided by tusd.

**Comment by Acconut** [comment]
> We extended the functionality, but we still use the s3-datastore provided by tusd.

Did you make any modification to the main request handler? In particular to the way how contexts are handled? Please remove all modifications or otherwise it will be impossible to track that bug down.

**Comment by runar-indico** [comment]
No, the modification we do is only that we strip all upload-metadata from being saved in the datastore, and instead sent to a database. When we run the same code in our production-environment, same configuration for the application as the customer except using Minio instead of StorageGrid, the getIncompletePartForUpload returns the expected result each time.

As I cannot debug, or even access the customers environment, I am not really sure how to proceed here. Removing modifications would be ok for us to test, but we cannot have the customer do that. 

I would agree, this issue would be impossible, or at least very difficult to track down. For that reason, I think it is best to close the issue for now.

I thank you in any case for bearing with me here, and for your advice.

**Comment by Acconut** [comment]
No worries, I am always happy to help :)
