### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by sergeyt** [tus/tusd#38]
Now [UnroutedHandler.absFileURL](https://github.com/tus/tusd/blob/master/unrouted_handler.go#L497) function uses `r.Host` and scheme of server where the tusd handler is embedded. It would be great if the handler automatically detects proxied request using `Forwarded`/`X-Forwarded-Host` headers. I have to manually set `r.Host` before calling tusd handler to workaround the cross-origin error.

**Comment by Acconut** [comment]
It's logical to me why we need this, thanks for bringing this to my attention.
Are `X-Forwarded-Proto` and `X-Forwarded-Host` the correct headers for detecting the original scheme and hostname?

**Comment by sergeyt** [comment]
> Are X-Forwarded-Proto and X-Forwarded-Host the correct headers for detecting the original scheme and hostname?
yes, also you need to handle first more modern [Forwarded header](https://tools.ietf.org/html/rfc7239) too.

BTW what do you think if the `tusd` package just accepting `func UploadURL(id string) string` in `Config` structure with `absFileURL` as default you have, so the app could customize this behavior. This configuration could be quickly implemented with small changes in your package and allows to avoid mutation of any request fields.

**Comment by Acconut** [comment]
> BTW what do you think if the tusd package just accepting func UploadURL(id string) string in Config structure with absFileURL as default you have, so the app could customize this behavior. This configuration could be quickly implemented with small changes in your package and allows to avoid mutation of any request fields.

I guess, it's not that easy. For example, in order to be flexible and generate a proper URL, `absFileURL` also needs to request object. I guess the function you suggest would also have this requirement.

**Comment by sergeyt** [comment]
> absFileURL also needs to request object

right, i.e. function with two arguments!

**Comment by Acconut** [comment]
@sergeyt I implemented a first draft in a separate branch in 27d6ade1878b4704c588655de4f4b32ed8825a64. By default, it's disable and must be enabled manually using `RespectForwardedHeaders: true` since I am a bit concerned about security. While the supplied protocol is validated, the host is not and a malicious client can form a URLs as it wants. I am not sure if this opens actual vulnerabilities but I will think a bit more about them. Then this branch will be merged into master.

**Comment by sergeyt** [comment]
@Acconut great, implementation looks trivial. This actually fixes the issue when the server is accessible only behind proxy. Also handling only one proxy is enough for now since proxy chaining is rare case.

**Comment by Acconut** [comment]
This feature has now landed in master.
