### ISSUE TITLE
s3store: unable to create multipart upload: MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#380]
**MissingRegion: could not find region configuration**
`Uncaught Error: tus: unexpected response while creating upload, originated from request (response code: 500, response text: s3store: unable to create multipart upload:
MissingRegion: could not find region configuration
)`

**To Reproduce**
**1. Execute command**
`export AWS_ACCESS_KEY_ID=MY_KEY_ID`
`export AWS_SECRET_ACCESS_KEY=MY_SECRET_KEY`
`export AWS_REGION=eu-west-2`
`sudo ./tusd -s3-bucket my-storage -s3-endpoint https://s3.eu-central-1.amazonaws.com  -s3-object-prefix files -max-size 4398046511104 -timeout 0 -port 1080`
**2. Start upload**
`tus_js_client`
**3. See error**
`Uncaught Error: tus: unexpected response while creating upload, originated from request (response code: 500, response text: s3store: unable to create multipart upload:
MissingRegion: could not find region configuration
)`

**Setup details**
- Operating System: Ubuntu(AWS EC2)
- Used tusd version: v1.1.0)
- Used tusd data storage: AWS S3
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
> sudo ./tusd ...

To my knowledge, `sudo` does not pass in environment variables. Please try `sudo -E` as you can see in https://www.petefreitag.com/item/877.cfm

**Comment by alameenlr** [comment]
`sudo apt install gccgo-go` solved my problem.
