### ISSUE TITLE
Best pattern to check file content?

### ISSUE THREAD

**Issue by sneko** [tus/tusd#381]
Hi @Acconut ,

I see in the FAQ https://tus.io/faq.html#how-can-i-get-the-file-name-or-file-type-for-an-upload a possible way to know about the file content type could to be told by the frontend.

But from a security perspective the frontend could put in metada "hey, here an image", and finally uploads an executable.

With that in mind, what do you recommend to prevent users uploading something wrong? I would like to restrict files they upload.

From what I understand it should be after a success upload since we need to have file content to check its true metadata/content. Maybe it could be something we deal with the PR https://github.com/tus/tusd/pull/373 ?

Otherwise if that's not in a blocking hook, the only solution I see is to consider all tusd uploads as unsafe, and thanks to "post-finished" asynchronous hook, I check their type/content and if ok, I move them elsewhere in the storage I use (another location, Google bucket...)?

What do you think :) ?

Thank you,

**Comment by Acconut** [comment]
> the only solution I see is to consider all tusd uploads as unsafe

I would always recommend that mindset, regardless of which user input you are dealing with. File uploads are always potentially harmful, so you can never trust them fully :)

> I check their type/content and if ok, I move them elsewhere in the storage I use (another location, Google bucket...)?

Exactly, that's the best solution: Add a check after the upload is complete and only using the file if the check passed.

**Comment by sneko** [comment]
Thank you for the answer!

I need to figure out the proper way to make this check async while preventing other microservices to start using it.

In case the user submits the profile form with the tusd generated URL for its avatar, the ProfileService can FileService to "commit" this file and get the final image URL (after being moved to the public folder)... but it needs to wait for the check to complete so:
- In case the check is long to process (or long queue of jobs), if ProfileService needs to wait, the frontend will also takes time to get an answer
- Otherwise, I could make the "commit" call giving in response the final URL image and on during that the FileService pushs a message in an event bus, this message as soon as consumed tries to check the file and move it (but not sure it's fast enough if the frontend needs to use it just after the form submit).

**Comment by Acconut** [comment]
PR https://github.com/tus/tusd/pull/382 may be interesting for you. It adds the `pre-finish` hook which is a synchronous version of `post-finish` and is executed after the file has been received but before a response is sent to the client. Maybe that is a good spot to do you validation?
