### ISSUE TITLE
Add documentation for expected setup relating to CORS

### ISSUE THREAD

**Issue by josh-marshall-jax** [tus/tusd#383]
**Is your feature request related to a problem? Please describe.**
It is not noted that when using a front end webpage to make a tus file upload to a different endpoint with authentication headers will fail due to CORS restrictions on allowed HTTP headers.

**Describe the solution you'd like**
A small addition to documentation noting that for full use of HTTP headers a reverse proxy needs to be used to make requests look like they are coming and going to the same endpoint.

**Additional context**
This is what I have come to with what reading I have done.  I may be misinformed.

**Comment by Acconut** [comment]
This is interesting. What header are you using? The master branch adds the `Authorization` header to the CORS whitelist (see https://github.com/tus/tusd/blob/master/pkg/handler/unrouted_handler.go#L225) but this has not been release yet. I will try to do another release in the next days, so maybe that helps you.

**Comment by josh-marshall-jax** [comment]
Maybe that would make the difference.  My particular use case is multiple file uploads with metadata and I need additional headers in order to supply that metadata and authorize requests.

**Comment by josh-marshall-jax** [comment]
I just read the code and saw that "Upload-Metadata" was an allowed header -- I didn't see this documented.  While auth should still go into a separate header, this gets my code working well enough for now.  This stuff just needs a quick mention in some documentation then it can be closed out.

**Comment by Acconut** [comment]
>  This stuff just needs a quick mention in some documentation then it can be closed out.

Good idea! Would you be open to making a PR for this?

**Comment by josh-marshall-jax** [comment]
I would!  I should be able to get that in today.
