### ISSUE TITLE
https://master.tus.io/files/ returning 500

### ISSUE THREAD

**Issue by fatawesome** [tus/tusd#385]
**Describe the bug**
Some time ago I was using Uppy with https://master.tus.io/files/ as Tus endpoint for university project and it was quite ok. For now it returns 500 with message saying there is some problem with s3 storage:
![image](https://user-images.githubusercontent.com/20212361/82158231-33801a00-988f-11ea-8deb-991cf1ae9c73.png)
![image](https://user-images.githubusercontent.com/20212361/82158245-4561bd00-988f-11ea-9749-153e02c54212.png)

You can also reproduce it on your demo page: https://tus.io/demo.html. Just try to upload something.

**To Reproduce**
1. Make POST request to https://master.tus.io/files/
2. See error

**Setup details**
Please provide following details, if applicable to your situation:
- Used tusd data storage: AWS S3 on https://master.tus.io/files/
- Used tus client library: Uppy.js

**Comment by fatawesome** [comment]
Cool, thank you :)

**Comment by fatawesome** [comment]
Works for now, closing

**Comment by Acconut** [comment]
Thanks for reporting. We fixed our deployment in the meantime, as you noticed :)

**Comment by nicokant** [comment]
I'm experiencing the same issue, how can I solve this?

**Comment by Acconut** [comment]
Please open a new issue with detailed information. This issue has already been closed for 5 years.

**Comment by nicokant** [comment]
Thank you, I've opened https://github.com/tus/tusd/issues/1256
