### ISSUE TITLE
A welcome message would be nice

### ISSUE THREAD

**Issue by kvz** [tus/tusd#39]
When you `GET` on the root or the `basePath`, it would be nice to display:

> Welcome to tusd version x.y.z. For documentation and bug reports, please check https://github.com/tus/tusd

Instead of 

![](https://dl.dropboxusercontent.com/s/vaer657xum6z4fn/2016-02-22%20at%2012.10%202x%20%281%29.png?dl=0)

Just more friendly and to let admins know they did something right, vs wrong.

**Comment by Acconut** [comment]
Here you go :)

**Comment by tim-kos** [comment]
I like it, except that you should not mix "we" and "I".

So let's change "However, there is something I want to tell you personally: " to "However, there is something you need to be aware of: "

**Comment by kvz** [comment]
Great stuff! We could perhaps run the copy also via @ajvanloon
