### ISSUE TITLE
Life-cycle of metadata and resumption activity

### ISSUE THREAD

**Issue by netaisllc** [tus/tusd#391]
**Question**
Does file metadata associated with an uploadable asset persist across resumed uploads?

**Setup & details**
Uppy.js and tusd (go binary), storing to local disk of tusd host; very standard setup.

**Example workflow:**

1. End-user uploads a file that we programmatically attach some metadata to using `onBeforeFileUploaded` client-side hook.
2. End-user does not wait for upload completion. Shuts his browser.
3. End-user later opens browser and resumes uploads. (Yay, tus protocol)
4. In the _post-finish_ hook for that file will the metadata as attached in step 1 be available to the hook and our hook-receiver endpoint?

**Comment by Acconut** [comment]
> In the post-finish hook for that file will the metadata as attached in step 1 be available to the hook and our hook-receiver endpoint?

There is a simple answer: Yes :) The metadata attached to an upload during its creation cannot later be modified and will be available as long as the upload is not deleted from the server/storage.

**Comment by netaisllc** [comment]
Awesome. Thank you.
