### ISSUE TITLE
hooks events documentation

### ISSUE THREAD

**Issue by vindemasi** [tus/tusd#398]
Hello,

This is not a bug, just a minor documentation issue (after introduction of pre-finish hook).

[https://github.com/tus/tusd/blob/master/docs/hooks.md#whitelisting-hook-events](url) has:

```
 If the --hooks-enabled-events option is omitted, all hook events are enabled.
```

while the ```tusd --help``` reports (correctly):

```
 -hooks-enabled-events string
        Comma separated list of enabled hook events (e.g. post-create,post-finish). Leave empty to enable all events (default "pre-create,post-create,post-receive,post-terminate,post-finish")
```

**Comment by Acconut** [comment]
Thank you! Fixed in https://github.com/tus/tusd/pull/399
