### ISSUE TITLE
Azure Blob Storage

### ISSUE THREAD

**Issue by Benehiko** [tus/tusd#401]
Hi there,

**Is your feature request related to a problem? Please describe.**
I saw the library does not have support for the Azure Blob Storage as a cloud store. I had implemented tusd in a freelancing project recently and was forced by my employer to use Azure which I in the end coded on top of the tusd library as a custom store which worked out quite well.

**Describe the solution you'd like**
Have Azure Blob Storage support out of the box.

**Can you provide help with implementing this feature?**
I thought since this isn't currently in the tusd library that I'd integrate the code I wrote and do a pull request. The code might not be up to the library's standard and there are some things I would test before adding it - I just thought I'd get some feedback first.

What are your thoughts?

Kind Regards
Benehiko

**Comment by wregen** [comment]
I would love to see  Azure Blob Storage supported by tus.io out of the box.

**Comment by Acconut** [comment]
Yes, we would be very much interested in such a PR! Thanks for the offer :heart:

**Comment by Benehiko** [comment]
I will see if I can have a PR by this weekend :)

**Comment by AKlaus** [comment]
Can we extend the feature request by adding:

1. Support _Azure File Storage_ along with _Blob Storage_.
2. Compute the MD5 hash of the file and put it base64 representation in the `Content-MD5` property of the blob.

It seems that the linked PR doesn't have it if I'm not mistaken (I'm terrible in Go).

**Comment by omBratteng** [comment]
@AKlaus may I ask what benefit computing the MD5 hash of the file has? (I've never used it, so I am curious)
Would you compute the MD5 hash of the block of the blob, or the entire file?

**Comment by AKlaus** [comment]
The hash is used to verify the integrity of the blob/file during transport.
Form experience, the likelihood of broken transmission is 1/1,000,000 and may appear negligible, but my users transfer many million files.

**Comment by Acconut** [comment]
I am going to close this issue since the main feature request (general support for Azure has been implemented in #458). @AKlaus If you have some additional ideas or feature requests, please feel free to open a new issue. Having separate issues helps with avoiding confusion :)
