### ISSUE TITLE
Get SubmissionID in post-finish hook

### ISSUE THREAD

**Issue by RoyMudie** [tus/tusd#403]
**Question**
I currently running a post-finish hook to move and rename files once uploaded. However, I want to be able to store the files in a folder structure based on the SubmissionID but all I seem to be able to get is the FileID.

$TUS_ID variable is the same json "Upload.ID" which both match the name of the file. Can someone advise how I can access the overall SubmissionID so I can move and group multiple files from a single upload to the same folder?

Cheers,
Roy

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: v1.1.0
  - Commit: 973a4fe066cdca6a2836252c6e804ec55b0c081c
  - Date: Sun Feb 23 21:05:28 UTC 2020
- Used tusd data storage: disk store
- Used tusd configuration: -hooks-dir /usr/local/tusd/hooks/ -upload-dir /usr/local/tusd/temp-data -base-path /upload/ -behind-proxy -metrics-path /metrics
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
What do mean with "SubissionID"? In tusd we don't use that term, so I am not sure what you are referring to.

**Comment by Acconut** [comment]
Glad to hear that you found a solution :+1:
