### ISSUE TITLE
nginx proxy_set_header X-Forwarded-Host

### ISSUE THREAD

**Issue by dragoscirjan** [tus/tusd#404]
**Question**

https://github.com/tus/tusd/blob/master/examples/nginx.conf#L60

```nginx
        proxy_set_header X-Forwarded-Host $hostname;
```

I think `$hostname` may refer to the machine's hostname, which may not always be the same as the domain. 
Would `$host` be more appropriate?

**Comment by Acconut** [comment]
Yes, you are right! I just had a tusd user in the last few days where the difference between host and hostname was a problem. I will update the example. Thanks!
