### ISSUE TITLE
TUS GO server does not resume failed upload

### ISSUE THREAD

**Issue by kkushal05** [tus/tusd#406]
**Question**
Does the tus go server not support resuming uploads. ?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System:
Linux
- Used tusd version: v1.3.0
- Used tusd data storage: Disk Storage
- Used tusd configuration: ./tusd -upload-dir=./ -base-path=/api/v1/uploads/ -hooks-http=http://localhost:8989/tus/events/ 
- Used tus client library:  (tus-py-client)
```py
from tusclient import client

my_client = client.TusClient('http://10.10.10.3:1080/api/v1/uploads/')
uploader = my_client.uploader('/root/3GB.zip', chunk_size=20000)
uploader.upload()
```

Event listener on port 8989:
```py
from flask import Flask
from flask import request
import json

app = Flask(__name__)
@app.route('/tus/events/', methods=['POST'])
def create_task():
    print json.dumps(request.json)
    return "", 201
if __name__ == '__main__':
    app.run(port=8989, debug=True)
```

Hi All,

I started a TUS server and client with the above configuration and tried uploading a 3GB file. Now, for testing purposes, I killed the client process after 20%  approx upload got completed. But when I started it again, it started all over again. It should have resumed from 20%, which did not happen. 

Questions ?
Do I need to start any additional flag while starting server or header to client request for this ?

**Comment by Acconut** [comment]
tusd does not need any special configuration to allow uploads to be resumed. Instead, I think that you are missing some configuration in your client code which is required for resuming. Maybe @ifedapoolarewaju, who built tus-py-client, can help you there?

**Comment by ifedapoolarewaju** [comment]
@kkushal05 to enable resumption you need to pass the `url_storage` parameter to the [uploader constructor](https://tus-py-client.readthedocs.io/en/stable/tusclient.html#tusclient.uploader.Uploader). So your code should look something like this:

```python
from tusclient import client
from tusclient.storage import filestorage

my_client = client.TusClient('http://10.10.10.3:1080/api/v1/uploads/')
storage_path = 'PATH/TO/YOUR/DESRIED/STORAGE/FILE.json'
uploader = my_client.uploader('/root/3GB.zip', chunk_size=20000, url_storage=filestorage.FileStorage(storage_path))
uploader.upload()
```
