### ISSUE TITLE
Metrics data behind load balancer

### ISSUE THREAD

**Issue by averdecia** [tus/tusd#409]
**Question**
Hi everyone. I assume that you are using the client in several use cases. My question is regarding the metrics api on the prometheus format. If I have many tusd-server replicas behind the same load balancer, how can I scrap metrics from specific servers? Prometheus only support statics targets, If I use an Amazon Autoscaling Group, or a Kubernetes pods environment... How can I configure metrics to be scraped? Also prometheus has a pushgateway utility but it is no recommended for service layer scrapping. 
A workaround may be to export metrics in a json format and scrapping with telegraf and influxdb to save.
Is there any way to get those insights? Is there any metrics on json format?
I may probably upload this question in stackoverflow but I decided to try here first.
Regards

**Comment by Acconut** [comment]
Hi there, this sounds like a general question about Prometheus and not tusd directly. I am not a Prometheus expert, so I recommend you to get support from them directly. However, from a brief research it looks like you need to somehow target the servers inside your autoscaling group directly: https://stackoverflow.com/a/49034770 Beside that I cannot provide you with more help.

> Is there any metrics on json format?

No, the metrics are not currently available in the JSON format.

**Comment by averdecia** [comment]
Hi @Acconut 
Thanks for the answer.
I did my own driver to get the same metrics on a Json format using runtime, os, and prometheus/procfs.
Regards

**Comment by Acconut** [comment]
Glad to hear you found a solution!
