### ISSUE TITLE
Is it possible to convert the uploaded files via hooks?

### ISSUE THREAD

**Issue by TaridaGeorge** [tus/tusd#414]
Is it possible to convert the uploaded files via hooks?
So for example, I'm making a service that would accept any type of audio file (mp3, flac, acc) and would offer them for download in a specific format (for example wav). How should I approach this conversion? I was thinking that I could do the conversion work after the final hook but how can I replace the uploaded file in tusd with the converted one? Is it possible to do it on-the-fly?

**Comment by Acconut** [comment]
> I was thinking that I could do the conversion work after the final hook

Yes, the post-finish hook is the perfect spot to start the conversion process.

> how can I replace the uploaded file in tusd with the converted one?

Frankly, I would not do that at all. Yes, you can replace the files in which tusd stores the upload, but tusd is not meant as a download server. It's optimized for file uploads and does not implement caches and so on. Instead, I recommend you to save the converted files somewhere else and use a proper tool for serving those files.

**Comment by TaridaGeorge** [comment]
Great! Thank you!

**Comment by Acconut** [comment]
You're welcome :)
