### ISSUE TITLE
Index out of range error during FinishUpload

### ISSUE THREAD

**Issue by vaughanj10** [tus/tusd#419]
**Describe the bug**
I am running a tusd server in a production Kubernetes cluster. This server is currently successfully handling ~15,000 uploads per day. I have noticed that for about ~0.5% of uploads during the `FinishUpload` step, we receive the following error `panic serving *.*.*.*:*: runtime error: index out of range`.  The relevant stack trace leads me to believe it is occurring at this line in gcsservice.go: https://github.com/tus/tusd/blob/master/pkg/gcsstore/gcsservice.go#L157. Here is a screenshot of one of those stack traces (apologies for it being out of order, this is viewed through our log aggregation service). 

![image](https://user-images.githubusercontent.com/1255074/92003475-1290e700-ed0f-11ea-8668-7dc2bdf86202.png)

As far as I can tell, the uploads that encounter this error fall into limbo as the error wasn't handled and these uploads never fully finish. 

**To Reproduce**
I am unable to deterministically reproduce this bug, I'm only able to see this happen when running tusd at a large scale. 

**Expected behavior**
What I expected to happen was for tusd to not crash in this step and to successfully finish uploading the file. 

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Docker Image: tusproject/tusd:v1.4.0
- Used tusd version: 1.4.0
- Used tusd data storage: Google Cloud Storage
- Used tusd configuration: args: [
          "-port=1081",
          "-behind-proxy",
          "-hooks-http", "REDACTED",
          "-hooks-enabled-events", "post-finish",
          "-hooks-http-forward-headers", "REDACTED",
          "-gcs-bucket", "REDACTED",
          "-timeout", "300000",
          "-hooks-http-backoff", "600",
          "-hooks-http-retry", "10"
        ]
- Used tus client library: tus-java-client/tus-android-client

**Comment by Acconut** [comment]
Thanks for the report. Out of my head, I don't know what could cause this. Maybe @tab1293, who wrote the original GCS implementation, has an idea.

Did you try uploading an empty file (with a size of 0) to reproduce this bug? Can you show the logs from tusd for these request causing this panic?

**Comment by bezi** [comment]
We don't have an atomic repro of this, but we do see this issue in prod using GCS as our backing store.  #360 does seem to resolve it for us.
