### ISSUE TITLE
Some questions about <some.long.alfanumeric.string>.info files content...

### ISSUE THREAD

**Issue by masail** [tus/tusd#42]
During my test, I have earned how to add key-value pairs into MetaData field contained into .info files.
But I'm not sure to have well understood the meaning of the field "IsFinal": I have read the comments into filestore.go, but I have seen these field always set to false, even if the upload is correctly finished. On the other hand the field "IsPartial" is always false even if I stop (restart and stop again) the upload before it is completed. 
What I'm misunderstanding?
Who is responsible (which "go" class) to write the content of the .info files?

Again, thanks a lot in advance.

**Comment by Acconut** [comment]
> But I'm not sure to have well understood the meaning of the field "IsFinal"

There seems to be a general misconception about the fields IsFinal and IsPartial. Both of them have nothing to do with whether the upload is finished or not. Instead, they are necessary for the [tus Concatention extension](http://tus.io/protocols/resumable-upload.html#concatenation). Basically, it provides a way to combine multiple (partial) uploads into a single (final) upload. The IsFinal and IsPartial fields indicate whether this specific upload is a partial one, a final or neither.

> Who is responsible (which "go" class) to write the content of the .info files?

[`FileStore#writeInfo()`](https://github.com/tus/tusd/blob/be8fd83d0d90227511472e459a66b186c5e65c10/filestore/filestore.go#L196-L202) is the only function to write to .info files. You can search in filestore.go for its function name and find the callers.
