### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by vaughanj10** [tus/tusd#420]
**Describe the bug**
I am running a tusd server in a production Kubernetes cluster. This server is currently successfully handling ~15,000 uploads per day averaging 300KB each, so about 4.5 GB total per day. When watching the memory usage over the course of a day, I have noticed the memory only ticks upwards and never seems to fully release any memory. Example of memory usage over 1 day: 

![image](https://user-images.githubusercontent.com/1255074/92007365-d90eaa80-ed13-11ea-99c9-d5d2d25f38bc.png)

The image above shows an increase of 7GB of memory over the day, which seems very high! Additionally, these files are quite small and they only take 1.5 minutes on average to upload, so at any one time only ~50-100 uploads are happening concurrently.

**To Reproduce**
Not sure how to reproduce, as I don't know whether this pertains to all tusd instances or my particular configuration. I am seeing this behaviour happen every day until this k8s pod is evicted due to running out of memory. 

**Expected behaviour**
I would expect that tusd would release memory over time as uploads finish and to not continue increasing.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Docker Image: tusproject/tusd:v1.4.0
- Used tusd version: 1.4.0
- Used tusd data storage: Google Cloud Storage
- Used tusd configuration: args: [
          "-port=1081",
          "-behind-proxy",
          "-hooks-http", "REDACTED",
          "-hooks-enabled-events", "post-finish",
          "-hooks-http-forward-headers", "REDACTED",
          "-gcs-bucket", "REDACTED",
          "-timeout", "300000",
          "-hooks-http-backoff", "600",
          "-hooks-http-retry", "10"
        ]
- Used tus client library: tus-java-client/tus-android-client

**Comment by Acconut** [comment]
Thanks for reporting. I haven't seen this for our production tusd servers. What metric is the graph actually showing? Is that total memory used by a container? Or are those numbers from the `/metrics` endpoint (see https://master.tus.io/metrics)? Are you sure there is no other process running next to tusd causing memory usage?

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Comment by Acconut** [comment]
FYI, I had a look at our production tusd servers and their RSS usually stays around 30 - 40 MiB.

**Comment by jzupka** [comment]
Hello I have same problem in our production servers. Almost same configuration like in issue report head 

tusd Version: v1.3.0

tusd -gcs-bucket  -gcs-object-prefix tusd -behind-proxy -base-path --hooks-http

6742768 4,348g   8416 S 158,7 74,9  14744:55 tusd 
The memory was consumed after 2 days of usage.

**Comment by Acconut** [comment]
@jzupka 

> 6742768 4,348g 8416 S 158,7 74,9 14744:55 tusd

What do those numbers mean? Can you explain? Also, what memory usage does the /metrics endpoint (see https://master.tus.io/metrics) report?

**Comment by jzupka** [comment]
@Acconut sorry for late answer and inconvenient report
this is allocated memory by tusd. Important part is 4.348GB after 2 days of usage. 
CPU load is solved unfortunately memory problem is still there. 
I have to install early oom to kill tusd.

**Comment by Acconut** [comment]
This memory leaks seems to be specific for the GCS storage. I found a few issues in the GCS Go SDK repository about memory leaks (e.g. https://github.com/googleapis/google-cloud-go/issues/1623) which are not fixed in the SDK version we are using in tusd.

@jzupka Can you try to upgrade the GCS Go SDK, recompile tusd and see if the memory leak disappears?

**Comment by jzupka** [comment]
@Acconut yes sure. Lets try this it looks reasonable. I'll try it during this week.

**Comment by Acconut** [comment]
Great, let me know if you hit road blocks!

**Comment by jzupka** [comment]
@Acconut There is really problem with GCS SDK they create newMediaBuffer which they almost never destroy. There is pull request [pull request](https://github.com/googleapis/google-api-go-client/pull/632) to using user manager buffer to avoid this problems. 
I have tried tusd on miniogw -> GCS. Unfortunately it not work good.  I'll make another issue for this.

**Comment by jzupka** [comment]
@Acconut I have tested tusd builded with go Lang 1.15 and last GCS everything unfortunately same behaviour.

**Comment by Acconut** [comment]
> If you have Idea how to solve memory problem with GCS without these pull request it would be great.

Unfortunately, I don't. A first step in the right direction would be to pinpoint what allocations are not released properly. Would you be able to add pprof to tusd and take a memory profile after performing a few uploads? https://www.freecodecamp.org/news/how-i-investigated-memory-leaks-in-go-using-pprof-on-a-large-codebase-4bec4325e192/ looks like a good introduction.

**Comment by jzupka** [comment]
yes I already did it. it looks exactly same than like in https://github.com/googleapis/google-api-go-client/pull/632.

**Comment by Acconut** [comment]
Ok, that's good to know! Would you be able to replace the GCS SDK with the fork from the PR's author and configure it to use our own buffers?

This way we can see if that PR actually solves the problem.

**Comment by joshcurtis** [comment]
Upgrading to v1.8 fixed this for us (I'm on the issue author's old team). Based on the discussion here I'd guess #535 was the fix.

**Comment by Acconut** [comment]
@joshcurtis Awesome, thanks for letting us know! Glad that it fixes the issue for you
