### ISSUE TITLE
Respond with Status 204 while Resume Upload!!

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#422]
**204(No Content) While Resuming Upload**
Request to upload is accepted and started the uploading. I've Paused the Upload manually. The Developers Network tab shows the response of 

> **Pause Request**
> **`Url:`** `https://tus.domian.com/files/d59e93f6e32198328992e02692992050+htCxGORr2-F8dS27kJwUcd3X_8Ky7A-W3APlia1TNtkG9ilYBuYrUCi5Wm7PIrkirLxfD1kEBgsFZIFjJ9l2UiuyJCRdfJnhcxopjma_lmOFhPEoM6DEg4bmD7DW3S72`
> **`Method:`** `OPTION` 
>  **`Status:`** `200`

Then I resumed the Upload,Network tab shows the response

> **Resume Request**
> **`Url:`**`https://tus.domian.com/files/d59e93f6e32198328992e02692992050+PaDp02XfiOTPhanj5eBeBX0ylzVMFpDBM8Wm5WPMnE9Du69g9DFI6b_5tBnDD9v2FSrmhxD63hJEudE6IsYexyu9aD5Sj4ZCtXbc-ZNk401l_LjFrrQh32NjukJYUl2G`
> **`Method:`** `HEAD` 
>  **`Status:`** `204`

**To Reproduce**
_Pause the Upload, Then Resume_

**Expected behavior**
_It must be resumed_

**Setup details**
- Operating System: Ubuntu 18
- Used tusd version: 1.0
- Used tusd data storage: AWS S3
- Used tusd configuration:[-s3-bucket,-s3-endpoint,-s3-object-prefix,-max-size,-timeout,-port,-hooks-http,-hooks-http-retry,-hooks-http-backoff,-hooks-enabled-events ,-behind-proxy]
- Used tus client library: tus-js-client

**Comment by alameenlr** [comment]
`[tusd] 2020/09/05 19:13:20 event="RequestIncoming" method="POST" path=""`
`[tusd] 2020/09/05 19:13:20 event="HookInvocationStart" type="pre-create" id=""`
`[tusd] 2020/09/05 19:13:20 event="HookInvocationFinish" type="pre-create" id=""`
`[tusd] 2020/09/05 19:13:20 event="UploadCreated" id="bd0a7474fef080f329f794216c3ba8b5" size="102354212" url="http://tus.mydomain.com/files/bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:20 event="ResponseOutgoing" status="201" method="POST" path=""`
`[tusd] 2020/09/05 19:13:20 event="HookInvocationStart" type="post-create" id="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:20 event="HookInvocationFinish" type="post-create" id="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:20 event="RequestIncoming" method="OPTIONS" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:20 event="ResponseOutgoing" status="200" method="OPTIONS" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:26 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:26 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:26 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:26 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:27 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:27 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:30 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:30 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:36 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`
`[tusd] 2020/09/05 19:13:36 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"`

There is no problem in FreshUpload With out Interruption(Network Failure,[Pause/Resume]).

**Comment by Acconut** [comment]
It's suspicious that the logs show a GET request when it should be a HEAD request:

> [tusd] 2020/09/05 19:13:26 event="RequestIncoming" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"
> [tusd] 2020/09/05 19:13:26 event="ResponseOutgoing" status="204" method="GET" path="bd0a7474fef080f329f794216c3ba8b5"

Seems like your proxy is not correctly configured. Can you ensure that it properly passes through HEAD requests to tusd?

**Comment by alameenlr** [comment]
This is the Request

![Capture2](https://user-images.githubusercontent.com/50786913/92414573-7c2b4e00-f172-11ea-8101-4c0c44eb316a.JPG)

This is the head Request, Tusd Server Hosted from aws ec2.

**Comment by alameenlr** [comment]
This is the Request

![Capture1](https://user-images.githubusercontent.com/50786913/92414711-1ab7af00-f173-11ea-91e2-e9a75effe4fd.JPG)

Tusd Server Hosted from aws ec2.

**Comment by Acconut** [comment]
Did you check that your proxy properly passes through HEAD requests to tusd? If not, you have to do so or we cannot help you.

**Comment by alameenlr** [comment]
I've tested without Domain (Direct to server xxx.xxx.xxx.xxx:1080) it is working. Do you have any Idea to solve this problem. I

**Comment by Acconut** [comment]
> I've tested without Domain (Direct to server xxx.xxx.xxx.xxx:1080) it is working.

That shows that the problem is caused by the proxy. You must make sure that it properly passes through HEAD requests, which it does not. It turns the HEAD request into a GET request which is wrong. I don't know what proxy you are using, so I cannot help you there.

**Comment by alameenlr** [comment]
Ok, I understand.

**`Request URL`**: `http://xxx.xxx.xxx.xxx:1080/files/6b746dad11aeb231d61ba95808dfca85+pzZoRfEqg50Zso4xG5RLpHmF7C9PNW7aVdiEgtJ2w1km9nBO2hxkxZl3rEQtKBs4cbif5mLXXoyyz6L5yB6bFFvFV4SFzx_AQVSVk8Hq-aW4sZ4nj4dKs2Q3v4J8i93l`
**`Request Method`**: `HEAD`
**`Status Code`**:` 423 Locked`

What's the meaning of this!!!?

**Comment by Acconut** [comment]
> What's the meaning of this!!!?

Everything works as intended. The client wants to resume but the server is still taking care of saving the data from the previously upload request. You must enable retryDelays in tus-js-client, so I can automatically retry.
