### ISSUE TITLE
Upload file using Lambda function

### ISSUE THREAD

**Issue by prabhatsrikant** [tus/tusd#424]
Hi,

I have used tus-js client in my frontend. And trying upload in S3 through a lambda function.
I unable to find a suitable lambda code to accept the file content at the lambda side.
Can you please help with sample code.

Thanks

**Comment by Acconut** [comment]
tusd is not intended to be run inside Lambda. We experimented with Lambda some time ago but at that time its request body limit of a few megabytes made it not feasible for uploading larger files. So I cannot provide you with any example.

**Comment by prabhatsrikant** [comment]
Thanks for the reply.
