### ISSUE TITLE
> 4.0 GB of file

### ISSUE THREAD

**Issue by Jirapong** [tus/tusd#43]
Hi all,

I'm trying to upload a file that have size of 4.6 GB via tus. But after file is about 4.0 GB the PATCH method return an error message 

    read tcp 127.0.0.1:1080->127.0.0.1:61596: i/o timeout

Any idea?

**Comment by Acconut** [comment]
How do you use tusd? If you use the tusd binary, please supply the exact arguments using which you invoked the binary.

**Comment by Jirapong** [comment]
I'm using tusd binary version 0.2.0 with following command

Rabitron:tusd_darwin_amd64 jirapong$ sudo ./tusd -timeout 60000 -max-size 10737418240
[tusd] Using './data' as directory storage.
[tusd] Using 10240.00MB as maximum size.
[tusd] Using 0.0.0.0:1080 as address to listen.
[tusd] Core: ✓ Terminater: ✓ Finisher: ✗ Locker: ✓ GetReader: ✓ Concater: ✗

**Comment by Jirapong** [comment]
updated, I still can't find a reason but based on tus-js-client/demo/index.html itself. It is uploaded successfully

**Comment by Acconut** [comment]
Sadly, I am not able to reproduce this. Is the timeout only triggered for bigger files (> 4GB) or do small files also not work?

**Comment by Jirapong** [comment]
Thank you. It seems like this issue went away after put the chunksize on the tus-js-client library. Thank you.
