### ISSUE TITLE
Putting data from an HTTP hook into tus responses.

### ISSUE THREAD

**Issue by sripberger** [tus/tusd#434]
**Question**
I'm using HTTP hooks and I have a bit of a feature question. I know blocking hooks can cause error messages from the hook to propagate through to the tus response by setting a 5xx response code, but is there any way to do anything like this for successful requests?

For example, if I have a "pre-finish" hook which performs some kind of database operation, and I want to put information about that operation into the response headers of the final PATCH request for a particular upload, is this possible? I can't seem to find it in the docs for HTTP hooks if so. It's not super critical-- I just want to make sure I'm not missing anything as this would simplify some things for me.

**Setup details**
Please provide following details, if applicable to your situation:
- Not really applicable, just a feature question.

**Comment by Acconut** [comment]
No, this is unfortunately not possible right now. We had this and similar feature requests in the past multiple times and we have the intention of providing a better mechanism in the future. Once we get around it, this feature will likely ship in a tusd v3 release with an entirely new hook system to replace the current one. However, as of now, you cannot set the response body from a successful hook invocation.

**Comment by sripberger** [comment]
Ok, that's understandable. Thank you for the swift response. :+1:

**Comment by akuma8** [comment]
Hi, 
I have the same requirement so I hope that after five years there is a solution. I also use the prefinish hook to put data in the response body but it is always empty on the client side. 
Do you have some some recommendations about how to solve this issue? 
thanks

**Comment by Acconut** [comment]
Yes, it's possible using tusd hooks. You have to follow the instructions at https://tus.github.io/tusd/advanced-topics/hooks/ closely, in particular the [required response format](https://tus.github.io/tusd/advanced-topics/hooks/#hook-requests-and-responses).

**Comment by akuma8** [comment]
> Yes, it's possible using tusd hooks. You have to follow the instructions at https://tus.github.io/tusd/advanced-topics/hooks/ closely, in particular the [required response format](https://tus.github.io/tusd/advanced-topics/hooks/#hook-requests-and-responses).

That exactly what I use. I just noticed that if we don't set the statusCode field, tusd ignores the response body, that was my mistake.
