### ISSUE TITLE
Which hook is best fit for magic number validation

### ISSUE THREAD

**Issue by romanpod** [tus/tusd#445]
Hey all,

I'd like to make sure that the uploaded file is of the permitted type, which calls for a magic number validation.
For small files one can use the post-finish hook to inspect the completed file and delete it upon violation, however it's not quite efficient when dealing with large files [wasted traffic, resources, etc].

Possible candidate might be a post-create hook. From the documentation:

> At this point the upload may have received some data already since the invocation of these hooks may be delayed by a short duration

I can use something like _prioritizeFirstAndLastChunk_ in _resumablejs_ to get the first chunk, however I don't think there's any guarantee that _some data_ will actually be there and we probably do not control the hook invocation delay.

What do you think would be the best way to go?

Thanks.

**Comment by Acconut** [comment]
If you do not want to wait until the post-finish hook, you can check how much data has already been uploaded in the post-receive hooks. If X bytes have been uploaded, you can trigger a file validation job.

Please be aware that not for every data store the uploaded file can be accessed before the upload is finished (e.g. S3 store).
