### ISSUE TITLE
how to clean temp files

### ISSUE THREAD

**Issue by lucas007007** [tus/tusd#446]
**Question**
Hi All
Please tell me how to clean temp files(chunk files info files) in s3 after upload finished. 
Can I store the temp file in list  and delete files by file name when finish-event triggered.
Thanks.

**Comment by Acconut** [comment]
Temporary files should be cleaned up after any upload which also occurred when I tried to reproduce the behavior you are mentioning. Can you share more details about your setup?

**Comment by lucas007007** [comment]
> Temporary files should be cleaned up after any upload which also occurred when I tried to reproduce the behavior you are mentioning. Can you share more details about your setup?

I just start the server in programmatically and using S3Composer  as following.

func S3Composer(s3EndPoint string,s3Bucket string,s3ObjectPrefix string) *tusd.StoreComposer {

	composer := tusd.NewStoreComposer()
	s3Config := aws.NewConfig()

	log.Infof("Using '%s/%s' as S3 endpoint and bucket for storage.\n", s3EndPoint, s3Bucket)

	s3Config = s3Config.WithEndpoint(s3EndPoint).WithS3ForcePathStyle(true)

	sess := session.Must(session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	}))
	store := s3store.New(s3Bucket, s3.New(sess, s3Config))

	store.ObjectPrefix = s3ObjectPrefix
	store.UseIn(composer)
	locker := memorylocker.New()
	locker.UseIn(composer)
	return composer
}

**Comment by Acconut** [comment]
> Please tell me how to clean temp files(chunk files info files) in s3 after upload finished.

Oh, you are talking about the files on S3. Once the upload is complete, tusd will leave the uploaded file and the `.info` file on S3. This is not a bug but by design because these files should then be consumed by your application. If you want to remove them, you have to do it on your own in, for example in the post-finish hook.

**Comment by lucas007007** [comment]
> > Please tell me how to clean temp files(chunk files info files) in s3 after upload finished.
> 
> Oh, you are talking about the files on S3. Once the upload is complete, tusd will leave the uploaded file and the `.info` file on S3. This is not a bug but by design because these files should then be consumed by your application. If you want to remove them, you have to do it on your own in, for example in the post-finish hook.

OK. Thanks for replying. I will try to drop these file in the post-finish hook.

**Comment by sha4id** [comment]
how to delete these file, any code link?

**Comment by Acconut** [comment]
> how to delete these file, any code link?

We don't have any example code for this, sorry. For the files on S3, we just use its own auto expiration rules to remove files after some time.
