### ISSUE TITLE
Status of Current Upload.

### ISSUE THREAD

**Issue by MarhabaLRS** [tus/tusd#451]
**Question**
Status of Current Upload.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: `Linux`
- Used tusd version: `latest`
- Used tusd data storage: `AWS S3`
- Used tusd configuration: `-s3-bucket storage_bucket -s3-endpoint https://s3.eu-central-1.amazonaws.com -s3-object-prefix files -s3-part-size 100663260 -max-size 2199023255552 -timeout 0 -port 1080 -hooks-http http://localhost/tus_verify -hooks-http-retry 3 -hooks-http-backoff 2 -hooks-enabled-events pre-create,post-create,post-finish,post-terminate -behind-proxy true -expose-metrics false`
- Used tus client library: `tus-js-client`

**How can I get current status of my upload by giving `upload-id`?**
Status means `bytes-uploaded`!

**Comment by Acconut** [comment]
tusd cannot be directly queried to retrieve the upload progress for an upload which is currently running. Use the `Offset` property in the `post-receive` hook instead to let your application get notified about progress updates for the uploads.
