### ISSUE TITLE
Error: tus: invalid or missing offset value, originated from request

### ISSUE THREAD

**Issue by TommasoAmici** [tus/tusd#452]
**Describe the bug**
I'm using `tusd` programmatically in my go backend behind nginx, and I keep getting this error:

```
Error: tus: invalid or missing offset value, originated from request
(method: HEAD, url: https://mydomain.tld/files/b53af271868fdc811f4f3a93d6f5a7c9,
response code: 200, response text: , request id: n/a)
```

I can upload small files (<10mb), but when trying bigger files only the first chunk is saved and then the error occurs.

When looking at the headers, it seems like the tus headers are not there.

e.g. on a HEAD response I get this. I would expect to see `Upload-Offset` and `Upload-Length` in there.

```http
HTTP/2 200 OK
server: nginx/1.19.6
date: Sun, 17 Jan 2021 14:36:27 GMT
content-type: application/zip
content-length: 644676112
content-disposition: attachment;filename="filename.zip"
tus-resumable: 1.0.0
x-content-type-options: nosniff
x-cache-status: MISS
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
referrer-policy: no-referrer-when-downgrade
strict-transport-security: max-age=31536000; includeSubDomains
X-Firefox-Spdy: h2
```

**To Reproduce**
I've made a repository with a (not) working example. See here: https://github.com/TommasoAmici/tusd-bug-report

**Expected behavior**
I should be able to upload files on the endpoint.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: macOS for local development, Ubuntu server for staging
- Used tusd version: `1.4.0`
- Used tusd data storage:
```go
        store := filestore.FileStore{
		Path: *app.tusDir,
	}

	composer := tusd.NewStoreComposer()
	store.UseIn(composer)
```
- Used tusd configuration: 
```go
       handler, err := tusd.NewHandler(tusd.Config{
		BasePath:                "/files/",
		StoreComposer:           composer,
		MaxSize:                 8 * 1_000_000 * 1_000,
		RespectForwardedHeaders: true,
		NotifyCompleteUploads:   true,
		Logger:                  app.infoLog,
		PreUploadCreateCallback: app.checkIfOrderExistsTusHook,
	})
```
Then I integrate it in my mux like this:
```go
mux.Handle("/files/", http.StripPrefix("/files/", handler))
```
- Used tus client library: Uppy.js
```ts
new Uppy<StrictTypes>({
    id: "client-upload",
    debug: true,
    autoProceed: false,
    restrictions: {
      minFileSize: 1,
      maxFileSize: 8 * GB,
      maxNumberOfFiles: numFiles,
      minNumberOfFiles: numFiles,
      allowedFileTypes: uppyFileTypes,
    },
    locale: languageMap[language],
    meta: {
      orderID: orderID,
      orderUUID: orderUUID,
      orderEmail: orderEmail,
      admin: false,
    },
  })
```

**Comment by Leeaandrob** [comment]
I am experiencing the same issue behind nginx.

**Comment by TommasoAmici** [comment]
I have tried using the `tusd` binary and I can upload with no issues.

So there should be no issues on the client side with uppy. I think it's something with the set up of the handler in my go app

**Comment by Acconut** [comment]
Thanks for the detailed description and the code for reproduction. Can you generate a HAR file containing network information and send it over? https://mediaplanhq.zendesk.com/hc/en-us/articles/360001171463-Generating-a-HAR-file-for-troubleshooting

**Comment by TommasoAmici** [comment]
Thanks for looking into this, here's an HAR file with the error.
[tusd-missing-offset.har.zip](https://github.com/tus/tusd/files/5857738/tusd-missing-offset.har.zip)

**Comment by TommasoAmici** [comment]
Also, here's my nginx config

```nginx
location /files/ {
      # Forward incoming requests to local tusd instance
      proxy_pass http://127.0.0.1:4000;
  
      # Disable request and response buffering
      proxy_request_buffering off;
      proxy_buffering off;
      proxy_http_version 1.1;
  
      # Add X-Forwarded-* headers
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      client_max_body_size 0;
    }
```

**Comment by TommasoAmici** [comment]
I've spent some more time on this today.

With the `tusd` binary I can upload big files, but if I try to pause and resume I get this same error. HAR here:
[local.mttaudio.com_Archive [21-01-25 16-55-57].har.zip](https://github.com/tus/tusd/files/5867745/local.mttaudio.com_Archive.21-01-25.16-55-57.har.zip)

**Comment by Leeaandrob** [comment]
Locally running the project without the nginx directly with golang server the problem not happened.

**Comment by Leeaandrob** [comment]
I am using parallelUpload with 10 too

**Comment by solovenkoU** [comment]
Had the exact same problem with the latest Uppy.
Tried to upload 1 small file (100KB) from a local device.
Downgraded to the following and the issue is gone.
"@uppy/core": "^1.15.0",
"@uppy/dashboard": "^1.14.0", 
"@uppy/tus": "^1.8.2"

So it seems like a client-side issue.

**Comment by Qoraiche** [comment]
I had the same issue, the problem is that the backend is not accepting large content-length chunks so you either need to configure your server to accept large requests or use the **chunkSize** UppyJs Tus client parameter to limit the chunks are being sent through the browser.
hope this helps

**Comment by MrVibe** [comment]
facing same issue in apache and nginx on local. Could we be missing something ?

**Comment by Qoraiche** [comment]
> facing same issue in apache and nginx on local. Could we be missing something ?

> I had the same issue, the problem is that the backend is not accepting large content-length chunks so you either need to configure your server to accept large requests or use the **chunkSize** UppyJs Tus client parameter to limit the chunks are being sent through the browser. hope this helps

have you tried this?

**Comment by Acconut** [comment]
@MrVibe If the hint form @Qoraiche does not help, please provide more details on the error and the setup you have.

**Comment by G2G2G2G** [comment]
I've had this setup in production for more than a year and have never reproduced this. His proxy must have a lower file limit than his uppy is set to send as chunks. 
The entire benefit to tus is to be able to send files in parts and chunks. Set client to send 2mb files and the client will send you 2mb files for each chunk, this is great benefit to overflowing nginx itself and the server. Allowing you to do multi gigabyte files easily and less RAM

**Comment by MrVibe** [comment]
> @MrVibe If the hint form @Qoraiche does not help, please provide more details on the error and the setup you have.

My issue was resolved. It was not related to the chunk-size but the initial length of a security token that I send in the first call. Due to the token being large it was truncated and thus subsequent chunks rejected. So I was able to resolve this by reducing the token size.

**Comment by Acconut** [comment]
Multiple people reported issues here, but I think most of them are resolved by now. I will close this issue. If anyone still has problems, please open a new issue with a detailed report.

**Comment by alidplus** [comment]
Is there any solution for Nginx with reverse proxy?

**Comment by Acconut** [comment]
@alidplus We are using Nginx in production without problems. Please follow the instructions at https://tus.github.io/tusd/getting-started/configuration/#proxies and https://github.com/tus/tusd/blob/main/examples/nginx.conf. If that doesn't work, please open a new issue with detailed descriptions of the error and your setup.

**Comment by mifi** [comment]
I got this error because proxy_pass was configured incorrectly in nginx:
```conf
location /files/ {
	proxy_pass http://127.0.0.1:1977/files/;
}
```
instead of the correct:
```conf
location /files/ {
	proxy_pass http://127.0.0.1:1977;
}
```

**Comment by Acconut** [comment]
@mifi I added a comment to the Nginx example to hopefully prevent others from running into this problem as well: https://github.com/tus/tusd/commit/a9dc5228dabee5fc6f697e57d6665c4a8d3c64f1
