### ISSUE TITLE
s3store: NoSuchKey error

### ISSUE THREAD

**Issue by lucas007007** [tus/tusd#456]
**Question**
Hi All
I try to use tusd to  upload large file( ~1G) 
After  100% completed  was shown in  browser console , http 500 error returned. (and upload failed)

```
[tusd] 2021/01/19 11:36:45 event="UploadCreated" id="98754d0a85dd5a81d3cb839c34c803ef+g_ZoA05ZqjmE87ULQPuXk4VgkjyO1di6oddh9IsPYlda8j4PYNfVPeH6u2_zExxsM2vnmUbpM4FVqJJXikfeahcW71RjDCTAlXj8I7zlRiU-" size="751566392" url="http://localhost:8005/api/v1/files/98754d0a85dd5a81d3cb839c34c803ef+g_ZoA05ZqjmE87ULQPuXk4VgkjyO1di6oddh9IsPYlda8j4PYNfVPeH6u2_zExxsM2vnmUbpM4FVqJJXikfeahcW71RjDCTAlXj8I7zlRiU-"
2021/01/19/ 11:36:45.108741537  [Info] vvv/pkg/upload.invokeHookSync 157 id:98754d0a85dd5a81d3cb839c34c803ef+g_ZoA05ZqjmE87ULQPuXk4VgkjyO1di6oddh9IsPYlda8j4PYNfVPeH6u2_zExxsM2vnmUbpM4FVqJJXikfeahcW71RjDCTAlXj8I7zlRiU-,size:%!s(int64=751566392),name:post-create
[tusd] 2021/01/19 11:36:45 event="ResponseOutgoing" status="500" method="POST" path="" error="Multiple errors occurred:
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: BFA2563C1B12B816, host id: m1ORcd4vo91gwKa0nQUSIHdJ5YDMGQaz0Qk6nUpWkwMC5/HeZ8k+uDWQ9z23d12lIOQiBQTuQLQ=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 856AEEF3BF64CEC4, host id: Nu3Kog6n1emh+jCxsGeD7rthWKCu+tg8Lhd+LanY98eGlrYvdFy1Z8hqFGySeUOOPV0HQomnb7E=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: A16815EA2028BBE7, host id: lkmxp+x7ABFV0U8Sed17dgNItIlFzuwU07qtrbGc+4fmvXKDfX/Mfmwtpb/3x+debQ+QhRXifZk=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: F7727AA847FFD4DF, host id: x4ISE39HlUifWbOjlR8lIUGXSjnJbwCiLPfgCMKGKn/VfePqmRMIG9wTY2fciUCVp5YZZXfj/2M=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 07F90B6A975ED60D, host id: aAV70VSQXfqm/B0HKVgaFCVJzfaK0hqZw2F3ng6FS80THfkVlFeUc47PPT9gh0bwUdJWJCjP4Fs=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 6N3T1MFJBSAS9K7P, host id: 2lbdEiwfuepqI8DlpsJinsEmR7ZiexnV5Y6jeGNzEEglKyNYehIUExfYGCmqNlIBEgL61+6oVSU=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 9974A9571698FD21, host id: 2QD3+sXg5tHNve2eKtXYsiZkOwXNlz1XrEM0Y+wOc1If4gYzhnNewQ4Mgd9gI7AYlcNY5inStpA=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: CFEA3505F4598A05, host id: xeQI3QIjrkf+J+8ZjIzV1+OoUIp+VWkMsSxmqYBsO6Wa0yDiSo8rvfngQKoh4ujnjCVttSneqpc=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 7A832F3FC2EDE7D6, host id: Q1IsLiylSlaxxNuXQwaHjl8SPXecgNwzAK8qFwtWaMycjKl9QXuRgrzqwk+CRjsNtR8p/LBwUBM=
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: 63E0983E28DE0700, host id: Y3DQpPt2hAjaUnQ1n6TwKdkNPylBlbFXQxRWaKOY+bYX/98OmziLfACGwnaSvjrqFAsEW7hAN1Y=
" requestId=""
```

**Setup details**
Please provide following details, if applicable to your situation:

data flow : tus-js-client > https > ec2[nginx > tusd@8005 ] > s3

I just start the server in programmatically and using S3Composer as following ,leaving the default setting.

`func S3Composer(s3EndPoint string,s3Bucket string,s3ObjectPrefix string) *tusd.StoreComposer {
composer := tusd.NewStoreComposer()
s3Config := aws.NewConfig()
log.Infof("Using '%s/%s' as S3 endpoint and bucket for storage.\n", s3EndPoint, s3Bucket)
s3Config = s3Config.WithEndpoint(s3EndPoint).WithS3ForcePathStyle(true)
sess := session.Must(session.NewSessionWithOptions(session.Options{
	SharedConfigState: session.SharedConfigEnable,
}))
store := s3store.New(s3Bucket, s3.New(sess, s3Config))
store.ObjectPrefix = s3ObjectPrefix
store.UseIn(composer)
locker := memorylocker.New()
locker.UseIn(composer)
return composer
}`

**Comment by Acconut** [comment]
The errors from the logs is this:

> NoSuchKey: The specified key does not exist

So you didn't configure `aws.NewConfig()` with the correct S3 credentials.

**Comment by YOUNG00011** [comment]
I alse meet this problem when i was trying to upload one 2.5G file, really hope there be a solution to this problen!

**Comment by lucas007007** [comment]
> The errors from the logs is this:
> 
> > NoSuchKey: The specified key does not exist
> 
> So you didn't configure `aws.NewConfig()` with the correct S3 credentials.

Thanks for replying.
I think I have configed ec2 with the correct S3 credentials because I succeed to upload small files to S3 , such as png file or pdf file.

**Comment by Acconut** [comment]
Ok, what does your tus-js-client code look like?

**Comment by RobertVillalba** [comment]
I believe I'm also seeing this same error. I'm using tus-js-client and writing to minio with s3 store. The client code simply has parallelUploads set to 2 and I've tried to remove as much as possible from the server side. My upload works for a small 10 MB video file and I see that there are 3 info files and 3 regular files with two being 5 MB and the last one 10 MB as expected. However when I try to perform an upload with a 677 MB file I end up with the same expected 4 partial files (info and content) and simply a new .info file for each post request that the client retries sends to concatenate the parts. 

```
NoSuchKey: The specified key does not exist.
status code: 404, request id: 16FFE9C72F880F1E, host id: 
NoSuchKey: The specified key does not exist.
status code: 404, request id: 16FFE9C72F8A8975, host id: 
```

**Comment by Acconut** [comment]
@RobertVillalba Can you test more file sizes and see if files smaller than 10MB work and files bigger than 10MB fail? tusd has two different method for concatenating uploads, depending on whether all partial uploads are bigger than 5MB.

**Comment by RobertVillalba** [comment]
I believe that you are correct. I created some zip files and was able to upload things smaller than 10MB (tested up to 9.6MB) but 10.6MB broke the upload concatenation. I also tried specifying a chunk size of 1MB as well for a final test to see if the behavior would change, but it did not.

**Comment by RobertVillalba** [comment]
I think I may have found the error. The CopySource does not take into account the store object prefix. After adding this in it seems that the uploads complete as expected (tested up to a 1 GB upload).

**Comment by Acconut** [comment]
@RobertVillalba Your patch will be in this release: https://github.com/tus/tusd/releases/tag/v1.9.1
