### ISSUE TITLE
After the upload was finish, how can I send additional information to the client?

### ISSUE THREAD

**Issue by danegigi** [tus/tusd#459]
**Question**
I'm able to successfully upload a file but what's the best way to send information back to the client with additional information?
In the configuration, there's the `PreFinishReponseCallback` which I use to process the file which also generates some information that I want to send back to the client.

I've made use of the HTTP NewUnroutedhandler
```
	app.Post("/files/", adaptor.HTTPHandlerFunc(handler.PostFile))
	app.Head("/files/:id", adaptor.HTTPHandlerFunc(handler.HeadFile))
	app.Patch("/files/:id", adaptor.HTTPHandlerFunc(handler.PatchFile))
	app.Get("/files/:id", adaptor.HTTPHandlerFunc(handler.GetFile))
```

Here's my configuration
```
	handler, err := tusd.NewUnroutedHandler(tusd.Config{
		BasePath:                  "/files/",
		StoreComposer:             composer,
		NotifyCompleteUploads:     true,
		PreFinishResponseCallback: processUploads,
	})
```

Thanks

**Comment by Acconut** [comment]
Apologies for my late response! Currently, there is no easy way to send information from the server to the client after an upload is complete. Instead, you currently have to implement a separate endpoint where the client can fetch additional information. We have plans to implement this natively into tusd, so let us know if you are interested in helping :)
