### ISSUE TITLE
GridFS support

### ISSUE THREAD

**Issue by mzygmunt** [tus/tusd#47]
Hello,
I'm currently working on MongoDB and I need to upload some large files into DB. Is there a plan to support GridFS storage?

**Comment by Acconut** [comment]
While there is no plan to add support for GridFS in the near future, I do not reject this idea.

**Comment by mzygmunt** [comment]
Thanks for reply. I will be very grateful to you for adding this functionality in the future.

**Comment by Acconut** [comment]
Just to clarify: I sadly do not have the time to add support for GridFS anytime soon. If you really want to see it integrated, you may need to build it on your own.

**Comment by Acconut** [comment]
Closing this for now, as there is no sign that GridFS support will be added in the near future.
