### ISSUE TITLE
Fail to upload file to s3 with 404 on PATCH, only .info uploaded

### ISSUE THREAD

**Issue by b0bbywan** [tus/tusd#471]
When using tusd with AWS s3 my uploads fails with a 404 on the PATCH request.

The POST seems to work well, I receive a 201 response with an https uri as I wanted, but the PATCH fails after a while (I see upload progressing then failing on Uppy)

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: linux
- Used tusd version: 1.6.0
- Used tusd data storage: AWS S3
- Used tusd configuration: See below
- Used tus client library: uppy 1.27.0

here's my tusd handler config :
```
func Uploads() *tusd.UnroutedHandler {
	AWSID := config.Getenv("AWS_ID")
	AWSSecret := config.Getenv("AWS_SECRET")
	creds := credentials.NewStaticCredentials(AWSID, AWSSecret, "")
	config := aws.Config{
		Credentials: creds,
		Region: aws.String("eu-west-1"),
		S3ForcePathStyle: aws.Bool(true),
	}
	store := s3store.New(
		storage.BucketUploads,
		s3.New(session.Must(session.NewSession()), &config),
	)
	composer := tusd.NewStoreComposer()
	store.UseIn(composer)
	handler, err := tusd.NewUnroutedHandler(tusd.Config{
		BasePath:              "/uploads/",
		StoreComposer:         composer,
		RespectForwardedHeaders: true,
	})
	if err != nil {
		panic(fmt.Errorf("unable to create handler: %s", err))
	}
	return handler
}
```

Here are tusd logs:
```
[tusd] 2021/04/14 14:41:01 event="UploadCreated" id="782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" size="3012597" url="https://mydomain.com/uploads/782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" 
[tusd] 2021/04/14 14:41:01 event="ResponseOutgoing" status="201" method="POST" path="/uploads" requestId="" 
[tusd] 2021/04/14 14:41:01 event="ResponseOutgoing" status="404" method="PATCH" path="/uploads/782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" error="upload not found" requestId=""
```
I can see the 782c394b3d58967f45fce729cb5026b6.info file in the s3 bucket, but the + part seems to prevent tusd to find it afterwards.

I'm using tusd with Gin. Using a filestore storage works well.

**Comment by Acconut** [comment]
Are you using `http.StripPrefix` when attaching the uploader handler? See https://github.com/tus/tusd/blob/master/cmd/tusd/cli/serve.go#L81 for how it needs to be done.

**Comment by b0bbywan** [comment]
@Acconut Thanks for your answer.

I'm attaching the handler like this : 
```
       	tusdHandler := Uploads()
        engine.POST("/uploads", gin.WrapF(tusdHandler.PostFile))
	engine.GET("/uploads/:id", gin.WrapF(tusdHandler.GetFile))
	engine.HEAD("/uploads/:id", gin.WrapF(tusdHandler.HeadFile))
	engine.PATCH("/uploads/:id", gin.WrapF(tusdHandler.PatchFile))
```

I'm not sure I understand how `http.StripPrefix` helps me here, can you explain me ?

**Comment by b0bbywan** [comment]
I don't have the error when using an HTTP request, only with HTTPS and AWS S3

**Comment by SagarKabariya** [comment]
> When using tusd with AWS s3 my uploads fails with a 404 on the PATCH request.
> 
> The POST seems to work well, I receive a 201 response with an https uri as I wanted, but the PATCH fails after a while (I see upload progressing then failing on Uppy)
> 
> **Setup details**
> Please provide following details, if applicable to your situation:
> 
> * Operating System: linux
> * Used tusd version: 1.6.0
> * Used tusd data storage: AWS S3
> * Used tusd configuration: See below
> * Used tus client library: uppy 1.27.0
> 
> here's my tusd handler config :
> 
> ```
> func Uploads() *tusd.UnroutedHandler {
> 	AWSID := config.Getenv("AWS_ID")
> 	AWSSecret := config.Getenv("AWS_SECRET")
> 	creds := credentials.NewStaticCredentials(AWSID, AWSSecret, "")
> 	config := aws.Config{
> 		Credentials: creds,
> 		Region: aws.String("eu-west-1"),
> 		S3ForcePathStyle: aws.Bool(true),
> 	}
> 	store := s3store.New(
> 		storage.BucketUploads,
> 		s3.New(session.Must(session.NewSession()), &config),
> 	)
> 	composer := tusd.NewStoreComposer()
> 	store.UseIn(composer)
> 	handler, err := tusd.NewUnroutedHandler(tusd.Config{
> 		BasePath:              "/uploads/",
> 		StoreComposer:         composer,
> 		RespectForwardedHeaders: true,
> 	})
> 	if err != nil {
> 		panic(fmt.Errorf("unable to create handler: %s", err))
> 	}
> 	return handler
> }
> ```
> 
> Here are tusd logs:
> 
> ```
> [tusd] 2021/04/14 14:41:01 event="UploadCreated" id="782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" size="3012597" url="https://mydomain.com/uploads/782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" 
> [tusd] 2021/04/14 14:41:01 event="ResponseOutgoing" status="201" method="POST" path="/uploads" requestId="" 
> [tusd] 2021/04/14 14:41:01 event="ResponseOutgoing" status="404" method="PATCH" path="/uploads/782c394b3d58967f45fce729cb5026b6+vo.rW0quUD0XBWaopJlymlSIK4e3rysSkJbe87_WsA.EB0bd3EE.cwX_uqF61b_7mDwuFPi8.qvWxZSAI69kIbmyDRhnYDpO36yUW5V.TFDI_fM9ZKKSPV8kYcNw7jjg" error="upload not found" requestId=""
> ```
> 
> I can see the 782c394b3d58967f45fce729cb5026b6.info file in the s3 bucket, but the + part seems to prevent tusd to find it afterwards.
> 
> I'm using tusd with Gin. Using a filestore storage works well.

Hey, I am also trying to upload from Uppy to AWS S3 using tusd, do you have git link for reference ? It will help me lot, thank you so much in Advance.

**Comment by Acconut** [comment]
@b0bbywan Can you please provide a minimal, but complete example where this fails? I have never used Gin before so such a minimal example would be the only way how I could debug it.

**Comment by b0bbywan** [comment]
@Acconut Thank you for your answer.

Here's my minimal gin config :

```
	engine := gin.New()
	engine.Use(
		cors.New(cors.Config{
			AllowAllOrigins:  true,
			AllowMethods:     []string{"PUT", "PATCH", "GET", "POST", "HEAD", "OPTION", "DELETE"},
			AllowHeaders:     []string{"Origin", "Content-Type", "Authorization", "Content-Language", "Content-Disposition", "X-Requested-With", "X-Request-ID", "X-HTTP-Method-Override", "Upload-Length", "Upload-Offset", "Tus-Resumable", "Upload-Metadata", "Upload-Defer-Length", "Upload-Concat", "User-Agent", "Referrer", "Content-Length"},
			ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Headers", "Access-Control-Allow-Methods", "Upload-Offset", "Location", "Upload-Length", "Tus-Version", "Tus-Resumable", "Tus-Max-Size", "Tus-Extension", "Upload-Metadata", "Upload-Defer-Length", "Upload-Concat", "Location", "Upload-Offset", "Upload-Length"},
			AllowCredentials: true,
			MaxAge:           12 * time.Hour,
		}),
	)
      	tusdHandler := Uploads()
	engine.POST("/uploads/", gin.WrapF(tusdHandler.PostFile))
	engine.GET("/uploads/:id", gin.WrapF(tusdHandler.GetFile))
	engine.HEAD("/uploads/:id", gin.WrapF(tusdHandler.HeadFile))
	engine.PATCH("/uploads/:id", gin.WrapF(tusdHandler.PatchFile))


```

And logs extract from chrome and TUS when uploading with uppy

```GENERAL
Request URL: https://mydomain.com/uploads/
Request Method: POST
Status Code: 201 
Remote Address: xxx.xxx.xxx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
RESPONSE HEADER
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers: Content-Length,Access-Control-Allow-Headers,Access-Control-Allow-Methods,Upload-Offset,Location,Upload-Length,Tus-Version,Tus-Resumable,Tus-Max-Size,Tus-Extension,Upload-Metadata,Upload-Defer-Length,Upload-Concat
content-length: 0
date: Tue, 04 May 2021 11:40:31 GMT
location: https://mydomain.com/uploads/38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ
REQUEST HEADER
:authority: mydomain.com
:method: POST
:path: /uploads/
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
authorization: REDACTED
content-length: 0
dnt: 1
origin: http://localhost:8000
referer: http://localhost:8000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
tus-resumable: 1.0.0
upload-length: 18189766
upload-metadata: relativePath bnVsbA==,name ZWNnX05hdmFqZXJvXzE1LTItMjAyMV8xNGgyOS5jc3Y=,type dGV4dC9jc3Y=,filetype dGV4dC9jc3Y=,filename ZWNnX05hdmFqZXJvXzE1LTItMjAyMV8xNGgyOS5jc3Y=
user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

[tusd] 2021/05/04 11:40:31 event="UploadCreated" id="38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ" size="18189766" url="https://mydomain.com/uploads/38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ" 
[tusd] 2021/05/04 11:40:31 event="ResponseOutgoing" status="201" method="POST" path="/uploads/" requestId="" 


GENERAL
Request URL: https://mydomain.com/uploads/38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ
Request Method: PATCH
Status Code: 404 
Remote Address: xxx.xxx.xxx.xxx:443
Referrer Policy: strict-origin-when-cross-origin
RESPONSE HEADER
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers: Content-Length,Access-Control-Allow-Headers,Access-Control-Allow-Methods,Upload-Offset,Location,Upload-Length,Tus-Version,Tus-Resumable,Tus-Max-Size,Tus-Extension,Upload-Metadata,Upload-Defer-Length,Upload-Concat
content-length: 17
content-type: text/plain; charset=utf-8
date: Tue, 04 May 2021 11:40:34 GMT
REQUEST HEADER
:authority: mydomain.com
:method: PATCH
:path: /uploads/38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
authorization: REDACTED
content-length: 18189766
content-type: application/offset+octet-stream
dnt: 1
origin: http://localhost:8000
referer: http://localhost:8000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
tus-resumable: 1.0.0
upload-offset: 0
user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

[tusd] 2021/05/04 11:40:32 event="ChunkWriteStart" id="38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ" maxSize="18189766" offset="0" 
[tusd] 2021/05/04 11:40:32 event="ResponseOutgoing" status="404" method="PATCH" path="/uploads/38d1be049f241b39768cc1ed56b7e8cb+CLDXUkpKN2m14D44waQF1Y8jzjF2OnOeE3KHYYO05OkzRfOW8.heoobt9TdSuZoblCEaF5f06wk.andUm.qaBdv9K1C82Y2AZhFjFVL4Ue09PTu3TXnqa59VLiPH.0TZ" error="upload not found" requestId="" 
```

**Comment by Acconut** [comment]
@b0bbywan Can you please expand the example to include a fully working main function? It should also include how the tusd handler is constructed and how the `engine` is attached to the HTTP handler. Without a fully working example, I will not be able to debug this as I do not have time to come up with a failing program on my own.

**Comment by Arcadianer** [comment]
I have a similar issue. What is funny tho is that the same code appears to be working on Windows 10 but on linux i get a 404.

**Comment by Arcadianer** [comment]
I will provide a example or just send you the code in private in a day or two.

**Comment by b0bbywan** [comment]
@Acconut Sorry for the misunderstanding. I'm working on it now, however I can't reproduce the error when running directly GIN in HTTPS. The environment where this error happens is behind an AWS Load Balancer, I strongly suspect the problem to come from it.

**Comment by Arcadianer** [comment]
I also managed to resolve the problem. On my side it had something to do with my container image.
Previously I used to build a bare image with just the software inside. I replaced the bare one with alpine and the error seems to be gone.

**Comment by b0bbywan** [comment]
@Arcadianer That's interesting, I'm using scratch for my release image, I'll give it a try with alpine.

**Comment by Arcadianer** [comment]
If it helps, the Dockerfile I am now using looks something like this:
```
FROM golang:1.16-alpine AS build
# Adding Certs
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates
WORKDIR /workspace
COPY . /workspace

ENV CGO_ENABLED=0
RUN go mod download all

RUN go build -a -installsuffix cgo -o <module>

FROM alpine AS runtime
# Copy certs
RUN apk add --no-cache ca-certificates jq gcc 
#COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /workspace/image ./
EXPOSE 8080/tcp
ENTRYPOINT ["./image"]

```

**Comment by b0bbywan** [comment]
@Arcadianer Indeed it works ! Thanks a lot for the heads up !

@Acconut so the problem really is with `scratch` docker image and not https (i'm not sure if Gin is involved or not). Do you want me to close this issue and open a new one for `scratch` ?

**Comment by Acconut** [comment]
@Arcadianer Wow, that is an incredible result! I would never have thought the the Docker image can be the cause. In that case, a minimal example would have probably led us in the wrong direction.

As @b0bbywan suggested, I am going to close this issue since the original problem is solved. Feel free to open a new issue for investigating the reason why tusd does not work with `scratch`!
