### ISSUE TITLE
How can I set an exit code from grpc hook in java?

### ISSUE THREAD

**Issue by TaridaGeorge** [tus/tusd#472]
**Question**
How can I set an exit code from grpc hook in java?

According to the documentation for the pre-create hook in order to reject the upload an exit code > 0 should be set. I can't find a way to set this exit code in Java and also If i want to specify the error message I don't know how to do that.

> you can determine whether the upload should be created or rejected using the exit code. An exit code of 0 will allow the upload to be created and continued as usual. A non-zero exit code will reject an upload creation request, making it a good place for authentication and authorization.

What I've tried:
`return SendResponse.newBuilder().setResponse(Any.newBuilder().setValue(ByteString.copyFromUtf8("1")).build()).build();`

But doing that does not reject the upload. 

The only method I can find to make the upload fail is to call the onError method on the StreamObserver instance of grpc. If I do that in the tusd server console I see this and the upload fails:

`
-tusd] 2021/04/19 13:31:00 event="RequestIncoming" method="OPTIONS" path="" requestId=""
-[tusd] 2021/04/19 13:31:00 event="ResponseOutgoing" status="200" method="OPTIONS" path="" requestId=""
-[tusd] 2021/04/19 13:31:00 event="RequestIncoming" method="POST" path="" requestId="" 
-[tusd] 2021/04/19 13:31:00 event="HookInvocationStart" type="pre-create" id="" 
-[tusd] 2021/04/19 13:31:01 event="HookInvocationError" type="pre-create" id="" error="rpc error: code = Unknown desc = " 
-[tusd] 2021/04/19 13:31:01 event="ResponseOutgoing" status="500" method="POST" path="" error="pre-create hook failed: rpc error: code = Unknown desc = 
- " requestId="" 
`

Is it ok to do it like that? And if yes how can I specify an error message?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: v1.6.0
- Used tusd data storage: disk store
- Used tusd configuration: ./tusd --hooks-grpc localhost:6565 --hooks-grpc-retry 5 --hooks-grpc-backoff 2 --hooks-enabled-events "pre-create,post-create,post-receive,post-terminate,post-finish,pre-finish"
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
I have never used gRPC with Java, so I cannot give any Java-specific advice. However, if you want to reject an upload, the gRPC invocation must return an error. I think you already found out about this approach from you comment.

> And if yes how can I specify an error message?

If you want a custom HTTP response code, you should set the gRPC error code (see https://github.com/tus/tusd/blob/master/cmd/tusd/cli/hooks/grpc.go#L43-L45). However, I do not know how to do this in Java.
The response body will be inferred from the gRPC error, so try setting the error message to the desire response.

I know that this is currently implemented very suboptimally but I hope to improve the gRPC hooks in the near future. Of course, help is always appreciated, if you want to :)

**Comment by TaridaGeorge** [comment]
This works:
```
responseObserver.onError(Status.INTERNAL
          .withDescription(e.getMessage())
          .augmentDescription("customException()")
          .withCause(e) // This can be attached to the Status locally, but NOT transmitted to the client!
          .asRuntimeException());
```
from here: https://github.com/saturnism/grpc-by-example-java/blob/master/error-handling-example/error-server/src/main/java/com/example/grpc/server/ErrorServiceImpl.java#L33

https://github.com/avinassh/grpc-errors/issues/4
