### ISSUE TITLE
Custom MaxSize

### ISSUE THREAD

**Issue by ChrisSchinnerl** [tus/tusd#474]
**Is your feature request related to a problem? Please describe.**
I'd like to set a different MaxSize depending on a request header that a proxy could set after authenticating a user.

**Describe the solution you'd like**
I think a good way to implement this would be by allowing to provide a `func (*http.Request) (int64, error)` in the config. If not nil it would override the other MaxSize field. 

**Can you provide help with implementing this feature?**
I would be willing to implement it.

**Comment by Acconut** [comment]
Apologies, this ticket somehow slipped through my inbox. Hopefully my answer will still be helpful for you:

I do not think a separate configuration is necessary for you to implement this functionality but it can already be done using the `pre-create` hook: Basically, you set the MaxSize very high and instead validate the upload size in the `pre-create` hook. There you have access to the requests object and all necessary headers to determine the maximum size for a given user. If this maximum is exceeded, your hook must return an error, so the upload gets rejected.

**Comment by Acconut** [comment]
Opened https://github.com/tus/tusd/issues/1352 for this idea.
