### ISSUE TITLE
Wrong code returned for HEAD calls in unrouted handler

### ISSUE THREAD

**Issue by cjhenck** [tus/tusd#48]
The protocol shows HEAD calls as returning 200 codes, which is also how the TUSKit library is implemented and what the HTTP spec defines.

https://github.com/tus/tus-resumable-upload-protocol/blob/master/protocol.md#example
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by Acconut** [comment]
Thank you for reporting. I am deeply sorry for not resolving this simple inconsistency before.
