### ISSUE TITLE
Upload-Offset should not be returned for partial uploads

### ISSUE THREAD

**Issue by cjhenck** [tus/tusd#49]
When using the concatenation extension, partial uploads should not have an offset, which also implies that they should be `PATCH`ed from offset 0 regardless of how many bytes have been received so far.:

https://github.com/tus/tus-resumable-upload-protocol/blob/master/protocol.md#concatenation

**Comment by Acconut** [comment]
Do you refer to the ambiguities mentioned in #81?

**Comment by cjhenck** [comment]
Yes.  I suppose my original comment is not necessarily correct, it depends on the resolution for 81.

**Comment by Acconut** [comment]
tus/tus-resumable-upload-protocol#85 will most likely be accepted and therefore tusd is conform again. :)
Thank you for noticing!
