### ISSUE TITLE
Internal server error when downloading non-finished resource

### ISSUE THREAD

**Issue by mitjap** [tus/tusd#490]
**Describe the bug**
When downloading a non-finished upload I get status 500 server error - "cannot stream non-finished upload". 

Also HEAD request does not finish in this scenario. (Edit: I found that this was because my HEAD request contained body. I don't think this is even valid HTTP request.)

**To Reproduce**
1. Create new resource with POST, with deferred length
2. Try to download non-finished resource
3. See error

**Expected behavior**
I expect a 4xx status, as this is client error.

**Setup details**
- Used tusd version: https://master.tus.io
- Used tus client library: postman

**Comment by Acconut** [comment]
Thank you for the report! I just changed it, so that it now return the more appropriate 400 response.
