### ISSUE TITLE
New major version (v2) of tusd

### ISSUE THREAD

**Issue by Acconut** [tus/tusd#492]
After the last major release (https://github.com/tus/tusd/issues/212), this issue is used to track possible changes for the next major release (v2):

- Change the HTTP status code for client caused timeouts from 500 to 408 (see https://github.com/tus/tusd/issues/169#issuecomment-877197279).

**Comment by oliverpool** [comment]
(I wanted to ask about the status, but then I saw that there is already a pull-request with a checklist: #672)

**Comment by Acconut** [comment]
Tusd v2 has been released some time ago, so this can be closed: https://tus.io/blog/2023/09/20/tusd-200
