### ISSUE TITLE
The transmission will fail after half an hour?

### ISSUE THREAD

**Issue by a852882874** [tus/tusd#499]
![1628164163(1)](https://user-images.githubusercontent.com/25943026/128345131-dd69e871-cb38-40cb-ad6d-fddb1ff289e8.png)
![1628164182(1)](https://user-images.githubusercontent.com/25943026/128345159-0c0481e3-168c-433d-beda-021e9e510872.png)

**Comment by Acconut** [comment]
You must fill out the template when opening such an issue or otherwise we do not have enough information to help you. A screenshot is not a sufficient description for a bug.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
