### ISSUE TITLE
Metadata being properly set on object after upload to S3 bucket

### ISSUE THREAD

**Issue by mcunningham** [tus/tusd#508]
**Describe the bug**
I have a cloud hosted tusd server and I am currently uploading files via the tus-js-client. I am following the basic [node.js example](https://github.com/tus/tus-js-client/blob/master/demos/nodejs/index.js). I am able to upload files to S3, however the file metadata I am setting in the tus-js-client upload call is not being reflected properly on the S3 object. For example, I want S3 to recognize`text/plain` as the Content-Type however `binary/octet-stream` is still showing as the Content-Type after upload. I also tried setting content-type alongside filename and filetype but that did not work either.  

I noticed the metadata I used in the original tus-js-client was coming through but was prefixed by `x-amz-meta` as seen below:

<img width="1315" alt="Screen Shot 2021-09-27 at 12 50 23 AM" src="https://user-images.githubusercontent.com/56338479/134848178-fac116c1-21c5-45e9-a2d4-d38e8ff44c7f.png">

Here is my tus-js-client upload code:

```javascript
  const upload = new tus.Upload(fs.createReadStream(path), {
    endpoint: TUS_URL,
    metadata: {
      filename: "README.md",
      filetype: "text/plain",
    },
    retryDelays: [0, 1000, 3000, 5000],
    uploadSize: fs.statSync(path).size,
    chunkSize: 10000000,

    onError(error) {
      throw error;
    },
    onProgress(bytesUploaded, bytesTotal) {
      const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
      console.log(bytesUploaded, bytesTotal, `${percentage}%`);
    },
    onSuccess() {
      console.log("Upload finished:", upload.url);
    },
  });
  upload.start();
```

 Is this expected behavior? Am I setting something incorrectly?

**To Reproduce**
1. Upload file with tus-js-client setting the filename and filetype as part of the metadata
2. Upon upload, view S3 console to see Content-Type is binary/octet-stream and not the filetype provided (text/plain)

**Expected behavior**
I expected the upload to take into account the metadata provided in the tus-js-client call and set the correct Content-type accordingly

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux (tusd binary)
- Used tusd version: v1.6.0
- Used tusd data storage: AWS S3
- Used tusd configuration: tusd -s3-bucket=my-bucket -max-size=20000000000 -timeout=8000
- Used tus client library: tus-js-client

**Comment by Acconut** [comment]
> Is this expected behavior?

Yes, this is expected. tusd does currently not set the `Content-Type` header for S3 objects. It only adds all the meta data from the tus upload as meta data for the S3 object. If you are interested in improving this situation, feel free to open a PR! We are always happy to assist. :)

**Comment by mcunningham** [comment]
@Acconut Thanks, so if I want to set Content-Type from the tus-js-client to be displayed in S3 properly afer upload where would I do so? I tried passing in the below but it didn't work 

```javascript
    const upload = new tus.Upload(file, {
    endpoint: TUS_URL,
    metadata: {
      filename: "README.md",
      filetype: "text/plain",
    },
    headers: {
      "Content-Type": "text/plain", // tried to set header here and doesn't reach s3 still
    },
    uploadSize: size,
    onError(error) {
      throw error;
    },
    onProgress(bytesUploaded, bytesTotal) {
      const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2);
      console.log(bytesUploaded, bytesTotal, `${percentage}%`);
    },
    onSuccess() {
      console.log("Upload finished:", upload.url);
    },
  });
```

**Comment by Acconut** [comment]
Closing in favor of https://github.com/tus/tusd/issues/1016.
