### ISSUE TITLE
TLS GRPC?

### ISSUE THREAD

**Issue by TaridaGeorge** [tus/tusd#560]
Is there a way to achieve secure connection while using the tusd grpc hooks? My GRPC Server is secured via TLS certificates and any clients connecting to it must show their certificate.

**Comment by TaridaGeorge** [comment]
I think that in order to have this one should implement the grpcOpts from here
https://github.com/tus/tusd/blob/774b7bec6e3ee3e684ccb45ceac3e71d1ae7c3e9/cmd/tusd/cli/hooks/grpc.go#L26
something like here:
https://github.com/grpc/grpc-go/blob/bac0a7e47f70cf08cd80193ff26a55d954e1e102/examples/route_guide/client/client.go#L157

I will try to see If I can proxy the grpc insecure request view nginx to the secure grpc server that I have.

**Comment by Acconut** [comment]
I am no expert at gRPC but tusd does not have such a feature, as far as I know. If you are interested in adding it to tusd, let me know and I can help you with a PR.

**Comment by TaridaGeorge** [comment]
I've solved it using nxing.

```
server {
    listen 1443 http2;

    access_log /var/log/nginx/grpc_access_log.log;

    location / {
        grpc_pass grpcs://my-secured-grpc-server:6565;
	grpc_ssl_certificate /opt/certs/ca.pem;
        grpc_ssl_certificate_key /opt/certs/ca-key.pem;
    }     

}
```
