### ISSUE TITLE
Can we dynamically pass bucket name from uppy for tus upload?

### ISSUE THREAD

**Issue by mohandass-pat** [tus/tusd#564]
Right now want to allow our users to upload data with different buckets. Can we pass bucket names dynamically if we use the existing helm charts without setting bucket name in env?

**Comment by oschrenk** [comment]
A single tusd process can only upload to a single bucket

See also response from maintainer 

https://github.com/tus/tusd/issues/491#issuecomment-873920897

**Comment by Acconut** [comment]
@oschrenk is correct. The upload destination inside tusd cannot be changed dynamically at runtime.
