### ISSUE TITLE
S3 AWS package incompatibility

### ISSUE THREAD

**Issue by maxpert** [tus/tusd#59]
Hey guys,

 So I am trying to use TUS with S3 in my own project, since there were no examples, I looked into comments/code and tried came up with this piece of code:

```go
        cfg := &aws.Config{
            Credentials: credentials.NewStaticCredentials(
                viper.GetString("s3_access_key_id"),
                viper.GetString("s3_secret_access_key"),
                ""),
        }
        s3Client := s3.New(session.New(), cfg)
        store := s3store.New(viper.GetString("s3_bucket"), s3Client)
        store.UseIn(composer) 
```
When compiling this piece of code I get compile errors

```
cannot use s3Client (type *"github.com/aws/aws-sdk-go/service/s3".S3) as type s3iface.S3API in argument to s3store.New:
	*"github.com/aws/aws-sdk-go/service/s3".S3 does not implement s3iface.S3API (wrong type for AbortMultipartUpload method)
		have AbortMultipartUpload(*"github.com/aws/aws-sdk-go/service/s3".AbortMultipartUploadInput) (*"github.com/aws/aws-sdk-go/service/s3".AbortMultipartUploadOutput, error)
		want AbortMultipartUpload(*"github.com/tus/tusd/vendor/github.com/aws/aws-sdk-go/service/s3".AbortMultipartUploadInput) (*"github.com/tus/tusd/vendor/github.com/aws/aws-sdk-go/service/s3".AbortMultipartUploadOutput, error)
```

What am I doing wrong here? Is it a bug? How can I fix this?

**Comment by Acconut** [comment]
Thank you for reporting, there is definitely something fishy going on. It seems to be related to how we manage our dependencies but I need to dive more into before I can tell you more specific facts.

Which Go version are you using and did you explicitly enable or disable the Go vendor experiment (using the `GO15VENDOREXPERIMENT` environment variable)?

**Comment by maxpert** [comment]
I am using Go 1.7, I will look into disabling the vendor experiment. I got it to work by removing the aws directory from vendor folder (right now I have written a bash script, which is of course not good). I can get code to compile afterwards.

**Comment by Acconut** [comment]
I was able to reproduce this issue and the only solution I was able to find is the same deletion approach as you mentioned. For now, I removed the aws-go-sdk package (and another one for which the same problem would have occurred). I hope it will work for you now.

**Comment by maxpert** [comment]
Will this fix one have a tag? I can just modify my dependency version file to point to the new version.

**Comment by Acconut** [comment]
Once the tests pass again (which fail now due to missing dependencies), I will publish a new release with the corresponding tag.

**Comment by Acconut** [comment]
The new release has been tagged as 0.5.2

**Comment by kvz** [comment]
I like you commithash 😋
