### ISSUE TITLE
Web MediaRecorder getUserMedia Blob to tusd AWS S3 data storage

### ISSUE THREAD

**Issue by imcodingideas** [tus/tusd#606]
**Question**
I have a theory I want to try. I would like to take the web [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) blob and "stream" upload it to a tusd AWS S3 data storage. Think Loom desktop and webcam. It's super fast to upload/encode it and I think they are using something like this setup.

Could this work? Am I going down the right path? If not where are my gaps?

**Setup details**
Please provide following details, if applicable to your situation:
- Used tusd data storage: AWS S3
- Used tus client library: Any: [e.g. tus-js-client, tus-java-client, TUSKit, Uppy.js]

**Comment by Acconut** [comment]
I don´t think there any obvious gaps in your idea. In fact, there is a demo in the tus-js-client repository for the client-side code that is responsible for streaming the video to tusd using getUserMedia:

https://github.com/tus/tus-js-client/blob/master/demos/browser/video.js
https://github.com/tus/tus-js-client/blob/master/demos/browser/video.html

That should help you a lot :)

**Comment by imcodingideas** [comment]
Thank you @Acconut, this validates thats its worth the effort to pursue. 🙌
