### ISSUE TITLE
Is there any document for api calling?

### ISSUE THREAD

**Issue by rezaalimorady** [tus/tusd#611]
**Question**
I want to test routes and need completely guide for calling api.
For example for start uploading at first should call the bla bla api and set these headers and these bodies.
For resuming upload calling bla bla api and set these headers and these bodies.
I want to test them with POSTMAN.
Need suitable documentation for API calling.
  
**Setup details**
- Operating System: Ubuntu
- Used tusd version: latest
- Used tusd data storage: disk store
- Used tusd configuration: just same as your repository
- Used tus client library: I wanna use POSTMAN

**Comment by oschrenk** [comment]
Does the documentation at https://tus.io/protocols/resumable-upload.html fit your needs?

**Comment by Acconut** [comment]
@oschrenk is correct. The documentation for its API is the tus specification.

**Comment by rezaalimorady** [comment]
Thats it 
Thanks
@oschrenk
