### ISSUE TITLE
How set offset in partial upload?

### ISSUE THREAD

**Issue by rezaalimorady** [tus/tusd#612]
**Question**
How set partial offset in partial uploading?
the document say that we should not set offset in partial upload.
![image](https://user-images.githubusercontent.com/60624937/148678987-0dcd1022-a6f1-4c53-aeba-a7816c3670ef.png)
This method not get the first id?
how could we found wich chunk is for wich Id?
who should save or remember the ids posted for a video .
finally we want to concatenate like this!
`Upload-Concat: final;/files/f833e7b6c22dea2cf7d8676a1b714e3d /files/7405ac4ac50d24024d501e49b67956a9
`

let me ask it in other way.
thinking you submit first file and set header partial. the id is A.
and the second one you submit the post request and the id is B.
third one is C.
finally i want to concatenate these.
normally i should use this pattern:
`Upload-Concat: final;/files/A /files/B /files/C`
ok?
now if i use wrong pattern what happens? of course file is not correct.
`Upload-Concat: final;/files/C /files/B /files/A`
so is there any way to prevent this happens?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: ubuntu
- Used tusd version: 1.8
- Used tusd data storage: disk
- Used tusd configuration: as same as repository
- Used tus client library: -

**Comment by Acconut** [comment]
I hope you already found the answer on your own! I will just answer here as well, in case another person is looking here.

> now if i use wrong pattern what happens? of course file is not correct.
Upload-Concat: final;/files/C /files/B /files/A
so is there any way to prevent this happens?

You have to keep track of the order of partial uploads on your own. You cannot attack offsets to partial uploads in the way you are asking for here. Partial uploads can be concatenated in any order you like, so tusd does not enforce any order on you.
