### ISSUE TITLE
add some jobs in pre create hook

### ISSUE THREAD

**Issue by rezaalimorady** [tus/tusd#614]
**Question**
How can i manage pre create hook? or other hooks?
for example i want to save user agent in pre create hook.
in wich file should i use that?
is there any document for hooks?

**Comment by Acconut** [comment]
The documentation for hooks is at https://github.com/tus/tusd/blob/master/docs/hooks.md, as mentioned in the README.

**Comment by rezaalimorady** [comment]
I use the -hooks-dir for example/hooks and it works.
but it is a bash script file.
i wanna use go file. how could i do that

**Comment by rezaalimorady** [comment]
And how could i change status code 500 to 400 when hook  return error?
![image](https://user-images.githubusercontent.com/60624937/148773656-90a713ef-0414-4317-8156-8996ad6eae5d.png)

**Comment by Acconut** [comment]
> i wanna use go file. how could i do that

Compile your Go code into a binary, rename it to `pre-create` and place it into your hooks directory.



> And how could i change status code 500 to 400 when hook return error?

This is not possible until https://github.com/tus/tusd/pull/516 is completed and merged.

**Comment by rezaalimorady** [comment]
and how access the uploaded ID and other need detail in go file?

**Comment by Acconut** [comment]
Read the stdin using `os.Stdin` and parse it using the `encoding/json` package.
