### ISSUE TITLE
post-finish hook gets called multiple times

### ISSUE THREAD

**Issue by renepardon** [tus/tusd#616]
**Describe the bug**
The "latest" version calls the `post-finish` hook multiple times (3 times). Reverting to `tusproject/tusd:v1.8.0` works quite good.

**To Reproduce**
- Create a SAAS project including TUSD for file uploads and deploy everything with Docker swarm. Use `image: tusproject/tusd:latest` image.
- Command I used for the container: `command: -verbose --hooks-http=http://api:8080/api/uploader/tusd/webhook -hooks-stop-code=401 -hooks-http-forward-headers=Authorization,Cookie,TraceId`
- Within the PHP application I check for a few conditions because even with v1.8.0 and before it looks like the hook gots called multiple times:

```php
$conditions = $payload &&
            !empty($payload['ID']) &&
            !empty($payload['Storage']) &&
            $request->hasHeader('hook-name') &&
            $request->header('hook-name') === 'post-finish';
```
Even if those conditions are met I have to check for the same tus_payload id to prevent duplicate entries being created in my database.

**Expected behavior**
The post-finish hook should only be called once when the upload is completely done and the file is stored at it's desired location.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Ubuntu / Docker Container
- Used tusd version: latest/1.8.0
- Used tusd data storage: local file system storage
- Used tusd configuration: `-verbose --hooks-http=http://api:8080/api/uploader/tusd/webhook -hooks-stop-code=401 -hooks-http-forward-headers=Authorization,Cookie,TraceId`
- Used tus client library: `Uppy.js`

**Comment by Acconut** [comment]
Thank you for the report. I am not convinced this is a bug in tusd. This has never happened for our usage of non-HTTP hooks, so it is probably not related to the core hook logic. Could it be that your hooks endpoint responds with an error or takes to long to respond? If so, the retry logic would kick in and resend the same hook request.

**Comment by renepardon** [comment]
hi @Acconut 
this is indeed a HTTP hook. The called application is a PHP laravel application.
What is the time limit for hook response before the hook gets sent again? Maybe I can reproduce this. Usually the response should be back in no longer than a second but if not, I could also move the corresponding logic to the background and respond faster.

**Comment by Acconut** [comment]
> What is the time limit for hook response before the hook gets sent again?

I don´t know out of my head. It could be that it used the default timeout values from Go's `net/http` package.

**Comment by renepardon** [comment]
@Acconut ok looks like that there is an error response being returned. So tusd tries to call the same hook again for 2 more times? Is there a setting to prevent that or to increase the time before it's tried again?

**Comment by renepardon** [comment]
ok, searched for the cli flags and found the answer, there is :) `hooks-http-retry` and `hooks-http-backoff`

thanks!
