### ISSUE TITLE
S3 bucket configuration

### ISSUE THREAD

**Issue by rezaalimorady** [tus/tusd#620]
**Question**
Should i config my s3 detail in Flags.go file?
And is there any example for configuration s3 bucket?

**Comment by rezaalimorady** [comment]
all file will directly uploading on s3 bucket? or saving on local storage after completing upload on s3 bucker?

**Comment by rezaalimorady** [comment]
If all file directly uploading on s3, this module how will clean the bucket for files that is not complete ?
thinking i upload a file on s3 bucket and its not completly. stopping upload.
my file in the s3 is not complete file. right?
user never try to complete the upload.
how this module detect this file is not complete and remove it?

**Comment by Acconut** [comment]
> Should i config my s3 detail in Flags.go file?

No, just pass the flags on the command line

> And is there any example for configuration s3 bucket?

https://github.com/tus/tusd/blob/master/docs/usage-binary.md

> all file will directly uploading on s3 bucket?

Yes

> If all file directly uploading on s3, this module how will clean the bucket for files that is not complete ?

It won't. You must take care of that. S3 has some options to remove unfinished mulitpart uploads and old files.

**Comment by rezaalimorady** [comment]
Is that possible define s3 endpoint and bucket like `export AWS_ACCESS_KEY_ID=zxxxxxx`
I don't like to define them in flags.
what is key of them 
for example `export WHAT=xxxxxx`
i am looking for suitable key instead WHAT for s3 endpoint and bucket name

**Comment by Acconut** [comment]
> Is that possible define s3 endpoint and bucket like `export AWS_ACCESS_KEY_ID=zxxxxxx`

No, that's not possible. These can only be defined using flags.
