### ISSUE TITLE
Issue in using tusd with HTTPs

### ISSUE THREAD

**Issue by flomarty** [tus/tusd#64]
Hello,

I would like to use tusd on Https protocol. I didn't success to used it. Is there possible to use this protocol. If it's possible, how do it this ?

Thank you for helping.

**Comment by kvz** [comment]
Hi @flomarty, thanks for taking an interest in tus!

To be honest, we're not an absolute 💯  on offering HTTPS out of the box for reasons mentioned in https://github.com/tus/tus-node-server/issues/13#issuecomment-158169623:

> Does it have to be baked into the server itself? e.g. if you'd use an ssl terminator like haproxy/stunnel/nginx, you could run the tus server as a nonprivileged user (port > 1024), and also when the next heartbleed surfaces, that damage will be limited to the terminator - vs potentially leaking more sensitive data out of the tus process.

Refs: https://github.com/tus/tus-node-server/issues/22
