### ISSUE TITLE
Help stating wrong environment variables to configure Azure storage

### ISSUE THREAD

**Issue by meidlinga** [tus/tusd#660]
**Describe the bug**
`tusd -help` states `AZURE_ACCOUNT_NAME` and `AZURE_ACCOUNT_KEY` must be configured, if using `-azure-storage`.
The variables read are `AZURE_STORAGE_ACCOUNT`, respectively `AZURE_STORAGE_KEY`.

Full output:
```
 -azure-storage string
    	Use Azure BlockBlob Storage with this container name as a storage backend (requires the AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY environment variable to be set)
```

**Comment by Acconut** [comment]
Thank you for reporting!
