### ISSUE TITLE
Azure storage backend leaks information

### ISSUE THREAD

**Issue by meidlinga** [tus/tusd#661]
**Describe the bug**
Azure storage backend leaks information:
* The used client library including version
* The underlying error
* The Storage Account Name / URL
* X-Ms-Client-Request-Id
* X-Ms-Request-Id

Example:
```
-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.14.0/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====
Description=The specified blob does not exist.
RequestId:(*redacted for github issue*)
Time:2022-02-18T10:47:40.9444083Z, Details: 
   Code: BlobNotFound
   GET https://somecontainername.blob.core.windows.net/tusd/foo.info?timeout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.14 (go1.17.2; linux)]
   X-Ms-Client-Request-Id: [(*redacted for github issue*)]
   X-Ms-Date: [Fri, 18 Feb 2022 10:47:40 GMT]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 404 The specified blob does not exist.
   Content-Length: [215]
   Content-Type: [application/xml]
   Date: [Fri, 18 Feb 2022 10:47:40 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Client-Request-Id: [(*redacted for github issue*)]
   X-Ms-Error-Code: [BlobNotFound]
   X-Ms-Request-Id: [(*redacted for github issue*)]
   X-Ms-Version: [2020-04-08]
```

**To Reproduce**
1. Setup a storage account in Azure
2. Start tusd using Azure as Storage Backend
`./tusd -azure-storage=tusd`
3. Send HTTP GET to file upload endpoint
curl 'http://tusd:1080/files/foo'
4. Inspect the delivered response

**Expected behavior**
The response to the client should be general 404, or 500 Error.
It should not contain details about the used storage backend.
No details should be included.
Consistently with the local file upload it should return status 404 with string `upload not found`.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version:
```
./tusd -version
Version: v1.8.0
Commit: 48ffebec56fcf3221461b3f8cbe000e5367e2d48
Date: Fri Oct 29 09:32:00 UTC 2021
```
- Used tusd data storage: Azure Blob Storage
- Used tusd configuration: `./tusd -azure-storage=tusd`
- Used tus client library: curl

**Comment by Acconut** [comment]
Thank you for the detailed report. If I understand this correctly, Azure is returning a BlobNotFound error that we a not handling correctly and instead forward directly to the client. It's probably best to add special treatment for these situations to the error handling so that tusd returns the correct 404 response in this situation. Similar code already exists for the s3store: https://github.com/tus/tusd/blob/b47294267ae80e6cede255cb86a55529f1ab3bef/pkg/s3store/s3store.go#L481-L483

I don´t have Azure credentials, so I am not able to work on this on my own. @meidlinga, would you be interested in opening a PR for this?

@omBratteng Do you have any other insights or advice on this task?

**Comment by omBratteng** [comment]
@Acconut I will try to replicate it, and come with a fix

**Comment by Acconut** [comment]
@omBratteng Thank you very much!

**Comment by omBratteng** [comment]
I've reproduced it, and I'll get a fix sometime this week. Just got back from vacation, so lots to catch up with.

**Comment by meidlinga** [comment]
@Acconut , @omBratteng : Thanks for taking care of this so fast. Microsoft is giving free credit for Open Source Projects utilizing Azure. Maybe it could be worth to apply[1], so the Azure Storage backend can be covered in CI?

If I can help in any way, please notify me.

[1] https://opensource.microsoft.com/azure-credits#credits-apply

**Comment by omBratteng** [comment]
Thanks, was not aware of free credits for Open Source. I won't be using it for fixing this, as I already have the needed credentials.
