### ISSUE TITLE
tusd and Azurite

### ISSUE THREAD

**Issue by oahmadseecs** [tus/tusd#686]
**Question**
I am having trouble connecting my tusd server with Azurite. When I upload a file through Uppy, the logs are visible on tusd server, about write chunk started and upload finished, and file can be seen in the data directory. However no requests can be seen on the azurite server, and azure storage explorer also shows nothing. I am sure, I am missing something when starting tusd and configuring it to relay files to Azurite Blob Storage. Can anyone help? I can provide more information if required.

**Setup details**
- Operating System: Linux
- Used tusd version: 1.8.0
- Used tusd data storage: Azurite
- Used tusd configuration: -azure-endpoint=127.0.0.1:10000 
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
You are missing a configuration flag. Setting `-azure-endpoint` is not enough, as it will not enable the azurestore. For that you need to set `-azure-storage` and configure the environment variables:

> -azure-storage string
      Use Azure BlockBlob Storage with this container name as a storage backend (requires the AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variable to be set)
  -base-path string

**Comment by oahmadseecs** [comment]
Hi, thanks for the reply that helped, however facing a new error now. Could you please clarify what goes in -the azure-storage flag, can it be any string, or do I have to give it the "Azure BlockBob Storage" value? 
The error:
`
❯ ./tusd -azure-storage="Azure BlockBlob Storage" -azure-endpoint=127.0.0.1:1000
[tusd] 2022/03/21 16:15:27.916329 Using Azure endpoint 127.0.0.1:1000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc2d7b5]

goroutine 1 [running]:
github.com/tus/tusd/pkg/azurestore.NewAzureService(0xc0006bfc68)
        github.com/tus/tusd/pkg/azurestore/azureservice.go:119 +0x275
github.com/tus/tusd/cmd/tusd/cli.CreateComposer()
        github.com/tus/tusd/cmd/tusd/cli/composer.go:128 +0x6e5
main.main()
        ./main.go:16 +0x147
`

**Comment by Acconut** [comment]
No, the value of `-azure-storage` must be the name of the container that the uploads should be stored in.

**Comment by oahmadseecs** [comment]
So there wasn't a container on Azurite, I created one called files.
Environment variables:
```
❯ export | grep AZURE     
AZURE_STORAGE_ACCOUNT=devstoreaccount1
AZURE_STORAGE_KEY='Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
```
Proof that container exists...
![image](https://user-images.githubusercontent.com/46478321/159253101-0bd8c324-5f9f-495d-96b6-6a67f09dbc0b.png)

The error I am getting:
```
❯ ./tusd -azure-storage="files" -azure-endpoint=127.0.0.1:1000
[tusd] 2022/03/21 16:28:54.705456 Using Azure endpoint 127.0.0.1:1000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc2d7b5]

goroutine 1 [running]:
github.com/tus/tusd/pkg/azurestore.NewAzureService(0xc00063fc68)
        github.com/tus/tusd/pkg/azurestore/azureservice.go:119 +0x275
github.com/tus/tusd/cmd/tusd/cli.CreateComposer()
        github.com/tus/tusd/cmd/tusd/cli/composer.go:128 +0x6e5
main.main()
        ./main.go:16 +0x147

```

**Comment by Acconut** [comment]
The Azure endpoint needs to be a full URL, i.e. -azure-endpoint=http://127.0.0.1:1000

**Comment by oahmadseecs** [comment]
Thanks, that worked.
