### ISSUE TITLE
Write errors are ignored (chance for silent data loss)

### ISSUE THREAD

**Issue by nh2** [tus/tusd#698]
`tusd` is using the `defer file.Close()` pattern that can result in silent data loss of writes since it discards the return error of `Close()`:

https://github.com/tus/tusd/blob/3feef174fd14d71c121c8c263c33eb08312a9296/pkg/filestore/filestore.go#L158-L162

This means `tusd` will acknowledge a successful write to the TUS client, even if there is no certainy whether the write was successful.

This common Go idiom is frequently reported for being bad for safety:

* https://www.joeshaw.org/dont-defer-close-on-writable-files/
* https://groups.google.com/g/golang-nuts/c/7Ek7Uo7vSqU

It's known outside Go for a long time. `man 2 close` says:

```
   Dealing with error returns from close()
       A  careful programmer will check the return value of close(), since
       it is quite possible that errors on a previous  write(2)  operation
       are  reported only on the final close() that releases the open file
       description.  Failing to check the return value when closing a file
       may  lead  to silent loss of data.  This can especially be observed
       with NFS and with disk quota.
```

I think tusd should ensure to check for errors on `Close()`, and not return HTTP success codes on failures.

**Comment by Acconut** [comment]
Good point. Would you be willing to open a PR for this?

**Comment by nh2** [comment]
I'm not actually a Go expert, I just review code before use. I think it would probably be more effiecient for somebody who's proficient in Go to do it.

**Comment by mosi-kha** [comment]
HI
any updates?

**Comment by Acconut** [comment]
Not yet. But if you are interested in helping, feel free to open a PR.
