### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by Not-Wadu** [tus/tusd#738]
How the docker config in docker-compse.yml should look like?
And I can use these direct as a file server or I have to have something else besides these?

I have tried something like these, but something is wrong .

  tus-file-server:
    container_name: tus-upload-server
    image: tusproject/tusd
    ports:
      - "5040:5040"
    volumes:
      - "./tusd_data:tusd"

**Comment by Acconut** [comment]
I have never used Docker Compose, so I cannot help you much with its configuration. But what exactly do you mean by "something is worng"?

**Comment by Not-Wadu** [comment]
the volume is not accepted 

Error response from daemon: invalid volume specification: '/Users/mihaimatei/Work/test-staging-backend/tusd_data:tusd:rw': invalid mount config for type "bind": invalid mount path: 'tusd' mount path must be absolute

**Comment by Not-Wadu** [comment]
so is no documentation regarding how it suppose to be configured in Docker Compose.

**Comment by Acconut** [comment]
In https://github.com/tus/tusd/issues/408 someone has posted their configuration. Maybe that helps. But it seems as the cause of your error is stated in the error message:

> 'tusd' mount path must be absolute

Maybe try

> - "./tusd_data:/tusd"

**Comment by Not-Wadu** [comment]
there is a way to get the data type stored on the server without getting all the data ?
I tried with HEAD but I get these :
headers:
  cache-control: "no-store"
  content-length: "21675"
  tus-resumable: "1.0.0"

  upload-length: "21675"
  upload-metadata: "filename aW1nMi5qcGVn,filetype aW1hZ2UvanBlZw=="
  upload-offset: "21675"

**Comment by Acconut** [comment]
> there is a way to get the data type stored on the server without getting all the data ?

Yes, if you set the `filetype` metadata in your tus client during the upload creation.

> Or is possible to add the file extension at the end of the id created?

No, that is not possible currently.
