### ISSUE TITLE
s3store: Support AWS Go SDK v2

### ISSUE THREAD

**Issue by KatamariJr** [tus/tusd#752]
**Is your feature request related to a problem? Please describe.**
Currently the S3 interface accepted by s3store.New() matches the AWS Go SDK v1 S3 interface. The interface has changed in the newer AWS Go SDK v2.

**Describe the solution you'd like**
An s3v2store type that accepts a Go SDK v2 s3 client.

**Comment by Acconut** [comment]
Would there be a significant benefit from using the AWS SDK v2 over the current v1?

**Comment by Acconut** [comment]
Ok, great to hear that v2 and v1 can be used simultaneously. In this case, still using v1 is not an urgent problem. Thanks for bringing this up.

**Comment by Acconut** [comment]
This is implemented in #998 and will be included in the next major release.
