### ISSUE TITLE
Docker Container Over CPU Usage?

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#765]
**Question**
When I Started TUS Server Total CPU usage 4%, after 4,5 Uploads CPU Usage 7%, after many uploads 80%!! Why?
I'm using Same `Dockerfile` file  from Your Source.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: `Alpine 3.13 Linux`
- Used tusd version: `Latest`
- Used tusd data storage: `AWS S3`
- Used tusd configuration: ` CMD ["--s3-bucket","storage-bucket","--s3-endpoint","https://s3.eu-central-1.amazonaws.com","--s3-object-prefix","files","--s3-part-size","100663260","--max-size","2199023255552","--timeout","0","--port","1080","--hooks-http","https://example.com/tus-rqust.php","--hooks-http-retry","3","--hooks-http-backoff","2","--hooks-enabled-events","pre-create,post-create,post-finish,post-terminate","--behind-proxy","true","--expose-metrics","false","--verbose","false"] `
- Used tus client library: `tus-js-client`

**Comment by Acconut** [comment]
Does the high CPU usage persist long after the uploads have been completed? In production, we also see a high CPU usage from the AWS SDK and have tried many things to reduce it, but didn´t manage anything significant so far. So if you are uploading to S3 a higher CPU usage is currently normal.

**Comment by alameenlr** [comment]
I `AWS SDK v1` is the problem Could you Try with `github.com/aws/aws-sdk-go-v2/`
https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/

**Comment by Acconut** [comment]
> I think `AWS SDK v1` is the problem

How do you come to this conclusion? Is it mentioned that the AWS SDK v2 improved the performance?

The reason I am asking is that we tried out the Minio SDK in comparision to AWS SDK v1 and we did not see any improvements in performance. So we concluded that the AWS SDK v1 on its own is not likely the reason for high resource usages and replacing it would likely not change the situation.

**Comment by alameenlr** [comment]
From the link I mentioned above, saying this.

_The AWS SDK for Go v2 requires Go 1.15 or higher, and offers significant performance improvements in CPU and memory utilization over version 1._

**Comment by Acconut** [comment]
Ok, thank you. We will dedicate some time to checkout AWS SDK v2 soon.

**Comment by Acconut** [comment]
Closing in favor of https://github.com/tus/tusd/issues/752.
