### ISSUE TITLE
tusd example with behind proxy

### ISSUE THREAD

**Issue by G2G2G2G** [tus/tusd#781]
Currently the example https://github.com/tus/tusd/tree/master/examples/server seems to lack virtually every option the binary does, and not much info about how the binary works and no methods to build certain parts of it in the example.

Nearly 1/4th the issues posted here are proxy related, and I keep triggering this issue https://github.com/transloadit/uppy/issues/2285#issuecomment-632920770
and the best methods to config stuff seem to be block tusd and uppy and rewrite the headers aspects.

So how do I read the x-forward headers in the tusd example and respond with the location header that uppy uses?

**Comment by Acconut** [comment]
Thank you for this report, but I am a bit confused about what you are exactly doing.



> Currently the example https://github.com/tus/tusd/tree/master/examples/server seems to lack virtually every option the binary does

This example is intended as the minimal possible version to get tusd as a package running. Therefore, only the required options are used. I agree that could also benefit from more advanced examples. Was there anything specific that you were looking for?


> not much info about how the binary works and no methods to build certain parts of it in the example

Do you want to rebuild the functionality from the binary?

> Nearly 1/4th the issues posted here are proxy related, and I keep triggering this issue [transloadit/uppy#2285 (comment)](https://github.com/transloadit/uppy/issues/2285#issuecomment-632920770)
> and the best methods to config stuff seem to be block tusd and uppy and rewrite the headers aspects.

You are right that many users run into issues here. But often they missed to follow the instructions at https://github.com/tus/tusd/blob/master/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy. What error are you running into?

> So how do I read the x-forward headers in the tusd example and respond with the location header that uppy uses?

tusd will do this on its own if you configure it as mentioned in https://github.com/tus/tusd/blob/master/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy.

**Comment by G2G2G2G** [comment]
Yes I found that page, and read all of them. I wanted to incorporate tusd into my program while also using whatever the `-behind-proxy` does
There is no example or seemingly any info on what that is doing. I assume it's just a few lines of code reading the actual header.. but not clear on how to do that with that tusd example. That's all I want. The exact example but reads the IP same way that the -behind-proxy does

**Comment by Acconut** [comment]
> There is no example or seemingly any info on what that is doing. I assume it's just a few lines of code reading the actual header.. but not clear on how to do that with that tusd example. That's all I want. The exact example but reads the IP same way that the -behind-proxy does

The `-behind-proxy` flag is directly passed to the `RespectForwardedHeaders` in the config struct. That is all it does. Set this config value and you will have the same behavior as the binary:

https://github.com/tus/tusd/blob/3feef174fd14d71c121c8c263c33eb08312a9296/cmd/tusd/cli/serve.go#L29

> I think that's pretty unique flag of the program, as many of the others are event based and you'd do something in the for loop there, with that handler and the event etc..

Not sure I understand that entirely. The example contains a section for handling events:

https://github.com/tus/tusd/blob/3feef174fd14d71c121c8c263c33eb08312a9296/examples/server/main.go#L39-L48

Was this not sufficient for you?

**Comment by G2G2G2G** [comment]
Yes the event parts I specifically said I understood

Thanks for the config link
