### ISSUE TITLE
S3Store: Deferred length is partly broken in v1.9.1

### ISSUE THREAD

**Issue by acj** [tus/tusd#798]
**Describe the bug**

When using the S3 backend, declaring the length of an upload after tusd has received all the bytes results in an empty object in S3.

**To Reproduce**
1. Run tusd v1.9.1
2. Start an upload for small file without declaring its length
3. Upload the entire file
4. Declare the length
5. Download the file from S3

**Expected behavior**

The object in S3 has the expected size and content.

**Actual behavior**

The object in S3 is empty.

**Discussion**

I think the relevant factors here are:
1) S3Store is being used
2) Defer-length extension is being used
3) Length is declared after all the bytes have been received by tusd (so `maxSize == 0` in the handler, and we skip the call to `WriteChunk`)

tusd seems to receive all of the bytes and marks the upload as finished. However, the `.part` file is still in S3 (it should have been deleted), and the actual object for the upload is empty. Here is a sanitized `.info` file from one of my uploads:

```json
{
	"ID":"abcd",
	"Size":4732723,
	"SizeIsDeferred":false,
	"Offset":4732723,
	"MetaData":{},
	"IsPartial":false,
	"IsFinal":false,
	"PartialUploads":null,
	"Storage":{
		"Bucket":"my-test-bucket",
		"Key":"test-upload",
		"Type":"s3store"
	}
}
```

The size and offset are correct, size is no longer deferred, and an object exists in S3 (so the multipart upload is complete).

I tried to write an S3Store test for this, but the issue seems to be in `unrouted_handler.go` and not in S3Store itself.

I think this bug was introduced in #746. Without leaking S3Store implementation details to the handler, I don't know how we could safely skip the `WriteChunk` call.

**Comment by Acconut** [comment]
Thanks for the report! Did this work properly in prior versions? I thought that we paid enough attention to uploads with deferred lengths in #746, but maybe we weren't careful enough. So the problem is we have a `.part` object in S3. Normally this object would get turned into a part for the S3 mulitpart upload by `WriteChunk`, but we skip this call. An `FinishUpload` does not check if a `.part` object is around before completing the multipart upload. Is this correct?

**Comment by acj** [comment]
> Did this work properly in prior versions?

It did. Our workaround was to revert to 1.9.0.

> So the problem is we have a `.part` object in S3. Normally this object would get turned into a part for the S3 mulitpart upload by `WriteChunk`, but we skip this call. An `FinishUpload` does not check if a `.part` object is around before completing the multipart upload. Is this correct?

Yes, that's my understanding of the bug.

**Comment by Acconut** [comment]
Thank you for the help. For now, I have reverted the PR, so v1.9.2 should work again. Maybe in the future we should check for `.part` files in the `FinishUpload` method.
