### ISSUE TITLE
[FEATURE REQUEST] Docker Secrets to read sensitive information from

### ISSUE THREAD

**Issue by renepardon** [tus/tusd#799]
**Is your feature request related to a problem? Please describe.**
I would like to use Docker Secrets to store my MINIO/AWS credentials. Therefore I created a Docker Secret at **/run/secrets/aws-access-key** and **/run/secrets/aws-key-id**
But there are no environment variables available as for other Docker images to load those secretes from corresponding file. E.g. https://hub.docker.com/r/bitnami/redis has **REDIS_PASSWORD_FILE** in addition to **REDIS_PASSWORD** to load this Docker Secret.

**Describe the solution you'd like**
I would like to have the environment variable **AWS_ACCESS_KEY_ID_FILE** and **AWS_SECRET_ACCESS_KEY_FILE** available to load the secret from Docker rather than from environment variables. Which makes it more secure against accidental exposure.

**Can you provide help with implementing this feature?**
If you tell me where and how to implement it, I would be happy to provide a pull request.

**Comment by Acconut** [comment]
Interesting approach. I have never heard of this before.

> E.g. https://hub.docker.com/r/bitnami/redis has **REDIS_PASSWORD_FILE** in addition to **REDIS_PASSWORD** to load this Docker Secret.

Do you know how this is implemented? Is this a feature in the Redis binary or a feature of the used Docker image (i.e. the corresponding file is read before starting Redis)?

**Comment by renepardon** [comment]
@Acconut i saw this already in multiple images like rabbitmq, MariaDB etc.

More details about Docker secrets: https://docs.docker.com/engine/swarm/secrets/

More example images using this approach already:
- https://hub.docker.com/_/rabbitmq
- https://hub.docker.com/_/mongo

And lot more. 

It’s part of the init script to read the secret and pass it to the correct destination.

**Comment by Acconut** [comment]
Ok. Then feel free to open a PR, if you want to. We don't use docker, so I cannot work on this on my own.

**Comment by renepardon** [comment]
@Acconut done :)
