### ISSUE TITLE
Forwarded request header with double quotes returns incorrect Location response header

### ISSUE THREAD

**Issue by tbnguyen1407** [tus/tusd#809]
**Describe the bug**

A `Forwarded` request header with double quoted `host` value will result in invalid `Location` header with quoted value

**To Reproduce**
1. start server with behind proxy config
2. send POST request with `Forwarded` header containing double quoted value
3. observe response with invalid `Location` header

```
## request headers
Forwarded: for=192.168.10.112;host="upload.example.tld:8443";proto=https
## response headers
Location: https://"upload.example.tld:8443"/files/some-fileid
```

**Expected behavior**

Quotes are valid according to https://datatracker.ietf.org/doc/html/rfc7239 and should be stripped when forming `Location` response header.

**Setup details**

Any setup.

**Comment by Acconut** [comment]
That seems to be the case, thanks for reporting! We currently extract this information using regular expressions:

https://github.com/tus/tusd/blob/7e6cd89114b43900c6b3d871f1b75b4fd16bed0c/pkg/handler/unrouted_handler.go#L22-L23

As you can see, they do not consider quotes at all. It should be easy to add support for quotes. Would you be willing to open a PR for this?

**Comment by tbnguyen1407** [comment]
@Acconut I am not familiar with PR/MR thing. I think you can simply strip the quotes after parsing

https://github.com/tus/tusd/blob/7e6cd89114b43900c6b3d871f1b75b4fd16bed0c/pkg/handler/unrouted_handler.go#L1053

to

```
host = strings.Trim(r[1], "\"")
```

Same should be done for `proto`

**Comment by Acconut** [comment]
I just adjusted the regexp for extracting the hostname, so this should be fixed in the next release. Thanks for reporting it!
