### ISSUE TITLE
Enhance metadata in gRPC Hooks

### ISSUE THREAD

**Issue by jonaskaltenbachz** [tus/tusd#811]
Hello,

is there a possibility to enhance the metadata object by an additional field in the pre-create gRPC Hook?
Or is there any other possibility to add some metadata automatically?

Many greetings
Jonas

**Comment by Acconut** [comment]
No, there currently exists no method for modifying the metadata of an upload. Neither using gRPC nor any other hook method. However, I am thinking about allowing this for the pre-create hook in the future.

**Comment by jonaskaltenbachz** [comment]
All right, I understand. 
I have created a pull request that enables the described functionality: https://github.com/tus/tusd/pull/814

**Comment by jonaskaltenbachz** [comment]
Hello, 
I just wanted to ask if there is an update on this topic.

Many greetings,
Jonas

**Comment by Acconut** [comment]
Hi Jonas, please see #814 for my response :)

**Comment by jonaskaltenbachz** [comment]
Hello,
I just wanted to ask if there is an update on this topic.

Many greetings,
Jonas

**Comment by Acconut** [comment]
Unfortunately, there has been no work performed on this in the recent months.

**Comment by jonaskaltenbachz** [comment]
Thank you for your answer @Acconut 
I prepared the pull request in https://github.com/tus/tusd/pull/814. Do you saw this too? From my point of view it should be ready to merge.

Best regards,
Jonas

**Comment by Acconut** [comment]
I am closing this issue since we now have a PR that tracks progress on this: https://github.com/tus/tusd/pull/962.
