### ISSUE TITLE
Consuming upload-data as a stream

### ISSUE THREAD

**Issue by mshunjan** [tus/tusd#824]
**Question**

I'm currently working on a project where we analyze files in chunks, as they are being uploaded. I would like to be able to consume the upload data from a tusd server, as it is being uploaded. Is this possible with tusd?

**Setup details**

Essentially I am using a client-server architecture, where my client slices an upload file and then sends that data to the server in chunks. We have certain metadata attached to the request that allows us to track or resume these uploads. Overall, it's not that robust, and I am looking to replace this using a client side tus library, and a tusd server. I would like for my api client to consume data from the tusd data store as it is coming in. 

**Possible Implementation** 
I'm wondering if I could use the post-create hook to signal my api that the upload has been created, and then consume from a `tail -f filename` process?

**Comment by Acconut** [comment]
tusd is not design for consuming the uploaded data while the upload is still in progress. You might be able to pull this off by watching the file as you mentioned, but this comes with its own set of challenges. Namely that an upload might be interrupted for some time. During this break, no data will obviously be written to the file, although you could use the post-receive hook to detect upload activity again.

In general, it is probably possible but I am not sure if such a system is a very robust and flexible one. We do not have plans to add explicit support for consuming uploads as streams so far.
