### ISSUE TITLE
CORS error: TUS upload having incorrect HOST in response Location header 

### ISSUE THREAD

**Issue by jeen-github** [tus/tusd#828]
**Question**
I'm using  `"tus-js-client": "^2.3.2"` in angular application to upload a file to tus server build via tus helm chart. 

I'm getting CORS error when i'm availing parallelUpload feature

`Access to XMLHttpRequest at 'https://local.foresight.com/files/3b30e3ee6860f55387e7e31ca98de358+7dbb7a17-059a-4809-8d1f-b04c76efc88e' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

Wondering how https://local.foresight.com is injected to upload URL in response **Location header** for /files request.

How can I have partial upload URL build out of host from the /files request to avoid this CORS
 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/31023508/195933795-6db2bc3b-92d7-4eb0-bac0-d53ea6ff5279.png">

**i.e**  http://localhost:4200/files/3b30e3ee6860f55387e7e31ca98de358+7dbb7a17-059a-4809-8d1f-b04c76efc88e

Please advise. Let me know if you need more info

<img width="629" alt="image" src="https://user-images.githubusercontent.com/31023508/195932901-4ea6aad0-f4bc-44a2-a907-6eeb13ffe76e.png">

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: [macOS]
- Used tusd version: [ v1.9.0]
- Used tusd data storage: [AWS S3]
- Used tusd configuration: `
helmCharts:
  - name: tusd
    repo: https://charts.sagikazarmark.dev
    version: 0.0.12
    releaseName: tusd
    valuesInline:
      containerArgs:
        - -s3-endpoint
        - http://minio:9000
        - -s3-bucket
        - data-uploads
        - -behind-proxy
        - --hooks-http
        - http://data-upload-service:8080/hook
        - --hooks-enabled-events
        - post-finish
        - --hooks-http-forward-headers
        - x-group,authorization,x-token-user-email
        - --hooks-http-retry=1
      envFrom:
        - secretRef:
            name: tusd-secret
      env:
        AWS_REGION: required-but-unused
      image:
        repository: harbor-preprod.test.com/library/external/tusproject/tusd
        tag: v1.9.0`
- Used tus client library: [tus-js-client]

**Comment by Acconut** [comment]
Did you follow all steps in https://github.com/tus/tusd/blob/master/docs/faq.md#can-i-run-tusd-behind-a-reverse-proxy to configure your proxy?

**Comment by Acconut** [comment]
> How can I have partial upload URL build out of host from the /files request to avoid this CORS
> **i.e** http://localhost:4200/files/3b30e3ee6860f55387e7e31ca98de358+7dbb7a17-059a-4809-8d1f-b04c76efc88e

I also do not understand this question. Please elaborate more.

**Comment by jeen-github** [comment]
Many thanks @Acconut for your quick turnaround. 

I'm able to override the hostname with `X-Forwarded-Host` header but failed to override protocol 'http' with `X-Forwarded-Proto` header for local development. 

`    
'X-Forwarded-Host': 'localhost:4200',
'X-Forwarded-Proto': 'http'
`

<img width="524" alt="image" src="https://user-images.githubusercontent.com/31023508/196266699-3f26dd14-7535-40b5-b290-50c8e0a26435.png">

Assist me on this please

**Comment by Acconut** [comment]
To be honest, I am confused about your setup. You have your angular running at localhost:4200 and the tusd server at local.foresight.com. In front of tusd is some kind of proxy (which one?). Is this correct?

In this case, you need to configure the proxy to set the X-Forwarded-* or Forwarded header, so tusd knows which host and protocol the clients uses to access it through the proxy. Note: basically in your case this should be `X-Forwarded-Host: local.foresight.com` and `X-Forwarded-Proto: https`, not localhost:4200.

In addition, tusd takes care of setting the correct CORS headers on its own. You do not need to do anything here normally. Just make sure that your proxy lets through all of the CORS request and responses to tusd. See https://github.com/tus/tusd/blob/8664d8c484f07472bc8c7b29e207b6e2e63ace8a/pkg/handler/unrouted_handler.go#L220-L242

**Comment by jeen-github** [comment]
@Acconut  what you said is true, I have angular running at localhost:4200 and the tusd server in azure k8s at local.foresight.com behind ambassador. For some reason i am not able to override protocol using X-Forwarded-Proto but was able to override using **Forwarded** header and CORS error got cleared.

Many thanks for your prompt responses. Much appreciated.
