### ISSUE TITLE
tus client for Go

### ISSUE THREAD

**Issue by alexandrevicenzi** [tus/tusd#83]
Hi @Acconut, as mentioned I made a version of tus client for go lang.

It was tested with 1.6, 1.7 and 1.8 (tip).

The code can be found in [github.com/eventials/go-tus](https://github.com/eventials/go-tus).

Feel free to check out, comment, or even send a PR. The lib was based a little in the JS version, but I want to add more features soon.

**Comment by Acconut** [comment]
Congratulations, this looks really, really well. However, I noticed that you require require a filename to determine what it going to be uploaded. In some cases, one would wish to upload even if it's not stored on disk, e.g. the body of a HTTP request. The tus-js-client, for example, allows you to pass a readable stream to it (see https://github.com/tus/tus-js-client#new-tusuploadfile-options).

**Comment by alexandrevicenzi** [comment]
Oh, I see. Well, I could take a look and use an io Reader or even a byte buffer.

**Comment by alexandrevicenzi** [comment]
@Acconut I changed the library, it's almost a new one. Take a look.

**Comment by Acconut** [comment]
I like your outdated version even more, congratulations on it :+1: I can see a few similarities to the Java library :) Do you want me to feature it on the list of implementations (http://tus.io/implementations.html)?

**Comment by alexandrevicenzi** [comment]
@Acconut It's similar the Java version :) and also the Python version. I took the inspiration from they this time.

Feel free to list in the tus.io site.

**Comment by Acconut** [comment]
Just added your project to the list (see Client section on http://tus.io/implementations.html). Let me know if it's ok that I used the name of the Github organization as the author :)

**Comment by alexandrevicenzi** [comment]
@Acconut Thanks.

@gfronza is it ok to use Eventials name right?
