### ISSUE TITLE
How to distinguish http hooks

### ISSUE THREAD

**Issue by arrowcircle** [tus/tusd#835]
**Question**
Hi! I am trying to understand what hook I received, but post-receive and post-finish HTTP hooks looks exactly the same.
What is the proper way of understanding what hook is sent?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: macOS
- Used tusd version: v1.9.2
- Used tusd data storage: Local minio S3
- Used tusd configuration: `tusd -upload-dir tmp/tusd -s3-endpoint="http://localhost:9000" -s3-bucket=tusd --hooks-http http://localhost:3000/api/v1/tusd -s3-disable-ssl -hooks-http-forward-headers --hooks-enabled-events=pre-create,post-create,post-finish,post-terminate`
- Used tus client library: curl

**Comment by Acconut** [comment]
Have a look at the Hook-Name request header, as mentioned in https://github.com/tus/tusd/blob/master/docs/hooks.md#usage.
