### ISSUE TITLE
Running tusd in Google Cloud Run with GCS

### ISSUE THREAD

**Issue by drummer3333** [tus/tusd#864]
**Question**
I'm trying to run tusd as golang package as a Container on Google Cloud Run with GCS as Storage Backend. 
A normal upload gets throught without a Problem. 

- But when I pause the Upload and resume it, it begins from 0%. Even If I use Filestore, so the problem musst be the google reverse proxy:
  - on Resume I get a OPTIONS Request with status 200, and a HEAD Request with status 404 to /upload/<hash>
  - followed from OPTION (200) and POST with 201 to /upload
- When I configure 5 Paralelle Uploads it is completely wild, but only if I use GCS as Storage:
  - At first all seems functioning to 100% but drops down to 20%
  - trys to upload the missing parts, complains about "missing or invalid Upload-Length header"

Paralell Uploads is only nice to have, but I need resume to work. 
- I assume Google Frontend Proxy blocks a specific Header entry, but I could not find I in my research. Only thing I Saw, that all Header Keys are converted to lowercase, should not break anything, but could.
- If paralell Uploads are not possible with GCS, can I disable them on the server side?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux Container on Google Cloud Run
- Used tusd version: 1.10.0
- Used tusd data storage: Google Cloud Storage / File
- Used tusd configuration: 
		BasePath:                
		StoreComposer:           composer with locker,(filestore with filelocker, GCS with memlocker)
		DisableDownload:         true,
		NotifyCompleteUploads:   true,
		NotifyTerminatedUploads: true,
		NotifyUploadProgress:    true,
		NotifyCreatedUploads:    true,
		RespectForwardedHeaders: true,
- Used tus client library: Uppy.js

**Comment by Acconut** [comment]
Apologies for the delay. It sounds to me like the proxy from Google Cloud Run is buffering the request before sending it to your container. Maybe you can research into that. I think that the same is also happen when you use AWS Lambda.

Then you can either try to disable this buffering, or use the chunkSize option of tus-js-client/Uppy and split the upload into multiple requests.
