### ISSUE TITLE
tusd verification / authorization before start upload

### ISSUE THREAD

**Issue by kevin-openc** [tus/tusd#88]
hi all, just wondering if it is possible to do some customize verification / authorization before tusd start receive the file from client? I am just confusing if this would cause a security problem if some one get the endpoint and upload files onto the server, and cause potential attacks to the server.

except security enhancement for the destination folder (like put the destination outside web server folder), is it possible to do some action before start? or the security should be considered after the file is uploaded?

thanks.

**Comment by Acconut** [comment]
> just wondering if it is possible to do some customize verification / authorization before tusd start receive the file from client?

That's absolutely possible. Please have a look at the hook system (https://github.com/tus/tusd/blob/master/docs/hooks.md), in particular, the `pre-create` event.

> I am just confusing if this would cause a security problem if some one get the endpoint and upload files onto the server, and cause potential attacks to the server.

Using the hook mentioned above, you can ensure that only files matching your criteria are uploaded.

> except security enhancement for the destination folder (like put the destination outside web server folder), is it possible to do some action before start? or the security should be considered after the file is uploaded?

I am not aware of any additional security measurements which must be taken before beginning the upload. tusd will ensure that the files are stored using restrictive permissions, disallowing it to be executed (see https://github.com/tus/tusd/blob/master/filestore/filestore.go#L31)

**Comment by kevin-openc** [comment]
hi, thanks for your effort! this hook is useful!

**Comment by kvz** [comment]
I feel this would be nice to add to the FAQ as well https://github.com/tus/tusd#faq

**Comment by Acconut** [comment]
@kvz Good idea, done in https://github.com/tus/tusd/commit/af5e0e834d80b6ae83e58ee95f3bac84817429b0
