### ISSUE TITLE
Rejecting Content-Length 0

### ISSUE THREAD

**Issue by jdcalvin** [tus/tusd#910]
**Question**
I do not see a config option, or anything in `unrouted_handler` about rejecting `Content-Length` 0 `PATCH` requests. I'm wondering if theres any valid reason for accepting these requests, and if theres any consideration for modifying the protocol for rejecting this type of request?

Reason I ask is I'm seeing edge case behavior with companion where URL uploads are making tus client requests with 0 body length repeatedly. Related question here: https://community.transloadit.com/t/how-to-abort-hanging-companion-uploads/16488

Edit: To clarify, this is not instances where `Content-Length` is missing, but is `0.` I do see there are considerations for where this can be missing, but it appears it only should apply if the config option `SizeIsDeferred` is enabled. We have that option disabled and all uploads for our use case send along the `Upload-Length` header.
https://github.com/tus/tusd/blob/main/pkg/handler/unrouted_handler.go#L604-L606

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: [e.g. Linux, Windows, macOS]
- Used tusd version: [can be obtained by running `tusd -version`]
- Used tusd data storage: [e.g. disk store, AWS S3, Google Cloud Storage]
- Used tusd configuration: [what arguments are you using to invoke `tusd`?]
- Used tus client library: [e.g. tus-js-client, tus-java-client, TUSKit, Uppy.js]

**Comment by mifi** [comment]
Created a PR here for a potential client side solution: https://github.com/tus/tus-js-client/pull/556

**Comment by Acconut** [comment]
There is no option to reject such requests. The specification does not disallow them and as such servers must support them.

Yes, clients should avoid sending empty request, but that is a bug that should be fixed in the client and not through a rejection by the server.

@mifi thank you, I will look into your PR soon.
