### ISSUE TITLE
The hook file in hooks-dir cannot be executed

### ISSUE THREAD

**Issue by zg-caowb** [tus/tusd#920]
**Describe the bug**
fork/exec /srv/tusd-hooks/post-finish: no such file or directory

```
Command returns the Cmd struct to execute the named program with the given arguments.

It sets only the Path and Args in the returned structure.

If name contains no path separators, Command uses LookPath to resolve name to a complete path if possible. Otherwise it uses name directly as Path.

The returned Cmd’s Args field is constructed from the command name followed by the elements of arg, so arg should not include the command name itself. For example, Command(“echo”, “hello”). Args[0] is always name, not the possibly resolved Path.

On Windows, processes receive the whole command line as a single string and do their own parsing. Command combines and quotes Args into a command line string with an algorithm compatible with applications using CommandLineToArgvW (which is the most common way). Notable exceptions are msiexec.exe and cmd.exe (and thus, all batch files), which have a different unquoting algorithm. In these or other similar cases, you can do the quoting yourself and provide the full command line in SysProcAttr.CmdLine, leaving Args empty.
```
cmd := exec.Command( hookPath)

should:
cmd := exec.Command("bash", hookPath)

**To Reproduce**
1. Execute command '...'
2. Start upload '....'
3. See error

**Expected behavior**

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: [e.g. Linux, Windows, macOS]
- Used tusd version: [can be obtained by running `tusd -version`]
- Used tusd data storage: [e.g. disk store, AWS S3, Google Cloud Storage]
- Used tusd configuration: [what arguments are you using to invoke `tusd`?]
- Used tus client library: [e.g. tus-js-client, tus-java-client, TUSKit, Uppy.js]

**Comment by Acconut** [comment]
I disagree, the hooks have always worked for us like that. Make sure that the file is executable and that you have defined an interpreter using a hashbang: https://github.com/tus/tusd/blob/4a46cf667e10a87ad77ad5124e3adb0eeb2041c5/examples/hooks/post-create#L1

**Comment by zg-caowb** [comment]
@Acconut Thank you, I did not `chmod +x ` the file
