### ISSUE TITLE
Please bump the golang.org/x/sys dependency

### ISSUE THREAD

**Issue by clausecker** [tus/tusd#923]
The version of golang.org/x/sys this package transitively depends on is too outdated to support recent platforms such as riscv64-freebsd.  Please bump the dependency to enable a build on such platforms.

**Comment by Acconut** [comment]
How do we update a transitive dependency? It is not in our go.mod: https://github.com/tus/tusd/blob/main/go.mod. Can you open a PR for this?

**Comment by clausecker** [comment]
Simply do

    go get golang.org/x/sys@latest

and then optionally

    go mod tidy

**Comment by Acconut** [comment]
Thank you. The package should not require at least 0.6. Let me know if there are still problems for you.
