### ISSUE TITLE
HTTPS Resumable Issue

### ISSUE THREAD

**Issue by Craytor** [tus/tusd#93]
Hello everyone!

First thing, amazing project! I've been trying to find something like this for quite some time.

That leads me to my issue. I'm trying to integrate this into a site that requires SSL, so I read the FAQ and it said it is indeed possible. I then looked at the configuration that you are using at https://tus.io/demo.html and tried to integrate it into my setup. I have replaced my domain with "myexampledomain.com" for various reasons.

In my Nginx configuration, I have:
```
        # Forward incoming requests to local tusd instance
        proxy_pass http://myexampledomain.com:1080;

        # Disable request and response buffering
        proxy_request_buffering  off;
        proxy_buffering          off;
        proxy_http_version       1.1;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host $hostname;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header         Upgrade $http_upgrade;
        proxy_set_header         Connection "upgrade";
        client_max_body_size     0;
```

In my uploader JS, I have:
```
this.file = document.getElementById('video').files[0];

                // Create a new tus upload
                var myUpload = new this.tus.Upload(this.file, {
                    endpoint: "https://myexampledomain.com/files/",
                    resume: false,
                    retryDelays: [0, 1000, 3000, 5000],
                    uploadSize: this.file.size,
                    onError: function(error) {
                        console.log("Failed because: " + error)
                    },
                    onProgress: function(bytesUploaded, bytesTotal) {
                        var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
                        console.log(bytesUploaded, bytesTotal, percentage + "%")
                    },
                    onSuccess: function() {
                        console.log("Download %s from %s", myUpload.file.name, myUpload.url)
                    }
                })

                // Start the upload
                myUpload.start()
```

I'm able to start an upload, and it will upload until I turn off my internet. Once I turn of my internet, I get the following errors in my console:
![untitled](https://cloud.githubusercontent.com/assets/3680866/21952438/8d435320-d9ea-11e6-9a8e-4040485b921a.png)

So it looks like when I disconnect my internet, it "still tries to upload". When I tested this with the https://tus.io/demo.html site, it would pause basically and continue uploading after you reconnect your internet.

Any suggestions and help would definitely be appreciated! Thanks!

**UPDATE:**
I've tested using the https://master.tus.io/files as an endpoint and it works fine, so it's leading me to believe I have something wrong with running tusd on the server. Am I suppose to run it using ```./tusd -behind-proxy``` or is ```./tusd``` good enough? Also, when I run it using ```./tusd -behind-proxy``` I get the host name of the server as the file url request, which is not right in my instance.

Finally, could it be an issue with the setup of my Nginx file?

Thank you!

**Comment by Acconut** [comment]
After some debugging we figured out that this is due some inconsistency inside Chrome: If you disconnect from your network while a HTTP/1.1 request is running, the request will not be immediately be interrupted. However, if the transportation is using HTTP/2, an error will be emitted instantly. The question is now whether tus-js-client should abort an running HTTP request if it detects that the network has been disconnected to mimic similar behavior?

**Comment by kvz** [comment]
There was an update on the OP

**Comment by Acconut** [comment]
Thank you, Kevin. I actually wrote my comment after @Craytor's edit. We debugged this issue together in the Slack channel, so that's the current state :)

**Comment by kvz** [comment]
Ah okay, great :)

**Comment by Acconut** [comment]
Closing this issue since we solved it, as far as I know. Please correct me if I am wrong :)
