### ISSUE TITLE
HOST header is not included in (HTTP) hooks POST data.

### ISSUE THREAD

**Issue by slide333333** [tus/tusd#935]
**Describe the bug**
HOST header is not included in (HTTP) hooks POST data.

**To Reproduce**
1. Enable post-create hook and upload a file using whatever client

**Expected behavior**
HOST header should be included either under the HttpRequest object or the HttpReuqest["Header"] object in the POST data.

**Setup details**
Please provide following details, if applicable to your situation:
- Used tusd version: 1.19.2

I'm not a Go developer, but I think the problem is that (according to the Go documentation here https://cs.opensource.google/go/go/+/refs/tags/go1.20.3:src/net/http/request.go;l=157) the Host header is not part of the Request.Header field, but promoted to a separate field Request.Host, which is not considered anywhere in the code.

The [hooks documentation](https://github.com/tus/tusd/blob/main/docs/hooks.md) is also wrong. It shows the Host header included unter the "Header" object.

**Comment by Acconut** [comment]
Good catch, I wasn't aware of this special handling for the Host header. I think we should add it back to the header map, so that hooks can access it. Are you able to open a PR for this?

**Comment by slide333333** [comment]
@Acconut : I'm not a Go developer. Would appreciate if a Go developer could take over.
