### ISSUE TITLE
Missing linux_arm64 binaries for v1.11.0

### ISSUE THREAD

**Issue by TrueBrain** [tus/tusd#960]
**Describe the bug**
https://github.com/tus/tusd/releases/tag/v1.11.0 doesn't list any linux_arm64 builds, while https://github.com/tus/tusd/releases/tag/v1.10.1 does. This makes updating to 1.11 a bit tricky :)

**To Reproduce**
See above.

**Expected behavior**
To also have access to prebuild arm64 binaries for Linux. If this could be fixed, that would be much appreciated. Thank you!

**Setup details**

**Comment by TrueBrain** [comment]
Nevermind, I am a peanut, and the interface was playing tricks on me. Nothing to see here. I blame GitHub UI :P

**Comment by Acconut** [comment]
Glad to read that you found it :)
