### ISSUE TITLE
Options returns 200 instead of 204

### ISSUE THREAD

**Issue by alexandrevicenzi** [tus/tusd#97]
The protocol says:

> An OPTIONS request MAY be used to gather information about the Server’s current configuration. A successful response indicated by the 204 No Content status MUST contain the Tus-Version header. It MAY include the Tus-Extension and Tus-Max-Size headers.

But tusd returns 200. It should be 204 right?

**Comment by Acconut** [comment]
I will refer to the corresponding code for an explanation: https://github.com/tus/tusd/blob/master/unrouted_handler.go#L169-L177
However, it may be worth adapting the specification to allow this scenario.

**Comment by alexandrevicenzi** [comment]
@Acconut so, it returns 200 because some old browsers?

I agree with 204 is better because it has no content at all. I think Presto is dead, Opera uses Blink now. Not sure what browsers fail on 204, but for sure if they fail they are not a good option to use 😂 

The spec could allow 200 or 204 for return, as the HEAD request returns 403, 404 and others if the file was not found.

**Comment by Acconut** [comment]
> so, it returns 200 because some old browsers?

Yes. Even if you consider this browser old and outdated, there are still people using it mostly outside of the western world (see http://raddevon.com/articles/where-are-opera-mini-users) and I would like to not exclude them. Since there is no downside of returning a different response code for OPTIONS request, I would not be pleased to change this behavior.

> The spec could allow 200 or 204 for return, as the HEAD request returns 403, 404 and others if the file was not found.

I absolutely agree.

**Comment by alexandrevicenzi** [comment]
I'm impressed by Opera Mini. Anyway, I think changing the spec is the better solution here.

**Comment by Acconut** [comment]
The corresponding paragraph in the specification has been adapted to allow the 200 OK status. :)
