### ISSUE TITLE
problem with locks (error 423, 500) when accessing stored files

### ISSUE THREAD

**Issue by hrvoj3e** [tus/tusd#984]
**`tusd` version**
```
Version = v1.12.1
GitCommit = a2ae9167621dd230cefdbbd04fef3448a54eba11
BuildDate = Tue Jul 25 17:08:51 UTC 2023
```
Client: Uppy JS 1.21.2

**Question**
We are getting very often errors (423, 500) when trying to download files from tus.
We have been using default endpoint `/files/` for GET requests via Curl.

code 423
```
file currently locked
```

code 500
```
open /srv/data/306161e54585a3bccc6fca5d14ed582c.lock: no such file or directory
```

Upon [reading this](https://github.com/tus/tusd/issues/466) my understanding is that locks are also used on `GET` and this is a problem. 
You have [suggested](https://github.com/tus/tusd/issues/466#issuecomment-802735562) to use another way to serve files (e.g. Nginx).

 - Can we expect more problems with locks if we use a proxy server?
 - Can we download from another service an uploaded file right away? Or should we wait N seconds?
   - context: after tus client gets a hash from tus server we are triggering another service to download this file to our storage
- How long does it stay locked after tus client returns a hash?

**Issues**
https://github.com/tus/tusd/issues/466
https://github.com/tus/tusd/issues/335

**Comment by Acconut** [comment]
> Upon [reading this](https://github.com/tus/tusd/issues/466) my understanding is that locks are also used on `GET` and this is a problem.
> You have [suggested](https://github.com/tus/tusd/issues/466#issuecomment-802735562) to use another way to serve files (e.g. Nginx).

Yes, tusd is intended for receiving uploads, but not for serving content. You should either access the content directly (e.g. on S3) or use a proxy to serve it from disk.

> * Can we expect more problems with locks if we use a proxy server?

No. Proxies do not care about tusd's internal locks, so you will not see any error about locks from them.

> * Can we download from another service an uploaded file right away?

Once the last PATCH request got a 2XX response, the file is ready to be used. In tus-js-client, this is communicated using the onComplete handler. There should be a similar event in Uppy.

> * How long does it stay locked after tus client returns a hash?

I don't know what you mean by hash. Is it the upload URL? tusd keeps the lock whenever it thinks there is an active request for the upload. So when the request completes or times out, the lock is released.

**Comment by hrvoj3e** [comment]
Thanks for clarification.
We have setup Nginx as proxy and avoided error 423.

About "hash" - Yes, I referenced upload URL `/files/<hash>`.

**Comment by aixj1984** [comment]
I have provided a modification method, the specific modification point is :
pkg/handler/unrouted_handler.go

`
func (handler *UnroutedHandler) GetFile(w http.ResponseWriter, r *http.Request) {
	c := handler.getContext(w, r)

	id, err := extractIDFromPath(r.URL.Path)
	if err != nil {
		handler.sendError(c, err)
		return
	}
	c.log = c.log.With("id", id)

	upload, err := handler.composer.Core.GetUpload(c, id)
	if err != nil {
		handler.sendError(c, err)
		return
	}

	info, err := upload.GetInfo(c)
	if err != nil {
		handler.sendError(c, err)
		return
	}

	 // If the file is not finished uploading, downloading can be locked, but if it has already been downloaded, it will not be locked.
	if handler.composer.UsesLocker && info.Size != info.Offset {
		lock, err := handler.lockUpload(c, id)
		if err != nil {
			handler.sendError(c, err)
			return
		}

		defer lock.Unlock()
	}

	contentType, contentDisposition := filterContentType(info)
	resp := HTTPResponse{
		StatusCode: http.StatusOK,
		Header: HTTPHeader{
			"Content-Length":      strconv.FormatInt(info.Offset, 10),
			"Content-Type":        contentType,
			"Content-Disposition": contentDisposition,
		},
		Body: "", // Body is intentionally left empty, and we copy it manually in later.
	}

	// If no data has been uploaded yet, respond with an empty "204 No Content" status.
	if info.Offset == 0 {
		resp.StatusCode = http.StatusNoContent
		handler.sendResp(c, resp)
		return
	}

	src, err := upload.GetReader(c)
	if err != nil {
		handler.sendError(c, err)
		return
	}

	handler.sendResp(c, resp)
	io.Copy(w, src)

	src.Close()
}
`

**Comment by Acconut** [comment]
@aixj1984 If I understand your code correctly, it will not lock an upload for downloading when the upload is completed. That's an interesting idea, but problematic for two reasons: The call to `GetInfo` is not thread-safe, so it expects that a lock is held while the method is called. Furthermore, the logic does not consider uploads, whose length is deferred and not yet known. You might want to check for `info.SizeIsDeferred` to exclude these uploads as well.

You might want to make these adjustments to improve your implementation's reliability.
