### ISSUE TITLE
Is it possible to specify which metadata go to the S3 store?

### ISSUE THREAD

**Issue by akhayyat** [tus/tusd#985]
**Question**
Is it possible to specify which metadata attributes are sent to the S3 store and which are not?

I'm getting the following error:

> response code: 500, response text: s3store: unable to create multipart upload: MetadataTooLarge: Your metadata headers exceed the maximum allowed metadata size.

I wish to be able to disable sending metadata to the S3 store, or to specify which metadata attributes get sent to the S3 store. I still want to be able to receive the full metadata in the http hook.

Is any of this possible? Or is there another way to get all the metadata in the http hook without triggering a MetadataTooLarge error on the S3 store?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: Linux
- Used tusd version: v1.10.1
- Used tusd data storage: OCI Object Storage (s3-compatible)
- Used tusd configuration: `-s3-bucket [...] -s3-endpoint [...] --hooks-enabled-events pre-create,pre-finish --hooks-http [...] -hooks-http-forward-headers Authorization -behind-proxy`
- Used tus client library: tus-js-client 3.1.1

**Comment by Acconut** [comment]
No right now, but in the next major release it will be. v2 will ship with https://github.com/tus/tusd/pull/962, where meta data can be customized (or filtered) in the pre-create hook.

**Comment by Acconut** [comment]
This is possible now since tusd v2. See https://tus.io/blog/2023/09/20/tusd-200 for more details.
